import type { UnitSource } from './types';

// 第二階：習慣｜守住一個服務
export const habit: UnitSource[] = [
  {
    id: 'h-perf',
    name: '把效能當成日常',
    question: '你怎麼知道系統變慢了？在變慢之前先量測。',
    lessons: [
      ['https://blog.codinghorror.com/performance-is-a-feature/', '效能本身就是功能', 'Jeff Atwood 以 Stack Overflow 為例，說明網站速度直接影響使用者體驗，應該當成產品功能來經營。', ['速度對使用者留存與滿意度的影響', '在每個頁面上顯示伺服器處理時間的做法', '效能要持續量測，而不是出事才處理', '前端與後端各自的效能責任']],
      ['https://codeascraft.com/2014/12/11/make-performance-part-of-your-workflow/', '把效能納入工作流程', 'Etsy 分享如何讓效能成為每位工程師的日常：效能預算、自動化量測與部署前檢查。', ['為頁面設定效能預算', '在開發流程中自動量測效能', '讓效能資料對所有人可見', '效能退步時的警示與責任歸屬']],
      ['http://www.brendangregg.com/linuxperf.html', 'Linux 效能分析資源', 'Brendan Gregg 整理的 Linux 效能工具地圖、方法論與演講，是系統效能分析的起點。', ['Linux 效能觀測工具地圖：每個子系統該用哪個工具', 'USE 方法：使用率、飽和度、錯誤', '火焰圖如何呈現處理器時間分布', '靜態調校、基準測試與追蹤工具的分類']],
      ['https://www.igvita.com/2016/05/20/building-fast-and-resilient-web-applications/', '打造快速又有韌性的網頁應用程式', 'Ilya Grigorik 說明在不穩定的行動網路下，如何讓網頁在慢速與失敗情況中仍然可用。', ['行動網路延遲與頻寬的變動性', '關鍵渲染路徑與阻擋渲染的資源', '為第三方資源設定逾時與備援', '以真實使用者量測取代實驗室測試']],
      ['https://medium.com/walmartlabs/the-benefits-of-server-side-rendering-over-client-side-rendering-5d07ff2cefe8', '伺服器端渲染相較於用戶端渲染的好處', 'Walmart Labs 比較兩種渲染方式在首次畫面時間、搜尋引擎收錄與使用者感受上的差異。', ['伺服器端渲染如何縮短首次內容顯示時間', '用戶端渲染的白畫面問題', '伺服器端渲染對搜尋引擎收錄的幫助', '伺服器端渲染帶來的伺服器負擔']],
    ],
  },
  {
    id: 'h-timeout',
    name: '逾時與重試',
    question: '每一次呼叫外部服務，都要先想好「最多等多久」。',
    lessons: [
      ['https://www.javaworld.com/article/2824163/application-performance/stability-patterns-applied-in-a-restful-architecture.html', '在 REST 風格架構中套用穩定性模式', '以 REST 風格服務為例，示範逾時、斷路器與隔艙等穩定性模式的實作方式。', ['為每個外部呼叫設定連線與讀取逾時', '斷路器在連續失敗時快速失敗', '用隔艙隔離不同相依服務的資源', '以非同步處理避免執行緒被卡住']],
      ['https://medium.com/netflix-techblog/fault-tolerance-in-a-high-volume-distributed-system-91ab4faae74a', 'Netflix 高流量分散式系統的容錯設計', 'Netflix 介紹 Hystrix 背後的容錯做法：逾時、重試、執行緒隔離、信號量與斷路器。', ['單一相依服務變慢如何拖垮整個系統', '以執行緒池與信號量隔離每個相依服務', '逾時、斷路器與備援回應的組合', '即時監控每個相依服務的健康狀態']],
      ['https://doordash.engineering/2018/12/21/enforce-timeout-a-doordash-reliability-methodology/', 'DoorDash 的強制逾時可靠性方法', 'DoorDash 說明為什麼要在每一層強制設定逾時，以及如何在服務中落實。', ['沒有逾時的呼叫如何耗盡工作者資源', '從資料庫、快取到外部服務逐層設定逾時', '逾時數值的決定方法', '用監控驗證逾時設定是否合理']],
      ['https://www.ebayinc.com/stories/blogs/tech/a-vip-connection-timeout-issue-caused-by-snat-and-tcp-tw-recycle/', 'eBay 排查 tcp_tw_recycle 造成的連線逾時', 'eBay 追查虛擬 IP 連線逾時的根因：來源位址轉換與 tcp_tw_recycle 核心參數的交互作用。', ['TCP TIME_WAIT 狀態的作用', 'tcp_tw_recycle 在位址轉換環境下的問題', '從封包分析找出間歇性逾時的根因', '調整核心參數前要先理解副作用']],
    ],
  },
  {
    id: 'h-breaker',
    name: '斷路器',
    question: '相依服務壞掉時，如何快速失敗，而不是跟著一起倒下？',
    lessons: [
      ['https://martinfowler.com/bliki/CircuitBreaker.html', '斷路器模式', 'Martin Fowler 說明斷路器的三種狀態，以及它如何防止故障在服務之間蔓延。', ['關閉、開啟、半開三種狀態的切換', '連續失敗達到門檻後快速失敗', '半開狀態如何試探服務是否恢復', '斷路器的狀態變化應該被監控與告警']],
      ['https://www.infoq.com/presentations/circuit-breaking-distributed-systems', '分散式系統中的斷路機制', '演講介紹在大型分散式系統中實作斷路器時，門檻設定、觀測與測試的實務經驗。', ['斷路器在服務呼叫鏈中的位置', '失敗率門檻與觀察時間窗的設定', '用戶端斷路與伺服器端負載卸除的差別', '如何在正式環境驗證斷路器行為']],
      ['https://f5.com/about-us/blog/articles/the-art-of-scaling-containers-circuit-breakers-28919', '擴展容器的藝術：斷路器', 'F5 說明在容器化環境中，由代理伺服器或服務網格實作斷路器的做法。', ['容器快速擴縮時故障的傳播方式', '由代理伺服器集中實作斷路器', '健康檢查與斷路器的配合', '斷路器與負載平衡器的關係']],
      ['https://developers.soundcloud.com/blog/lessons-in-resilience-at-SoundCloud', 'SoundCloud 的韌性課題', 'SoundCloud 從一次事故出發，說明如何在微服務中導入斷路器、逾時與隔艙。', ['單一緩慢服務引發連鎖故障的過程', '在用戶端函式庫加入斷路器', '逾時與重試的設定原則', '從事故整理出的韌性設計清單']],
      ['http://tech.trivago.com/2016/02/23/protector/', 'Trivago 的 Protector：保護時間序列資料庫的斷路器', 'Trivago 開發的代理服務，會在昂貴查詢壓垮時間序列資料庫之前先行阻擋。', ['昂貴查詢如何拖垮監控用的時間序列資料庫', '以規則判斷並拒絕危險查詢', '在資料庫前加一層保護代理的設計', '保護機制與使用者體驗的平衡']],
      ['https://blog.heroku.com/improved-production-stability-with-circuit-breakers', 'Heroku 以斷路器提升正式環境穩定性', 'Heroku 說明在 API 中加入斷路器後，如何在相依服務故障時維持核心功能。', ['找出哪些相依服務需要斷路器', '斷路器開啟時的降級行為', '用指標觀察斷路器的觸發情況', '斷路器參數的調整方式']],
      ['https://medium.com/zendesk-engineering/the-joys-of-circuit-breaking-ee6584acd687', 'Zendesk 的斷路器實踐', 'Zendesk 分享在服務中導入斷路器的過程與實際效果。', ['斷路器解決的是哪一類故障', '函式庫的選擇與整合方式', '失敗門檻與冷卻時間的設定', '導入後故障影響範圍的變化']],
      ['https://medium.com/traveloka-engineering/circuit-breakers-dont-let-your-dependencies-bring-you-down-5ba1c5cf1eec', 'Traveloka：別讓相依服務拖垮你', 'Traveloka 解說斷路器的原理與在旅遊平台中的應用，避免單一供應商故障影響全站。', ['外部供應商故障對旅遊平台的影響', '斷路器狀態機的運作方式', '搭配逾時與備援回應', '監控斷路器以及早發現問題']],
      ['https://shopify.engineering/circuit-breaker-misconfigured', 'Shopify：你的斷路器可能設錯了', 'Shopify 以實例說明斷路器參數設錯時反而會放大故障，並提供估算合理參數的方法。', ['斷路器參數之間的交互作用', '錯誤設定如何讓資源被耗盡', '用數學模型估算最壞情況下的資源使用率', '半開狀態的逾時與重試設定']],
    ],
  },
  {
    id: 'h-isolation',
    name: '隔離與穩態',
    question: '一部分壞掉時，怎麼讓其他部分照常運作？',
    lessons: [
      ['https://skife.org/architecture/fault-tolerance/2009/12/31/bulkheads.html', '隔艙模式：讓故障只影響一部分', '借用船艙分隔的概念，把系統資源分區，讓某一區故障時不會拖垮整體。', ['隔艙模式的由來與核心概念', '依客戶或功能切分資源池', '隔離讓故障範圍變小', '隔艙與資源利用率之間的取捨']],
      ['https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives', '穩態原則：資料檔與日誌檔分開放', 'SQL Server 的最佳實務：資料檔與交易日誌分開存放，避免輸入輸出互相干擾並降低風險。', ['資料檔與日誌檔的輸入輸出模式不同', '放在同一顆磁碟時的效能與復原風險', '日誌持續成長如何塞滿磁碟', '穩態設計：系統要能長期無人介入地運作']],
      ['http://www.sosp.org/2001/papers/welsh.pdf', '節流：分階段事件驅動架構', 'Matt Welsh 的經典論文，把服務拆成以佇列相連的階段，透過節流讓系統在過載時仍保持穩定。', ['分階段事件驅動架構的設計', '每個階段以佇列與執行緒池相連', '過載時由控制器動態調整並拒絕請求', '優雅降級，而不是整體崩潰']],
      ['https://medium.com/booking-com-infrastructure/better-crash-safe-replication-for-mysql-a336a69b317f', 'Booking.com 讓 MySQL 複寫在當機後安全恢復', 'Booking.com 說明 MySQL 複寫在伺服器當機後可能出錯的原因，以及更安全的設定方式。', ['複寫位置資訊與資料不同步的風險', '當機安全複寫需要的設定', '中繼日誌與交易的原子性', '用設定組合減少人工修復']],
      ['https://engineering.linkedin.com/blog/2017/11/improving-resiliency-and-stability-of-a-large-scale-api', 'LinkedIn 以多叢集提升大型單體 API 的韌性', 'LinkedIn 將大型單體 API 服務拆成多個叢集，依流量類型隔離，降低單點故障的影響。', ['單一大叢集的故障影響範圍', '依呼叫者或流量類型切分叢集', '多叢集部署與路由方式', '隔離後在穩定性與容量上的收穫']],
      ['https://engineering.riotgames.com/news/determinism-league-legends-fixing-divergences', '《英雄聯盟》伺服器的確定性', 'Riot Games 讓遊戲伺服器做到可確定重播，藉此重現並修正難以追查的錯誤。', ['確定性執行：相同輸入產生相同結果', '找出並修正造成分歧的原因', '以重播重現正式環境的錯誤', '時間、亂數與浮點數對確定性的影響']],
    ],
  },
  {
    id: 'h-ratelimit',
    name: '限流',
    question: '流量超過能力時，要先拒絕誰？',
    lessons: [
      ['https://www.keycdn.com/support/rate-limiting/', '限流是什麼', '介紹限流的目的與常見演算法，以及在網頁伺服器與 API 上的設定方式。', ['限流保護的對象：伺服器、下游服務與其他使用者', '固定視窗、滑動視窗與權杖桶演算法', '依使用者、來源位址或 API 金鑰計算額度', '被限流時回傳的狀態碼與重試提示']],
      ['https://blog.cloudflare.com/counting-things-a-lot-of-different-things/', 'Cloudflare 為數百萬個網域計數限流', 'Cloudflare 說明在全球邊緣節點上，為海量網域實作限流計數的設計與取捨。', ['為大量不同鍵值計數的記憶體挑戰', '滑動視窗的近似計算方式', '在多個邊緣節點間共享計數', '準確度與效能之間的取捨']],
      ['https://yahooeng.tumblr.com/post/111288877956/cloud-bouncer-distributed-rate-limiting-at-yahoo', 'Yahoo 的 Cloud Bouncer 分散式限流', 'Yahoo 介紹 Cloud Bouncer，一套在多台伺服器之間協調配額的分散式限流系統。', ['單機限流在多台伺服器時的不足', '多台伺服器之間同步使用量的方式', '配額精確度與延遲的取捨', '分散式限流在雲端服務中的應用']],
      ['https://stripe.com/blog/rate-limiters', 'Stripe 以限流器擴展 API', 'Stripe 分享四種限流器：請求速率、並行請求、機群負載卸除與工作者資源保護。', ['請求速率限流器與並行請求限流器', '依請求重要性進行負載卸除', '以權杖桶演算法搭配 Redis 實作', '導入限流器時先觀察、再強制執行']],
      ['https://allegro.tech/2017/04/hermes-max-rate.html', 'Allegro 的分散式限流', 'Allegro 在訊息代理 Hermes 中實作分散式最大速率演算法，避免訂閱者被訊息淹沒。', ['推送型訊息系統為什麼需要限流', '在多個消費者節點之間分配速率額度', '依訂閱者的實際處理能力動態調整', '分散式協調的簡化設計']],
      ['https://www.twilio.com/blog/2017/11/chaos-engineering-ratequeue-ha.html', 'Twilio 的 Ratequeue：佇列與限流核心系統', 'Twilio 說明 Ratequeue 如何兼顧排隊與限流，並用混沌工程驗證它的高可用性。', ['將請求排入佇列並依速率送出的設計', '高可用架構與故障切換', '以混沌工程測試故障情境', '從測試中發現的問題與改進']],
      ['https://engineering.grab.com/quotas-service', 'Grab 的配額服務', 'Grab 設計一套集中式配額服務，讓各個 API 可以依客戶或合作夥伴控管使用量。', ['集中式配額服務的需求', '配額計數的儲存與同步', '在低延遲下檢查配額', '配額與限流的差異']],
      ['https://medium.com/figma-design/an-alternative-approach-to-rate-limiting-f8a06cf7c94c', 'Figma 的另一種限流做法', 'Figma 比較多種限流演算法後，採用滑動視窗計數器的變形，以兼顧準確度與記憶體用量。', ['權杖桶、固定視窗與滑動日誌演算法的優缺點', '滑動視窗計數器的設計', '以 Redis 實作時的記憶體考量', '準確度與實作複雜度的取捨']],
    ],
  },
  {
    id: 'h-lb',
    name: '負載平衡',
    question: '流量進來之後，要怎麼公平又聰明地分出去？',
    lessons: [
      ['https://blog.vivekpanyam.com/scaling-a-web-service-load-balancing/', '擴展網路服務：負載平衡', '從 DNS、第四層到第七層，入門介紹負載平衡的各個層次與做法。', ['DNS 負載平衡的優點與限制', '第四層與第七層負載平衡的差別', '輪流分配、最少連線等分配策略', '健康檢查與故障節點的移除']],
      ['https://blog.envoyproxy.io/introduction-to-modern-network-load-balancing-and-proxying-a57f6ff80236', '現代網路負載平衡與代理入門', 'Envoy 作者 Matt Klein 全面介紹負載平衡器的類型、部署拓撲與功能，是這個主題最好的入門文章之一。', ['第四層（連線層）與第七層（應用層）負載平衡', '集中式代理、邊車代理與用戶端函式庫三種拓撲', '服務探索、健康檢查與黏著工作階段', '全域負載平衡與控制平面']],
      ['https://www.f5.com/company/blog/top-five-scalability-patterns', '五大負載平衡擴展模式', 'F5 整理五種常見的負載平衡擴展模式，從水平複製到依功能與資料分割。', ['水平複製：多台相同伺服器分擔流量', '依功能或路徑分流的第七層模式', '依資料或使用者分割流量', '多種模式組合使用的情境']],
      ['https://www.usenix.org/conference/srecon15europe/program/presentation/shuff', 'Facebook 支撐十三億使用者的負載平衡', 'Facebook 分享從 DNS、邊緣節點到資料中心的多層負載平衡架構。', ['以 DNS 把使用者導向最近的邊緣節點', '邊緣節點與資料中心之間的分層負載平衡', '第四層與第七層負載平衡器的分工', '大規模流量調度與故障處理']],
      ['https://code.facebook.com/posts/1734309626831603/dhcplb-an-open-source-load-balancer/', 'Facebook 的 DHCPLB：開源 DHCP 負載平衡器', 'Facebook 為資料中心 DHCP 服務打造的負載平衡器，用於伺服器開機與網路設定。', ['DHCP 在資料中心伺服器佈建中的角色', '以 Go 撰寫的無狀態負載平衡器', '多台 DHCP 伺服器之間的流量分配', '平順地更新與替換 DHCP 伺服器']],
      ['https://code.facebook.com/posts/1906146702752923/open-sourcing-katran-a-scalable-network-load-balancer/', 'Facebook 的 Katran：可擴展的網路負載平衡器', 'Facebook 開源的第四層負載平衡器，利用 XDP 與 eBPF 在核心中高速轉送封包。', ['以 XDP 在網路驅動層處理封包', 'eBPF 程式的轉送邏輯', '一致性雜湊確保同一連線送到同一台後端', '以 IP 封裝把封包轉送到後端伺服器']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/daperture-load-balancer.html', 'Twitter 的確定性孔徑負載平衡演算法', 'Twitter 在 Finagle 中實作確定性孔徑演算法，讓每個用戶端只連一部分伺服器，同時保持負載均勻。', ['用戶端負載平衡的連線數爆炸問題', '孔徑：每個用戶端只連接一部分伺服器', '以確定性的環狀配置讓負載分布均勻', '連線數與負載平均度的取捨']],
      ['https://medium.com/netflix-techblog/netflix-shares-cloud-load-balancing-and-failover-tool-eureka-c10647ef95e5', 'Netflix 的 Eureka：雲端負載平衡與容錯移轉工具', 'Netflix 開源的服務註冊與探索系統，讓中介層服務在雲端上能負載平衡並自動移除故障節點。', ['服務註冊與服務探索的角色', '用戶端負載平衡如何取得可用節點', '以心跳機制偵測故障節點', '跨可用區的容錯設計']],
      ['https://medium.com/netflix-techblog/netflix-edge-load-balancing-695308b5548c', 'Netflix 的邊緣負載平衡', 'Netflix 在 Zuul 閘道中改良負載平衡演算法，綜合考量伺服器健康度與負載來分配請求。', ['輪流分配在雲端環境的不足', '結合「二選一」與伺服器健康資訊', '保護剛啟動、尚未預熱的伺服器', '伺服器回報負載給負載平衡器的方式']],
      ['https://medium.com/netflix-techblog/open-sourcing-zuul-2-82ea476cb2b3', 'Netflix 開源 Zuul 2 雲端閘道', 'Netflix 介紹改用非同步、非阻塞架構的 Zuul 2，說明它在連線管理與韌性上的改進。', ['從阻塞式改為非同步、非阻塞架構', '大量長連線與推播的支援', '閘道上的路由、重試與流量調度', '非同步架構帶來的除錯難度']],
      ['https://engineeringblog.yelp.com/2017/05/taking-zero-downtime-load-balancing-even-further.html', 'Yelp 讓負載平衡做到零停機', 'Yelp 說明如何在更新 HAProxy 設定與重啟時，不中斷任何使用者連線。', ['重新載入負載平衡器設定時的連線中斷', '讓新連線短暫排隊而不是被丟棄', '以網路層技巧暫存重啟期間的封包', '服務頻繁變動下的零停機']],
      ['https://githubengineering.com/introducing-glb/', 'GitHub 的 GLB 負載平衡器', 'GitHub 介紹自建的負載平衡器 GLB，以及它如何在資料中心內高可用地分配流量。', ['自建負載平衡器的動機', '以等價多路徑路由在多台負載平衡器之間分流', '一致性雜湊與連線保持', '維護時平順地移除負載平衡節點']],
      ['https://medium.com/vimeo-engineering-blog/improving-load-balancing-with-a-new-consistent-hashing-algorithm-9f1bd75709ed', 'Vimeo 以新的一致性雜湊演算法改善負載平衡', 'Vimeo 導入「有界負載一致性雜湊」，在保持快取命中率的同時，避免單一伺服器過載。', ['一致性雜湊在熱門內容下的負載不均', '有界負載：限制每台伺服器的最大負載', '快取命中率與負載平均的取捨', '在 HAProxy 中的實作']],
      ['https://developers.500px.com/udp-load-balancing-with-keepalived-167382d7ad08', '500px 以 Keepalived 做 UDP 負載平衡', '500px 說明如何用 Keepalived 與 IPVS 為 UDP 流量建置高可用的負載平衡。', ['UDP 與 TCP 負載平衡的差異', 'IPVS 核心層負載平衡', 'Keepalived 的健康檢查與虛擬 IP 移轉', '無連線協定的狀態處理']],
      ['https://eng.uber.com/qalm/', 'Uber 的 QALM：服務品質負載管理框架', 'Uber 依請求的重要程度排序，在過載時優先保留關鍵流量、丟棄較不重要的請求。', ['過載時為什麼要區分請求優先順序', '依呼叫者與端點定義重要性', '以佇列延遲判斷是否過載', '在服務的中介層實作負載管理']],
      ['https://www.usenix.org/conference/srecon17europe/program/presentation/rastogi', 'LinkedIn 以真實使用者量測做 DNS 導流', 'LinkedIn 收集真實使用者的效能資料，用來決定 DNS 應該把使用者導向哪個節點。', ['以真實使用者量測評估網路路徑', '依地區與網路業者調整 DNS 回應', '導流決策的自動化', '導流對頁面載入時間的改善']],
      ['https://dropbox.tech/infrastructure/dropbox-traffic-infrastructure-edge-network', 'Dropbox 的流量基礎設施：邊緣網路', 'Dropbox 介紹全球邊緣節點如何接收使用者流量，並透過骨幹網路送回資料中心。', ['邊緣網路接入點的角色', '地理位置 DNS 與任播路由', '在邊緣終止加密連線以降低延遲', '邊緣到資料中心的流量調度']],
      ['https://dropbox.tech/infrastructure/intelligent-dns-based-load-balancing-at-dropbox', 'Dropbox 以 DNS 為基礎的智慧負載平衡', 'Dropbox 利用使用者量測資料與網路拓撲，讓 DNS 回應最適合的邊緣節點。', ['地理位置 DNS 的不足', '以量測資料建立延遲地圖', '利用 DNS 查詢中的用戶端子網路資訊', '自動化更新 DNS 對應表']],
      ['https://stripe.com/en-sg/blog/secret-life-of-dns', 'Stripe 追查 DNS 封包的秘密', 'Stripe 在一次 DNS 問題後，建立對內部 DNS 解析的監控，找出隱藏的查詢量與錯誤。', ['DNS 查詢量暴增的根因', '監控 DNS 伺服器的關鍵指標', '快取設定對 DNS 負載的影響', '從封包分析學到的觀測方式']],
      ['https://medium.com/monday-engineering/how-and-why-we-migrated-our-dns-from-cloudflare-to-a-multi-dns-architecture-part-3-584a470f4062', 'monday.com 的多 DNS 供應商架構', 'monday.com 說明為什麼從單一 DNS 供應商改成多供應商架構，以及遷移的步驟。', ['單一 DNS 供應商的風險', '多家供應商之間的紀錄同步', '遷移過程的測試與切換', '多 DNS 架構的維運成本']],
      ['https://medium.com/hulu-tech-blog/building-hulus-dynamic-anycast-dns-infrastructure-985a7a11fd30', 'Hulu 的動態任播 DNS 基礎設施', 'Hulu 以任播路由與動態健康檢查建立內部 DNS，讓查詢自動導向健康且最近的伺服器。', ['任播路由的原理', '以 BGP 宣告與撤回服務位址', '健康檢查驅動的自動移轉', '任播 DNS 的監控與除錯']],
    ],
  },
  {
    id: 'h-failover',
    name: '容錯移轉',
    question: '主要節點倒下時，備援要怎麼接手？',
    lessons: [
      ['http://cloudpatterns.org/mechanisms/failover_system', '容錯移轉系統', '雲端運算模式目錄中的容錯移轉機制，說明雙主動與主備兩種備援的運作方式。', ['雙主動與主備兩種備援架構', '故障偵測與自動切換', '切換期間的服務中斷時間', '資料同步對移轉的影響']],
      ['https://www.usenix.org/conference/srecon15/program/presentation/taveira', '依靠軟體在各層可靠地轉送流量', '演講說明如何在 DNS、負載平衡與應用程式等不同層次，用軟體自動化地轉送流量。', ['流量轉送可以發生的層次', '各層轉送的反應速度與影響範圍', '自動化轉送的安全機制', '避免轉送本身造成新的故障']],
      ['https://www.usenix.org/conference/srecon16/program/presentation/heady', '全球流量路由與容錯移轉的演進', '演講回顧全球流量路由如何從手動切換，演進到自動化的容錯移轉。', ['DNS 路由與任播路由的比較', '自動偵測區域故障並移轉流量', '移轉時的容量規劃', '避免移轉造成連鎖過載']],
      ['https://www.usenix.org/conference/srecon17asia/program/presentation/liu_zehua', '災難復原的容錯移轉演練', '演講分享如何定期演練資料中心層級的容錯移轉，確保災難發生時真的能切換。', ['災難復原計畫為什麼需要定期演練', '演練範圍：服務、資料中心與區域', '演練前後的檢查清單', '從演練中發現的隱藏相依']],
      ['https://blog.risingstack.com/designing-microservices-architecture-for-failure/', '為故障設計微服務架構', 'RisingStack 整理微服務常用的容錯模式：優雅降級、變更管理、健康檢查、自我修復與斷路器。', ['優雅降級與備援回應', '變更管理：金絲雀部署與回滾', '健康檢查與負載平衡', '逾時、重試、限流與斷路器']],
      ['https://engineering.gosquared.com/use-elb-automatic-failover', 'GoSquared 以 AWS 負載平衡器做自動容錯移轉', 'GoSquared 利用 AWS 的彈性負載平衡服務，自動偵測並繞過故障的機器。', ['負載平衡器健康檢查的設定', '跨可用區部署', '故障機器的自動移除', '雲端負載平衡器的限制']],
      ['http://americanexpress.io/eliminate-the-database-for-higher-availability/', 'American Express 移除資料庫依賴以提升可用性', 'American Express 說明如何讓讀取路徑不再即時依賴資料庫，使服務在資料庫故障時仍可運作。', ['資料庫成為單點故障的風險', '以預先產生的資料取代即時查詢', '把靜態化資料發布到多個位置', '可用性與資料新鮮度的取捨']],
      ['http://engineering.vinted.com/2015/09/03/failover-with-redis-sentinel/', 'Vinted 以 Redis Sentinel 做容錯移轉', 'Vinted 分享以 Redis Sentinel 監控主節點，並自動提升備援節點的設定與經驗。', ['Sentinel 的監控與投票機制', '主節點故障時的自動提升', '用戶端如何得知新的主節點', '網路分割時的腦裂風險']],
      ['http://engineering.freeagent.com/2017/02/06/ha-infrastructure-without-breaking-the-bank/', 'FreeAgent 低成本的高可用基礎設施', 'FreeAgent 分享在有限預算下，打造高可用軟體即服務基礎設施的做法。', ['找出單點故障並逐一消除', '資料庫的主從備援與移轉', '在成本與可用性之間取捨', '定期演練移轉流程']],
      ['https://github.blog/2018-06-20-mysql-high-availability-at-github/', 'GitHub 的 MySQL 高可用架構', 'GitHub 說明以 Orchestrator、Consul 與 GLB 組成的 MySQL 主節點自動移轉方案。', ['以 Orchestrator 偵測故障並提升新主節點', '以 Consul 發布主節點位址', '不再使用虛擬 IP 的理由', '半同步複寫降低資料遺失']],
      ['https://www.eventbrite.com/engineering/mysql-high-availability-at-eventbrite/', 'Eventbrite 的 MySQL 高可用架構', 'Eventbrite 分享 MySQL 主從架構的移轉方式與維運工具。', ['主從複寫與自動移轉', '移轉時的資料一致性檢查', '應用程式如何重新連線', '演練與監控移轉流程']],
      ['https://medium.com/walmartlabs/business-continuity-disaster-recovery-in-the-microservices-world-ef2adca363df', 'Walmart 微服務時代的營運持續與災難復原', 'Walmart 說明在微服務架構下規劃營運持續與災難復原的方法。', ['復原時間目標與復原點目標', '多區域的雙主動與主備部署', '資料複寫與一致性', '災難復原演練']],
    ],
  },
  {
    id: 'h-autoscale',
    name: '自動擴展',
    question: '流量上下起伏時，機器數量如何自動跟上？',
    lessons: [
      ['https://medium.com/@BotmetricHQ/top-11-hard-won-lessons-learned-about-aws-auto-scaling-5bfe56da755f', 'AWS 自動擴展的十一個教訓', '整理使用 AWS 自動擴展群組時最常踩到的坑，例如冷啟動、指標選擇與縮減策略。', ['選擇適當的擴展指標', '新機器冷啟動與健康檢查的等待時間', '擴展與縮減的冷卻時間', '預先建置映像檔以加快啟動']],
      ['https://medium.com/@Pinterest_Engineering/auto-scaling-pinterest-df1d2beb4d64', 'Pinterest 的自動擴展', 'Pinterest 說明如何依流量預測與即時指標自動調整機群大小，並處理擴展中的各種問題。', ['排程與指標並用的擴展策略', '新機器上線前的預熱', '容量不足與過度擴展的成本', '擴展系統本身的可靠性']],
      ['https://medium.com/square-corner-blog/autoscaling-based-on-request-queuing-c4c0f57f860f', 'Square 依請求排隊時間自動擴展', 'Square 發現處理器使用率不是好的擴展指標，改以請求在佇列中等待的時間作為依據。', ['以處理器使用率作為擴展指標的問題', '請求排隊時間反映真實的使用者延遲', '量測排隊時間的方法', '擴展門檻的設定']],
      ['http://tech.trivago.com/2017/02/17/your-definite-guide-for-autoscaling-jenkins/', 'Trivago 的 Jenkins 自動擴展指南', 'Trivago 讓 Jenkins 建置節點依排隊的工作數量自動增減，以降低成本並縮短等待。', ['建置排隊造成的開發者等待', '依佇列長度動態建立建置節點', '閒置節點的回收', '雲端建置節點的成本控制']],
      ['https://labs.spotify.com/2017/11/20/autoscaling-pub-sub-consumers/', 'Spotify 自動擴展發布／訂閱消費者', 'Spotify 依訂閱佇列的積壓量自動調整消費者數量，避免訊息延遲。', ['以積壓訊息量作為擴展依據', '消費者擴展的上下限', '避免頻繁擴縮的平滑策略', '與 Kubernetes 的整合']],
      ['https://labs.spotify.com/2018/12/18/bigtable-autoscaler-saving-money-and-time-using-managed-storage/', 'Spotify 依處理器負載自動擴展 Bigtable 叢集', 'Spotify 開源 Bigtable 自動擴展工具，依處理器使用率調整節點數以節省成本。', ['託管資料庫也需要容量管理', '以處理器使用率決定節點數', '擴展速度與穩定性的取捨', '節省成本的實際效果']],
      ['https://engineeringblog.yelp.com/2019/06/autoscaling-aws-step-functions-activities.html', 'Yelp 自動擴展 AWS Step Functions 的工作者', 'Yelp 為 Step Functions 的活動工作者設計自動擴展，依待處理的工作量調整容量。', ['工作流程中活動工作者的角色', '以待處理工作數量作為擴展指標', '長時間工作在縮減時的處理', '擴展延遲對工作流程的影響']],
      ['https://medium.com/netflix-techblog/scryer-netflixs-predictive-auto-scaling-engine-a3f8fc922270', 'Netflix 的 Scryer：預測式自動擴展引擎', 'Netflix 以歷史流量預測未來需求並提前擴展機群，避免反應式擴展來不及。', ['反應式擴展的延遲問題', '依歷史模式預測流量', '預測式與反應式擴展的搭配', '異常流量下的保護機制']],
      ['https://medium.com/palantir/bouncer-simple-aws-auto-scaling-rollovers-c5af601d65d4', 'Palantir 的 Bouncer：安全地替換自動擴展群組', 'Palantir 開源的工具，能安全地逐台替換自動擴展群組中的機器以完成部署。', ['替換自動擴展群組機器的挑戰', '逐台替換與整批替換兩種模式', '替換時的健康檢查', '失敗時的中止與復原']],
      ['https://engineeringblog.yelp.com/2019/02/autoscaling-mesos-clusters-with-clusterman.html', 'Yelp 的 Clusterman：自動擴展 Mesos 叢集', 'Yelp 開發 Clusterman，依叢集資源需求自動增減節點，並能用模擬器測試擴展策略。', ['叢集層級與服務層級擴展的差異', '以資源使用率驅動節點數', '用模擬器評估擴展策略', '混用競價機器降低成本']],
    ],
  },
  {
    id: 'h-resilience',
    name: '為失敗而設計',
    question: '如果故障一定會發生，你要怎麼設計？',
    lessons: [
      ['https://queue.acm.org/detail.cfm?id=3096459&__s=dnkxuaws9pogqdnxmx8i', '服務可用性的計算', 'Google 工程師說明可用性如何由相依服務組成，以及如何用數學估算並提升整體可用性。', ['串聯的相依服務如何拉低整體可用性', '每個相依服務的可用性預算', '以備援、降級與隔離減少相依的影響', '可用性目標與工程成本的取捨']],
      ['http://highscalability.com/blog/2012/12/31/designing-for-resiliency-will-be-so-2013.html', '為韌性而設計', '整理打造韌性系統的原則：接受故障、隔離影響、快速恢復，並在設計階段就考慮失敗。', ['假設每個元件都會故障', '隔離故障，避免連鎖反應', '快速偵測與自動恢復', '用測試驗證韌性設計']],
      ['https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/self-healing', '為自我修復而設計', '微軟 Azure 架構指南：讓系統能偵測故障、優雅回應並自動恢復。', ['重試暫時性錯誤', '以斷路器保護失敗的遠端服務', '隔離關鍵資源並平準負載', '容錯移轉、補償交易與檢查點', '優雅降級與故障注入測試']],
      ['https://www.usenix.org/conference/srecon17asia/program/presentation/wang_daxin', '接受部分失敗，把服務損失降到最低', '演講分享在大型服務中接受部分失敗的設計思維，以降級與隔離把影響縮到最小。', ['部分失敗是大型系統的常態', '依功能重要性分級降級', '限制故障的影響範圍', '用指標衡量服務損失']],
      ['https://queue.acm.org/detail.cfm?id=2371297', '韌性工程：學會擁抱失敗', 'ACM Queue 的座談，Google、Amazon 等公司的工程師分享故障演練與韌性工程的實踐。', ['韌性工程的定義與目標', '以大規模故障演練檢驗系統', '組織文化如何影響故障應對', '從事故中學習，而不是追究責任']],
      ['https://www.usenix.org/conference/srecon17americas/program/presentation/rosenthal', '混沌工程原則', 'Netflix 混沌工程團隊說明混沌工程的定義與原則：在正式環境中用實驗建立對系統的信心。', ['定義穩態並以指標衡量', '假設穩態在實驗組與對照組都會維持', '引入真實世界的故障事件', '在正式環境中執行並自動化實驗', '把爆炸半徑降到最小']],
      ['https://www.usenix.org/conference/srecon17americas/program/presentation/andrus', '刻意破壞：故障注入實踐', '演講介紹在正式環境中以受控方式注入故障，找出系統弱點的方法。', ['故障注入的目的與風險', '從小規模實驗開始', '設計安全的中止機制', '把實驗結果轉成改善行動']],
      ['https://www.usenix.org/conference/srecon16/program/presentation/lueder', '在混沌中找出秩序', '演講分享如何以混沌實驗與監控，在複雜的微服務系統中找出隱藏的故障模式。', ['複雜系統中的突現行為', '以實驗找出未知的故障模式', '用指標判斷實驗的影響', '自動化的混沌實驗平台']],
      ['https://engineering.linkedin.com/blog/2017/11/resilience-engineering-at-linkedin-with-project-waterbear', 'LinkedIn 的 Waterbear 韌性工程計畫', 'LinkedIn 以 Waterbear 計畫在正式環境注入故障，推動各服務改善韌性與降級設計。', ['請求層級的故障注入', '服務相依關係與預設的降級行為', '讓故障演練成為開發流程的一部分', '推動韌性改善的方式']],
      ['https://tech.iheart.com/resiliency-against-traffic-oversaturation-77c5ed92a5fb', 'iHeartRadio 對抗流量過載的韌性設計', 'iHeartRadio 分享在流量暴增時保護服務的做法，包括限流、快取與優雅降級。', ['流量尖峰對串流服務的衝擊', '在邊緣層限流與快取', '非必要功能的降級', '容量規劃與壓力測試']],
      ['https://blog.gojekengineering.com/resiliency-in-distributed-systems-efd30f74baf4', 'GO-JEK 的分散式系統韌性', 'GO-JEK 整理在分散式系統中建立韌性的實務：逾時、重試、斷路器、冪等性與降級。', ['為每個網路呼叫設定逾時', '搭配指數退避與隨機抖動的重試', '斷路器與備援回應', '冪等性讓重試變得安全']],
      ['https://www.ebayinc.com/stories/blogs/tech/practical-nosql-resilience-design-pattern-for-the-enterprise/', 'eBay 企業級 NoSQL 韌性設計模式', 'eBay 提出一套在應用層包裝 NoSQL 存取的韌性模式，處理故障切換與一致性。', ['NoSQL 叢集故障對應用程式的影響', '在資料存取層實作重試與切換', '多資料中心的讀寫路由', '一致性等級的動態調整']],
      ['https://quoraengineering.quora.com/Ensuring-Quoras-Resilience-to-Disaster', 'Quora 確保災難韌性的做法', 'Quora 說明如何為資料與服務建立備份、跨區複寫與復原流程，以因應重大災難。', ['定義需要保護的資料與服務', '備份與跨區域複寫', '復原流程的演練', '復原時間與成本的取捨']],
      ['https://www.infoq.com/presentations/expedia-website-resiliency?utm_source=presentations_about_Case_Study&utm_medium=link&utm_campaign=Case_Study', 'Expedia 的網站韌性', 'Expedia 演講分享如何在大型旅遊網站中導入韌性設計與故障演練。', ['相依服務故障對訂房流程的影響', '降級與備援策略', '韌性測試與演練', '從事故中持續改進']],
      ['https://tech.ebayinc.com/engineering/resiliency-and-disaster-recovery-with-kafka/', 'eBay 以 Kafka 實現韌性與災難復原', 'eBay 說明如何設計跨資料中心的 Kafka 架構，讓資料中心故障時仍能持續傳遞訊息。', ['跨資料中心的 Kafka 部署方式', '生產者與消費者的切換策略', '訊息重複與遺失的處理', '災難復原演練']],
      ['https://eng.uber.com/kafka/', 'Uber 多區域 Kafka 的災難復原', 'Uber 說明以多區域 Kafka 叢集與 uReplicator 實現災難復原，並處理消費位置的切換。', ['區域叢集與彙總叢集的架構', '跨區域的訊息複寫', '雙主動與主備兩種消費模式', '移轉時消費位置的對應']],
    ],
  },
  {
    id: 'h-ha',
    name: '高可用的實戰案例',
    question: '別人是怎麼把可用性做到好幾個九的？',
    lessons: [
      ['http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/36737.pdf', 'Google 全球分散式儲存系統的可用性', 'Google 分析大規模儲存叢集的故障資料，建立模型說明節點故障、相關故障與複寫策略對可用性的影響。', ['節點故障的頻率與持續時間', '機架、電源等相關故障比獨立故障更危險', '複寫與編碼策略對可用性的影響', '以模型預測資料不可用的機率']],
      ['https://yahooeng.tumblr.com/post/68823943185/nodejs-high-availability', 'Yahoo 的 Node.js 高可用實踐', 'Yahoo 分享在正式環境執行 Node.js 服務時，確保高可用的行程管理與監控方式。', ['單執行緒事件迴圈的風險', '以多個行程與叢集模式利用多核心', '行程當機的自動重啟', '監控與優雅關閉']],
      ['https://www.linkedin.com/pulse/introduction-every-day-monday-operations-benjamin-purgason', 'LinkedIn 的維運系列文章', 'LinkedIn 網站可靠性工程師撰寫的十一篇系列文章，介紹日常維運、值班與事故處理的實務。', ['網站可靠性工程師的日常工作', '值班與告警的設計', '事故處理與事後檢討', '以自動化減少重複勞動']],
      ['https://www.usenix.org/conference/srecon17americas/program/presentation/barot', '監控如何支撐 LinkedIn 動態消息的高可用', 'LinkedIn 說明如何以完善的監控與告警，讓動態消息服務維持高可用性。', ['動態消息服務的關鍵指標', '以監控及早發現異常', '告警與值班流程', '監控資料在事故分析中的角色']],
      ['https://code.facebook.com/posts/166966743929963/how-production-engineers-support-global-events-on-facebook/', 'Facebook 如何撐住全球重大活動', 'Facebook 的正式環境工程師分享在跨年、世界盃等全球活動期間，如何規劃容量與應變。', ['預測重大活動的流量高峰', '容量規劃與壓力測試', '活動期間的值班與戰情室', '事後檢討與經驗累積']],
      ['https://medium.com/blablacar-tech/the-expendables-backends-high-availability-at-blablacar-8cea3b95b26b', 'BlaBlaCar 的後端高可用架構', 'BlaBlaCar 說明如何讓後端服務隨時可以被替換，並以服務探索維持高可用。', ['把服務視為可隨時替換的元件', '服務探索與健康檢查', '資料庫的高可用設計', '自動化部署與移轉']],
      ['https://medium.com/@NetflixTechBlog/tips-for-high-availability-be0472f2599c', 'Netflix 的高可用技巧', 'Netflix 整理維持高可用的實務建議：部署策略、快速回滾、相依管理與故障演練。', ['漸進式部署與自動化金絲雀分析', '快速回滾的能力', '相依服務的逾時與備援', '定期進行故障演練']],
      ['https://www.twilio.com/engineering/2011/12/12/scaling-high-availablity-infrastructure-in-cloud', 'Twilio 在雲端的高可用基礎設施', 'Twilio 分享在雲端上打造高可用通訊服務的原則：無狀態、自動化與跨區部署。', ['把狀態從主機中移除', '跨可用區與區域的部署', '自動化佈建與替換主機', '以佇列吸收流量尖峰']],
      ['https://airbnb.tech/infrastructure/achieving-high-availability-with-distributed-database-on-kubernetes-at-airbnb/', 'Airbnb 在 Kubernetes 上以分散式資料庫達成高可用', 'Airbnb 說明在 Kubernetes 上執行分散式資料庫時，如何處理節點替換、跨區部署與資料安全。', ['有狀態服務在 Kubernetes 上的挑戰', '跨可用區的資料庫部署', '節點替換時的資料保護', '自動化維運與監控']],
      ['https://dropbox.tech/infrastructure/automating-datacenter-operations-at-dropbox', 'Dropbox 自動化資料中心維運', 'Dropbox 介紹如何自動化伺服器的上架、維修與汰換流程，減少人工操作並提升可用性。', ['資料中心維運的重複性工作', '以工作流程系統自動化硬體生命週期', '維修時的流量移轉', '自動化帶來的可靠性提升']],
      ['https://technology.riotgames.com/news/globalizing-player-accounts', 'Riot Games 全球化玩家帳號系統', 'Riot Games 將分散在各地區的玩家帳號整合為全球系統，並兼顧延遲與可用性。', ['地區帳號系統的限制', '全球資料複寫的設計', '就近讀取與寫入的取捨', '遷移大量帳號的過程']],
    ],
  },
];
