import type { UnitSource } from './types';

// 第一階：知識｜看懂一個概念
export const knowledge: UnitSource[] = [
  {
    id: 'k-scale',
    name: '規模會改變什麼',
    question: '使用者從一百人變成一百萬人，系統哪裡會先出問題？',
    lessons: [
      ['https://lethain.com/introduction-to-architecting-systems-for-scale/', '大型系統架構入門', '從負載平衡、快取、非同步處理到平台層，一篇文章看完網站成長時最常用的擴展手段。', ['負載平衡如何分散流量並提供備援', '快取可以放在哪幾層：應用程式、資料庫、記憶體快取', '快取失效的常見策略與風險', '為什麼要把耗時工作改成非同步處理', '用平台層隔離應用程式與資料庫的好處']],
      ['https://blog.codinghorror.com/scaling-up-vs-scaling-out-hidden-costs/', '垂直擴展與水平擴展的隱藏成本', '比較「買更大的機器」與「加更多機器」兩條路，在軟體授權、電力、機房與維運上的真實成本。', ['垂直擴展與水平擴展的差別', '軟體授權費用如何影響擴展的總成本', '電力、機櫃空間與維運人力等隱藏成本', '什麼情況下單台大機器反而比較划算']],
      ['http://ithare.com/scaling-stateful-objects/', '無狀態與有狀態服務的擴展', '解釋為什麼無狀態服務容易擴展，而帶狀態的物件（例如遊戲房間、交易）需要不同的切分方式。', ['無狀態服務為何可以隨意增加機器', '把狀態全推到資料庫，資料庫就會變成瓶頸', '有狀態物件的擴展：依物件切分到不同伺服器', '記憶體內狀態與持久化之間的取捨']],
      ['https://www.somethingsimilar.com/2013/01/14/notes-on-distributed-systems-for-young-bloods/', '給分散式系統新手的筆記', '一份寫給剛接觸分散式系統的工程師的經驗清單：失敗是常態、協調很昂貴、要用量測結果說話。', ['為什麼分散式系統經常「部分失敗」', '多台機器之間的協調為什麼困難又昂貴', '在整個系統實作背壓，避免過載擴散', '用百分位數而不是平均值看效能', '學會估算容量，並設計部分可用的降級方式']],
      ['https://blog.codinghorror.com/my-scaling-hero/', '我的擴展英雄', 'Jeff Atwood 介紹一人團隊如何用少量伺服器撐起大型交友網站，說明精簡架構的威力。', ['單人維運的大型網站如何保持架構精簡', '用少量強大伺服器承載大量流量的做法', '快取與資料庫調校在小團隊中的效果', '先把簡單的事情做好的擴展心法']],
      ['https://people.eecs.berkeley.edu/~brewer/papers/GiantScale-IEEE.pdf', '巨型網路服務的經驗教訓', 'Eric Brewer 從大型網路服務歸納出可用性指標、DQ 原則與優雅降級等經典觀念。', ['用產出率與收穫率衡量可用性', 'DQ 原則：資料量乘以查詢量受限於系統容量', '複寫與分割在故障時的不同影響', '優雅降級：故障時保留最重要的功能', '線上服務的滾動升級策略']],
      ['https://www.cs.cornell.edu/projects/ladis2009/talks/dean-keynote-ladis2009.pdf', '打造大型分散式系統的設計、教訓與建議', 'Jeff Dean 在 2009 年的主題演講，分享 Google 基礎設施的設計模式、延遲數字與容錯經驗。', ['每個工程師都該知道的延遲數字', '用紙上估算快速評估設計是否可行', '在大量不可靠的機器上設計可靠服務', '為十倍成長設計，在百倍成長前規劃重寫']],
      ['https://static.googleusercontent.com/media/research.google.com/en//people/jeff/stanford-295-talk.pdf', '大型分散式系統的軟體工程建議', 'Jeff Dean 在史丹佛的演講，談 Google 系統的演進，以及設計大型系統時的實務建議。', ['Google 搜尋系統從早期到後來的架構演進', '紙上估算與延遲數字在設計中的用途', '設計時要考慮的故障類型與頻率', '讓系統容易量測與除錯的設計習慣']],
      ['http://mvdirona.com/jrh/work/', 'James Hamilton 談效率、可靠性與擴展', 'AWS 副總裁 James Hamilton 的論文與演講彙整，涵蓋資料中心效率與大型服務的維運原則。', ['設計與部署網際網路級服務的經驗法則', '資料中心的成本結構：伺服器、電力與散熱', '用自動化維運降低人為錯誤', '為故障而設計：假設所有元件都會壞']],
    ],
  },
  {
    id: 'k-latency',
    name: '延遲、瓶頸與快取的直覺',
    question: '一個請求的時間，到底花在哪裡？',
    lessons: [
      ['http://norvig.com/21-days.html#answers', '每個程式設計師都該知道的延遲數字', 'Peter Norvig 在〈十年學會程式設計〉附上的一張表，列出記憶體、磁碟與網路操作的典型耗時。', ['處理器快取、主記憶體、固態硬碟與網路往返的量級差距', '記憶體存取與磁碟尋軌差了好幾個數量級', '同一資料中心與跨洲網路往返的延遲差異', '如何用延遲數字做紙上估算']],
      ['http://highscalability.com/latency-everywhere-and-it-costs-you-sales-how-crush-it', '延遲無所不在，而且讓你損失營收', '整理延遲如何影響使用者行為與營收，並列出從前端到後端降低延遲的各種手法。', ['延遲對轉換率與營收的影響', '延遲的來源：網路、伺服器處理、資料庫與前端渲染', '降低延遲的手法：快取、預先運算、就近部署', '尾端延遲為什麼比平均延遲更重要']],
      ['https://blogs.msdn.microsoft.com/csliu/2009/08/27/io-concept-blockingnon-blocking-vs-syncasync/', '阻塞與非阻塞、同步與非同步', '釐清兩組常被混用的輸入輸出概念，並對照作業系統提供的各種輸入輸出模型。', ['阻塞與非阻塞的差別：呼叫會不會等待', '同步與非同步的差別：結果由誰通知', 'select、epoll 這類多工機制屬於哪一種模型', '不同輸入輸出模型對伺服器擴展能力的影響']],
      ['https://www.cse.wustl.edu/~jain/cse567-06/ftp/os_monitors/index.html', '作業系統效能監控工具總覽', '大學課程報告，整理作業系統層級的效能監控工具，以及它們各自能量測的指標。', ['處理器、記憶體、磁碟與網路各自該看哪些指標', '常見系統監控工具的原理與差異', '監控本身帶來的額外負擔', '從底層指標推論應用程式的瓶頸']],
      ['http://veithen.github.io/2013/11/18/iowait-linux.html', 'Linux 輸入輸出等待時間的真正意義', '說明 Linux 的 iowait 指標是怎麼算出來的，以及為什麼它常被誤讀。', ['iowait 其實是「處理器閒置且有未完成輸入輸出」的時間', '為什麼 iowait 高不一定代表磁碟是瓶頸', '多核心環境下解讀 iowait 的陷阱', '判斷輸入輸出瓶頸時該搭配的其他指標']],
      ['http://highscalability.com/blog/2014/5/12/4-architecture-issues-when-scaling-web-applications-bottlene.html', '擴展網頁應用程式時的四個架構問題', '從回應時間與擴展性的關係出發，逐一分析資料庫、處理器與輸入輸出的常見瓶頸。', ['回應時間與擴展性之間的關係', '負載平衡與無狀態設計的必要性', '資料庫成為瓶頸時的對策：快取、讀寫分離、分片', '處理器密集與輸入輸出密集工作的不同處理方式']],
      ['http://highscalability.com/blog/2012/5/16/big-list-of-20-common-bottlenecks.html', '二十個常見瓶頸清單', '一份涵蓋資料庫、虛擬化、程式設計與網路的常見效能瓶頸清單。', ['資料庫：工作集超出記憶體、鎖競爭、慢查詢', '虛擬化環境下磁碟與網路的效能波動', '執行緒、事件驅動與阻塞呼叫帶來的程式瓶頸', '缺乏效能剖析與追蹤，讓瓶頸難以被發現']],
      ['https://www.stevesouders.com/blog/2012/10/11/cache-is-king/', '快取為王', 'Steve Souders 用實驗說明瀏覽器快取對網頁載入速度的影響，以及快取設定的常見問題。', ['瀏覽器快取對重複造訪速度的影響', 'Cache-Control 與 Expires 標頭的正確設定', '快取空間不足時資源被淘汰的問題', '為靜態資源加上版本號，放心長期快取']],
      ['https://www.the-paper-trail.org/post/2014-06-06-paper-notes-anti-caching/', '論文筆記：反快取架構', '解讀 H-Store 團隊的反快取論文：讓記憶體成為主要儲存，只把冷資料移到磁碟。', ['傳統「磁碟為主、記憶體快取」架構的限制', '反快取：記憶體為主，冷資料才寫到磁碟', '如何追蹤資料冷熱並決定淘汰對象', '存取已淘汰資料時的交易處理方式']],
    ],
  },
  {
    id: 'k-consistency',
    name: '一致性與取捨',
    question: '資料放在很多台機器上時，「正確」代表什麼？',
    lessons: [
      ['http://robertgreiner.com/2014/08/cap-theorem-revisited/', '重新認識 CAP 定理', '用清楚的圖解說明一致性、可用性與分割容忍，以及網路分割時只能在前兩者取其一的真正含義。', ['CAP 中一致性、可用性與分割容忍的定義', '為什麼分散式系統無法放棄分割容忍', '網路分割時在一致性與可用性之間的抉擇', '重視一致性與重視可用性的系統行為差異']],
      ['https://blog.andyet.com/2014/10/01/right-database', '重視一致性或可用性：選對資料庫', '從應用需求出發，說明何時該選重視一致性的資料庫、何時該選重視可用性的資料庫。', ['依業務需求決定一致性或可用性的優先順序', '重視一致性的資料庫在網路分割時拒絕寫入的後果', '重視可用性的資料庫接受寫入後如何處理衝突', '常見資料庫在 CAP 光譜上的位置']],
      ['https://neo4j.com/blog/acid-vs-base-consistency-models-explained/', 'ACID 與 BASE：兩種一致性模型', '比較傳統資料庫的 ACID 交易保證，與許多 NoSQL 系統採用的 BASE 最終一致模型。', ['ACID 四個性質：原子性、一致性、隔離性、持久性', 'BASE：基本可用、軟狀態、最終一致', '兩種模型各自適合的業務情境', '在同一個系統中混用兩種模型的考量']],
      ['https://www.allthingsdistributed.com/2008/12/eventually_consistent.html', '最終一致性', 'Amazon 技術長 Werner Vogels 的經典文章，定義各種一致性等級，以及它們在大型系統中的取捨。', ['強一致性、弱一致性與最終一致性的定義', '讀取自己寫入、單調讀取等一致性變體', '副本數量與讀寫法定人數（N、R、W）的關係', '為什麼大型系統常選擇最終一致性']],
      ['http://elliot.land/post/sql-transaction-isolation-levels-explained', 'SQL 交易隔離等級圖解', '用範例說明四種隔離等級，以及髒讀、不可重複讀與幻讀分別在什麼情況下發生。', ['讀取未提交、讀取已提交、可重複讀、可序列化四種等級', '髒讀、不可重複讀與幻讀的差異', '隔離等級越高，並行效能越低的原因', '依業務需求選擇適當的隔離等級']],
      ['http://highscalability.com/blog/2011/2/10/database-isolation-levels-and-their-effects-on-performance-a.html', '資料庫隔離等級對效能與擴展性的影響', '說明不同隔離等級如何透過鎖與多版本控制影響並行度，進而影響資料庫的效能與擴展能力。', ['以鎖實作隔離與以多版本並行控制實作隔離的差異', '較低的隔離等級如何提升吞吐量', '隔離等級不足時可能出現的資料異常', '在效能與正確性之間找到平衡點']],
      ['https://queue.acm.org/detail.cfm?id=3025012', '超越分散式交易的生活', 'Pat Helland 的經典論文：當系統大到無法使用分散式交易時，應用程式該如何設計。', ['為什麼分散式交易在極大規模下難以使用', '以「實體」作為交易範圍的設計方式', '實體之間透過訊息溝通，並接受最終一致', '訊息可能重複送達時的冪等性處理']],
      ['https://martin.kleppmann.com/2017/01/26/data-loss-in-large-clusters.html', '大型叢集中遺失資料的機率', 'Martin Kleppmann 計算節點數量增加時，三副本系統遺失資料的機率如何上升。', ['節點越多，同時故障的機率越高', '三個副本並不代表資料永遠安全', '副本放置策略對遺失機率的影響', '用機率思考資料持久性']],
      ['https://research.google.com/archive/paxos_made_live.html', 'Paxos 實戰：工程觀點', 'Google 將 Paxos 共識演算法實作於 Chubby 的經驗，揭露理論與工程實作之間的巨大落差。', ['Paxos 共識演算法要解決的問題', '從論文到正式系統需要補上的工程細節', '磁碟損毀、主節點租約與成員變更的處理', '如何測試一個容錯系統的正確性']],
    ],
  },
  {
    id: 'k-data',
    name: '資料放在哪裡：選型與分片',
    question: '資料多到一台機器放不下時，要怎麼選資料庫、怎麼切？',
    lessons: [
      ['https://www.upwork.com/hiring/data/sql-vs-nosql-databases-whats-the-difference/', 'SQL 與 NoSQL 資料庫有什麼不同', '入門比較關聯式與非關聯式資料庫在資料模型、結構彈性與擴展方式上的差異。', ['關聯式資料表與文件、鍵值、欄式、圖形等資料模型', '預先定義結構與彈性結構的取捨', '兩類資料庫在垂直與水平擴展上的差別', '依查詢模式選擇資料庫的思考方式']],
      ['https://engineering.salesforce.com/sql-or-nosql-9eaf1d92545b', 'SQL 還是 NoSQL：Salesforce 的經驗', 'Salesforce 工程師分享在實際產品中選擇資料庫的判斷依據與踩過的坑。', ['先釐清存取模式再選資料庫', '交易需求對資料庫選擇的影響', '關聯式資料庫其實也能擴展得很遠', 'NoSQL 帶來的維運與一致性成本']],
      ['https://medium.baqend.com/nosql-databases-a-survey-and-decision-guidance-ea7823a822d', 'NoSQL 資料庫綜覽與選擇指南', '從分片、複寫、儲存管理與查詢處理四個面向，系統化比較主流 NoSQL 資料庫並提供決策樹。', ['分片、複寫、儲存管理與查詢處理四個比較面向', '範圍分片與雜湊分片的差異', '依一致性、延遲與查詢能力選資料庫的決策樹', '主流 NoSQL 系統的設計取捨對照']],
      ['https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn271399(v=pandp.10)', '高擴展方案的資料存取：SQL、NoSQL 與多種資料庫並用', '微軟模式與實踐指南，說明如何在同一個系統中依資料特性混用多種資料庫。', ['多種資料庫並用：不同資料放在最適合的資料庫', '鍵值、文件、欄族與圖形資料庫的適用情境', '跨多個資料庫時的一致性挑戰', '以購物網站為例的資料庫組合設計']],
      ['https://use-the-index-luke.com/sql/testing-scalability', '資料庫的效能與擴展性測試', '《Use The Index, Luke》的章節，說明資料量與負載增加時，索引如何決定查詢能不能擴展。', ['資料量成長時查詢回應時間的變化', '正確的索引讓查詢時間幾乎不隨資料量增加', '系統負載增加時的回應時間曲線', '加硬體也解決不了的索引問題']],
      ['https://medium.com/@jeeyoungk/how-sharding-works-b4dec46b3f6', '分片是怎麼運作的', '從分片鍵的選擇、路由方式到重新平衡，介紹資料庫水平切分的基本原理。', ['分片的基本概念與適用時機', '演算法式分片與動態分片的差別', '如何選擇分片鍵以避免熱點', '跨分片查詢與重新分片的挑戰']],
      ['http://www.tom-e-white.com/2007/11/consistent-hashing.html', '一致性雜湊', 'Tom White 的經典解說：把節點與資料放在同一個雜湊環上，讓節點增減時只需搬移少量資料。', ['傳統取餘數雜湊在節點變動時的問題', '雜湊環與順時針查找節點的原理', '虛擬節點如何讓資料分布更平均', '一致性雜湊在分散式快取中的應用']],
      ['https://medium.com/@dgryski/consistent-hashing-algorithmic-tradeoffs-ef6b8e2fcae8', '一致性雜湊的演算法取捨', '比較環狀雜湊、跳躍一致性雜湊、會合雜湊、Maglev 等演算法在記憶體、速度與分布均勻度上的差異。', ['環狀雜湊與虛擬節點的記憶體成本', '跳躍一致性雜湊的速度與限制', '會合雜湊（最高隨機權重）的做法', 'Maglev 雜湊與有界負載一致性雜湊']],
      ['https://medium.com/netflix-techblog/distributing-content-to-open-connect-3e3e391d4dc9', 'Netflix 的均勻一致性雜湊', 'Netflix 如何改良一致性雜湊，讓影片更均勻地分散到 Open Connect 內容傳遞網路的伺服器上。', ['內容傳遞網路中「哪台伺服器存哪部影片」的問題', '傳統一致性雜湊造成的負載不均', '均勻一致性雜湊如何改善分布', '伺服器增減時的內容搬移成本']],
      ['https://booking.ai/dont-be-tricked-by-the-hashing-trick-192a6aae3087', '別被雜湊技巧騙了', 'Booking.com 分析機器學習中常用的特徵雜湊技巧，說明雜湊碰撞對模型品質的影響。', ['特徵雜湊如何把大量類別壓縮成固定維度', '雜湊碰撞的機率如何隨特徵數量增加', '碰撞對模型效果造成的影響', '決定雜湊空間大小的方法']],
    ],
  },
  {
    id: 'k-principles',
    name: '設計原則與架構模式',
    question: '好的系統結構，有哪些共同特徵？',
    lessons: [
      ['https://12factor.net/', '十二要素應用程式', 'Heroku 整理的雲端應用程式十二條設計原則，是打造可擴展、易部署服務的共同語言。', ['組態放在環境變數，與程式碼分離', '行程保持無狀態，狀態交給後端服務', '建置、發布、執行三個階段嚴格分開', '開發、預備與正式環境盡量一致', '日誌視為事件串流輸出']],
      ['http://www.math-cs.gordon.edu/courses/cs211/lectures-2009/Cohesion,Coupling,MVC.pdf', '高內聚與低耦合', '大學課程講義，說明內聚與耦合的種類，以及 MVC 如何幫助降低模組之間的相依。', ['內聚力的種類：從偶然內聚到功能內聚', '耦合的種類：從內容耦合到資料耦合', '為什麼高內聚、低耦合讓系統容易修改與擴展', 'MVC 模式如何分離關注點']],
      ['https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html', '整潔架構', 'Robert C. Martin 提出的同心圓架構：核心業務規則不依賴框架、資料庫與使用者介面。', ['相依規則：外層可以依賴內層，內層不知道外層', '實體、使用案例、介面轉接器與框架四層', '讓業務邏輯可以獨立測試', '跨越邊界時只傳遞簡單的資料結構']],
      ['https://www.infoq.com/presentations/effective-api-design', '如何設計好的 API，以及它為何重要', 'Joshua Bloch 的經典演講，談 API 的設計流程，以及命名、錯誤處理與相容性等原則。', ['API 一旦公開就很難更改', '先寫使用範例，再設計 API', '名稱要能自我說明並保持一致', '有疑慮時先不要加：API 越小越好', '讓 API 容易使用、難以誤用']],
      ['https://zapier.com/engineering/api-best-practices/', 'API 最佳實務：事件回呼、棄用與設計', 'Zapier 從串接上千個 API 的經驗，整理出事件回呼、版本棄用與介面設計的建議。', ['事件回呼的設計重點：重試、驗證與訂閱管理', '如何規劃與溝通 API 的棄用時程', '一致的錯誤格式與分頁設計', '從串接者的角度評估 API 好不好用']],
      ['https://medium.com/@SkyscannerEng/monoliths-and-microservices-8c65708c3dbf', '單體式架構與微服務', 'Skyscanner 分享從單體式架構走向微服務的理由、代價與過渡方式。', ['單體式架構在團隊擴大後的痛點', '微服務帶來的獨立部署與團隊自主', '拆分服務的額外成本：網路、監控與一致性', '逐步拆分，而不是一次重寫']],
      ['https://towardsdatascience.com/10-common-software-architectural-patterns-in-a-nutshell-a0b47a1e9013', '十種常見軟體架構模式速覽', '用簡短圖解介紹分層、主從、管線與過濾器、代理、點對點、事件匯流排、MVC 等十種架構模式。', ['分層模式與主從模式', '管線與過濾器模式', '代理模式與點對點模式', '事件匯流排模式與 MVC 模式', '黑板模式與直譯器模式']],
      ['https://lynnlangit.com/2017/03/14/beyond-relational/', '雲端巨量資料設計模式', 'Lynn Langit 整理雲端上超越關聯式資料庫的資料架構模式與選擇方式。', ['何時該跳脫關聯式資料庫', '雲端上的鍵值、文件、圖形與串流服務', '巨量資料處理的批次與即時模式', '依資料特性組合多種雲端資料服務']],
      ['https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/scale-out', '為水平擴展而設計', '微軟 Azure 架構指南的設計原則：讓應用程式可以透過增加執行個體來擴展。', ['避免執行個體黏著，讓請求可以送到任何一台', '找出並消除限制擴展的瓶頸', '依工作負載拆分，分別擴展', '自動擴展與優雅縮減的設計']],
      ['https://docs.microsoft.com/en-us/azure/architecture/guide/design-principles/design-for-evolution', '為演進而設計', '微軟 Azure 架構指南：讓服務可以獨立演進，持續交付新功能而不被既有設計綁死。', ['高內聚、低耦合的服務邊界', '用非同步訊息降低服務之間的耦合', '領域知識封裝在服務內，不要寫進閘道', '透過有版本的介面讓服務獨立演進']],
    ],
  },
];
