import type { UnitSource } from './types';

// 第三階：技能｜資料層（快取、資料庫、儲存、搜尋）
const group = '資料層';

export const skillData: UnitSource[] = [
  {
    id: 's-cache',
    group,
    name: '分散式快取',
    question: '快取到底在替哪一個成本買單？什麼時候它會反過來傷害你？',
    lessons: [
      ['https://www.wix.engineering/post/scaling-to-100m-to-cache-or-not-to-cache', 'Wix 擴展到一億使用者：要不要快取', 'Wix 說明快取帶來的複雜度，以及他們如何先把系統設計得夠快，只在真正需要時才加快取。', ['快取帶來的複雜度：失效、一致性與除錯', '先讓系統本身夠快，再考慮快取', '用預先產生的資料取代即時運算', '什麼情況下才真的需要快取']],
      ['https://medium.com/netflix-techblog/caching-for-a-global-netflix-7bcc457012f1', 'Netflix 的 EVCache：全球分散式記憶體快取', 'Netflix 以 Memcached 為基礎打造 EVCache，並跨區域複寫快取資料，支撐全球串流服務。', ['以 Memcached 為基礎的分散式快取', '跨區域複寫快取寫入', '快取叢集的容量與可用性設計', '快取在微服務架構中的角色']],
      ['https://medium.com/netflix-techblog/cache-warming-agility-for-a-stateful-service-2d3b1da82642', 'Netflix 的 EVCache 快取預熱', 'Netflix 說明在擴縮快取叢集或替換機器時，如何先把資料預熱到新節點，避免冷快取衝擊後端。', ['冷快取對後端資料庫的衝擊', '需要預熱的時機：擴容、部署與替換機器', '從現有副本複製資料到新節點', '預熱速度與線上流量的平衡']],
      ['https://blog.box.com/blog/introducing-memsniff-robust-memcache-traffic-analyzer/', 'Box 的 Memsniff：Memcache 流量分析工具', 'Box 開源的工具，能即時擷取並分析 Memcache 流量，找出熱門鍵與過大的值。', ['為什麼需要觀察快取流量', '以封包擷取分析 Memcache 請求', '找出熱門鍵與過大的值', '用分析結果改善快取的使用方式']],
      ['https://codeascraft.com/2017/11/30/how-etsy-caches/', 'Etsy 以一致性雜湊與快取抹散做快取', 'Etsy 說明如何用一致性雜湊分配 Memcached 節點，並用快取抹散分散熱門鍵的負載。', ['一致性雜湊降低節點變動時的快取失效', '熱門鍵造成單一節點過載的問題', '快取抹散：把熱門鍵複製成多份分散存放', '抹散程度與記憶體用量的取捨']],
      ['https://code.facebook.com/posts/220956754772273/an-analysis-of-facebook-photo-caching/', 'Facebook 照片快取分析', 'Facebook 分析照片從瀏覽器、邊緣快取、源站快取到後端儲存的整條快取階層，評估每一層的效果。', ['瀏覽器、邊緣與源站多層快取的分工', '各層快取命中率的量測', '不同淘汰演算法對命中率的影響', '照片熱度隨時間衰減的特性']],
      ['https://code.facebook.com/posts/964122680272229/web-performance-cache-efficiency-exercise/', 'Facebook 的瀏覽器快取效率實驗', 'Facebook 研究瀏覽器快取在真實使用者身上的效果，發現空快取的造訪比想像中常見。', ['量測真實使用者的瀏覽器快取命中率', '空快取造訪為什麼比預期多', '快取空間與資源被淘汰的問題', '據此調整資源打包與快取策略']],
      ['http://tech.trivago.com/2015/10/15/tcache/', 'Trivago 的 tCache：能感知資料特性的 Java 快取', 'Trivago 開發的 Java 快取函式庫，能依資料特性決定淘汰與更新方式。', ['行程內快取與分散式快取的差異', '依資料特性設計淘汰策略', '快取更新與一致性', '記憶體用量的控制']],
      ['https://quoraengineering.quora.com/Pycache-lightning-fast-in-process-caching', 'Quora 的 Pycache：行程內快取', 'Quora 在 Python 服務中加入行程內快取層，減少對遠端快取的呼叫，大幅降低延遲。', ['遠端快取呼叫的網路成本', '行程內快取的一致性問題', '失效通知的設計', '記憶體用量與命中率的平衡']],
      ['http://tech.trivago.com/2017/12/19/how-trivago-reduced-memcached-memory-usage-by-50/', 'Trivago 把 Memcached 記憶體用量降低一半', 'Trivago 分析 Memcached 的記憶體配置機制，透過調整資料格式與設定，把記憶體用量減半。', ['Memcached 以固定大小區塊配置記憶體的機制', '值的大小分布如何造成記憶體浪費', '壓縮與序列化格式的選擇', '調整設定後的效果驗證']],
      ['https://engineeringblog.yelp.com/2018/03/caching-internal-service-calls-at-yelp.html', 'Yelp 快取內部服務呼叫', 'Yelp 在服務之間的呼叫加入快取層，降低重複請求對後端服務的壓力。', ['服務之間重複呼叫的成本', '在代理層加入快取', '快取鍵與失效策略', '快取對延遲與負載的改善']],
      ['https://allegro.tech/2017/01/estimating-the-cache-efficiency-using-big-data.html', 'Allegro 用巨量資料估算快取效率', 'Allegro 以存取日誌模擬不同快取大小與策略，在導入前先估算命中率。', ['以歷史存取日誌模擬快取', '估算不同容量下的命中率', '比較不同的淘汰策略', '用資料決定要不要投資快取']],
      ['https://engineering.zalando.com/posts/2018/04/distributed-cache-akka-kubernetes.html', 'Zalando 以 Akka 與 Kubernetes 打造分散式快取', 'Zalando 用 Akka 叢集在 Kubernetes 上建立分散式快取，讓服務共享快取資料。', ['以 Akka 叢集分片資料', '在 Kubernetes 上的節點探索', '快取資料的一致性', '擴縮時的資料搬移']],
      ['https://clickhouse.com/blog/building-a-distributed-cache-for-s3', 'ClickHouse 為 S3 打造分散式快取', 'ClickHouse 說明如何為物件儲存建立分散式快取層，讓查詢不必每次都從 S3 讀取資料。', ['物件儲存的延遲與成本問題', '分散式快取層的架構', '以一致性雜湊分配快取資料', '快取對查詢效能的改善']],
      ['https://medium.com/netflix-techblog/evolution-of-application-data-caching-from-ram-to-ssd-a33d6fa7a690', 'Netflix 應用資料快取：從記憶體走向固態硬碟', 'Netflix 讓 EVCache 把部分資料放到固態硬碟，以更低的成本支撐更大的快取容量。', ['純記憶體快取的成本限制', '固態硬碟作為第二層快取', '延遲與成本的取捨', '冷熱資料的分層存放']],
      ['https://medium.com/@SkyscannerEng/the-tradeoffs-of-a-replicated-cache-b6680c722f58', 'Skyscanner 複寫式快取的取捨', 'Skyscanner 比較複寫式與分割式快取，說明為何某些場景選擇讓每個節點都保有完整副本。', ['複寫式快取與分割式快取的差異', '讀取延遲與記憶體用量的取捨', '資料更新時的同步成本', '適合複寫式快取的資料特性']],
      ['http://engblog.yext.com/post/geolocation-caching', 'Yext 以四元樹快取地理位置查詢', 'Yext 使用四元樹組織地理位置資料，讓「附近的地點」這類查詢也能有效快取。', ['地理位置查詢難以快取的原因', '四元樹如何切分地理空間', '以區塊為單位快取查詢結果', '資料密度不均時的處理']],
      ['https://medium.com/vimeo-engineering-blog/video-metadata-caching-at-vimeo-a54b25f0b304', 'Vimeo 的影片中繼資料快取', 'Vimeo 分享如何快取影片中繼資料，減少資料庫查詢並處理快取失效。', ['影片中繼資料讀多寫少的特性', '快取鍵設計與失效策略', '快取穿透與快取雪崩的防範', '快取命中率的監控']],
      ['https://developers.soundcloud.com/blog/gradle-remote-build-cache-misses-part-2', 'SoundCloud 解決遠端建置快取未命中', 'SoundCloud 追查 Gradle 遠端建置快取命中率偏低的原因，讓建置時間大幅縮短。', ['遠端建置快取的運作方式', '造成快取未命中的常見原因', '讓建置輸入保持可重現', '量測建置快取的效益']],
      ['https://blog.flipkart.tech/ratings-reviews-flipkart-part-2-574ab08e75cf', 'Flipkart 的評分與評論系統', 'Flipkart 說明評分與評論服務如何以快取與非同步處理，承受大量讀取與寫入。', ['評分彙總的預先計算', '讀取路徑上的快取設計', '寫入後的非同步更新', '資料一致性與延遲的取捨']],
      ['https://tech.ebayinc.com/engineering/prefetch-caching-of-ebay-items/', 'eBay 預先快取商品資料', 'eBay 預測使用者接下來可能點擊的商品，提前載入快取以縮短頁面回應時間。', ['預先快取與按需快取的差別', '預測使用者下一步行為', '預取帶來的額外負載', '命中率與資源成本的平衡']],
      ['https://www.wix.engineering/post/how-we-built-a-cross-region-caching-library', 'Wix 的跨區域快取函式庫', 'Wix 打造跨資料中心同步的快取函式庫，讓各區域的服務讀到一致的快取資料。', ['跨區域快取的一致性挑戰', '失效事件的跨區廣播', '區域故障時的快取行為', '函式庫化讓各服務共用機制']],
      ['https://medium.com/pinterest-engineering/improving-distributed-caching-performance-and-efficiency-at-pinterest-92484b5fe39b', 'Pinterest 提升分散式快取的效能與效率', 'Pinterest 分享如何調校 Memcached 機群的硬體、設定與代理層，提升效能並降低成本。', ['快取機群的硬體與執行個體選擇', '代理層的連線管理', '記憶體配置與淘汰調校', '以量測驅動的持續改善']],
      ['https://doordash.engineering/2023/10/19/how-doordash-standardized-and-improved-microservices-caching/', 'DoorDash 標準化並改善微服務快取', 'DoorDash 為各微服務提供統一的快取函式庫，解決各自實作造成的不一致與維運負擔。', ['各服務自行實作快取的問題', '分層快取：行程內與 Redis', '統一的觀測指標與開關', '安全地逐步導入快取']],
    ],
  },
  {
    id: 's-redis',
    group,
    name: 'Redis 實戰',
    question: 'Redis 很快，但放進正式環境後要注意什麼？',
    lessons: [
      ['http://highscalability.com/blog/2014/9/8/how-twitter-uses-redis-to-scale-105tb-ram-39mm-qps-10000-ins.html', 'Twitter 如何用 Redis 撐起巨量流量', 'Twitter 使用上萬個 Redis 執行個體支撐時間軸等服務，並自行擴充 Redis 的資料結構。', ['時間軸快取為什麼選擇 Redis', '自行擴充的資料結構', '大規模叢集的管理與代理層', '記憶體效率與碎片化問題']],
      ['https://slack.engineering/scaling-slacks-job-queue-687222e9d100', 'Slack 擴展以 Redis 為基礎的工作佇列', 'Slack 的非同步工作佇列原本建在 Redis 上，在流量暴增時出問題後，改為加入 Kafka 作為持久緩衝。', ['Redis 作為工作佇列的限制', '記憶體耗盡造成的事故', '加入 Kafka 作為持久化緩衝', '漸進式遷移而不停機']],
      ['https://githubengineering.com/moving-persistent-data-out-of-redis/', 'GitHub 把持久化資料搬出 Redis', 'GitHub 說明為什麼把原本存在 Redis 的持久資料搬到 MySQL，以及遷移的做法。', ['把 Redis 當資料庫用的風險', '哪些資料適合搬到關聯式資料庫', '雙寫與資料比對的遷移流程', '遷移後的可靠性與維運改善']],
      ['https://engineering.instagram.com/storing-hundreds-of-millions-of-simple-key-value-pairs-in-redis-1091ae80f74c', 'Instagram 在 Redis 存放數億組鍵值', 'Instagram 利用 Redis 雜湊結構的精簡編碼，把數億組鍵值的記憶體用量大幅壓低。', ['大量小鍵值的記憶體負擔', '以雜湊分桶合併鍵值', 'Redis 精簡編碼的觸發條件', '記憶體與存取效率的取捨']],
      ['http://tech.trivago.com/2017/01/25/learn-redis-the-hard-way-in-production/', 'Trivago：在正式環境學 Redis 的慘痛經驗', 'Trivago 分享在正式環境使用 Redis 踩過的坑，以及事後的改善。', ['單執行緒模型下慢指令的影響', '持久化設定對效能的影響', '記憶體上限與淘汰策略', '監控 Redis 的關鍵指標']],
      ['https://deliveroo.engineering/2017/01/19/optimising-membership-queries.html', 'Deliveroo 最佳化 Redis 儲存', 'Deliveroo 為了大量的成員查詢，改用更節省記憶體的資料結構，大幅降低 Redis 用量。', ['成員查詢的常見做法', '集合結構的記憶體成本', '改用更精簡的編碼或機率結構', '準確度與記憶體的取捨']],
      ['http://engineering.wattpad.com/post/23244724794/store-more-stuff-memory-optimization-in-redis', 'Wattpad 的 Redis 記憶體最佳化', 'Wattpad 說明如何調整資料結構與編碼，讓同樣的記憶體存下更多資料。', ['Redis 各種資料結構的記憶體特性', '精簡編碼的使用條件', '鍵名設計對記憶體的影響', '量測記憶體用量的方法']],
      ['https://blog.heroku.com/rolling-redis-fleet', 'Heroku 如何替整個 Redis 機群打修補', 'Heroku 說明如何在不中斷客戶服務的前提下，替大量託管 Redis 執行個體更新與修補。', ['託管服務大規模更新的挑戰', '以複本切換降低停機時間', '自動化更新流程', '更新期間的監控與回復']],
    ],
  },
  {
    id: 's-cdn',
    group,
    name: 'HTTP 快取與內容傳遞網路',
    question: '怎麼讓資料在離使用者最近的地方被送出？',
    lessons: [
      ['https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching', 'HTTP 快取完整指南', 'MDN 的 HTTP 快取文件，說明瀏覽器、代理與內容傳遞網路如何依標頭決定快取行為。', ['私有快取與共享快取的差別', 'Cache-Control 各項指令的意義', '新鮮度與重新驗證', '快取破壞與版本化網址']],
      ['https://www.zynga.com/blogs/engineering/zynga-geo-proxy-reducing-mobile-game-latency', 'Zynga 的地理代理：降低手機遊戲延遲', 'Zynga 在世界各地部署代理節點，讓玩家連到最近的入口，縮短手機遊戲的網路延遲。', ['手機網路延遲對遊戲體驗的影響', '就近部署代理節點', '代理與後端之間的長連線', '延遲改善的量測']],
      ['https://technology.condenast.com/story/the-why-and-how-of-google-amp-at-conde-nast', 'Condé Nast 導入 Google AMP 的原因與做法', 'Condé Nast 說明為什麼導入加速行動網頁，以及對頁面速度與流量的影響。', ['加速行動網頁的原理', '由搜尋引擎快取頁面的好處', '導入時的內容與廣告限制', '對載入速度與流量的影響']],
      ['https://deliveroo.engineering/2016/09/19/ab-testing-cdns.html', 'Deliveroo 用 A/B 測試比較內容傳遞網路', 'Deliveroo 以真實流量做 A/B 測試，比較不同內容傳遞網路供應商的效能。', ['為什麼要用真實流量比較供應商', '依使用者分流進行測試', '比較的指標：延遲、錯誤率、成本', '測試結果如何影響決策']],
      ['https://developers.soundcloud.com/blog/how-soundcloud-uses-haproxy-with-kubernetes-for-user-facing-traffic', 'SoundCloud 以 HAProxy 搭配 Kubernetes 處理使用者流量', 'SoundCloud 說明如何在 Kubernetes 前面使用 HAProxy 接收外部流量，並處理路由與重新載入。', ['叢集入口流量的處理方式', 'HAProxy 設定的動態產生', '後端變動時的平順重新載入', '入口層的監控']],
      ['https://dropbox.tech/infrastructure/meet-bandaid-the-dropbox-service-proxy', 'Dropbox 的 Bandaid 服務代理', 'Dropbox 自行打造的反向代理，負責請求佇列、負載平衡與服務之間的流量管理。', ['自建反向代理的動機', '請求排隊與後進先出處理', '動態負載平衡', '代理層的可觀測性']],
      ['https://slack.engineering/service-workers-at-slack-our-quest-for-faster-boot-times-and-offline-support-3492cf79c88', 'Slack 以 Service Worker 加快啟動並支援離線', 'Slack 利用瀏覽器的 Service Worker 快取應用程式資源，大幅縮短桌面版啟動時間。', ['Service Worker 在瀏覽器中的角色', '應用程式資源的預先快取', '版本更新與快取失效', '離線支援的限制']],
      ['https://labs.spotify.com/2020/02/24/how-spotify-aligned-cdn-services-for-a-lightning-fast-streaming-experience/', 'Spotify 整合內容傳遞網路服務', 'Spotify 說明如何統一多家內容傳遞網路的使用方式，讓音樂串流更快更穩。', ['多家內容傳遞網路並用的理由', '統一設定與監控', '依效能動態選擇供應商', '串流品質的量測']],
    ],
  },
  {
    id: 's-rdb',
    group,
    name: '關聯式資料庫',
    question: '一台關聯式資料庫可以撐多遠？撐不住的時候怎麼辦？',
    lessons: [
      ['https://www.mysql.com/products/cluster/scalability.html', 'MySQL Cluster 的擴展能力', 'MySQL 官方介紹 MySQL Cluster 如何透過自動分片與無共享架構做到水平擴展。', ['無共享架構的特性', '自動分片與資料分布', '同步複寫與高可用', '適合與不適合的工作負載']],
      ['https://www.uber.com/en-SG/blog/mysql-at-uber/', 'Uber 的 MySQL', 'Uber 介紹支撐公司業務的 MySQL 機群，以及自動化維運平台的設計。', ['大規模 MySQL 機群的管理', '控制平面與資料平面的分工', '自動化的主節點移轉', '升級與容量管理']],
      ['https://medium.com/@Pinterest_Engineering/learn-to-stop-using-shiny-new-things-and-love-mysql-3e1613c2ce14', 'Pinterest：別追新玩具，學著愛上 MySQL', 'Pinterest 說明為什麼選擇成熟穩定的 MySQL，而不是新潮的資料庫。', ['選擇資料庫時要考慮的成熟度', '團隊熟悉度與維運成本', '可預期的故障模式', '用分片把 MySQL 撐到大規模']],
      ['https://blog.twitch.tv/en/2016/10/11/how-twitch-uses-postgresql-c34aa9e56f58', 'Twitch 如何使用 PostgreSQL', 'Twitch 分享 PostgreSQL 在網站中的角色、架構與維運經驗。', ['PostgreSQL 叢集的架構', '讀取副本與連線池', '備份與復原', '效能調校的經驗']],
      ['https://medium.com/airbnb-engineering/tracking-the-money-scaling-financial-reporting-at-airbnb-6d742b80f040', 'Airbnb 擴展以 MySQL 為基礎的財務報表系統', 'Airbnb 說明財務報表系統如何隨業務成長重新設計，確保每一筆金流都能被正確追蹤。', ['財務資料的正確性要求', '以事件紀錄追蹤每一筆金流', '批次計算與資料分割', '對帳與稽核']],
      ['https://www.wix.engineering/post/scaling-to-100m-mysql-is-a-better-nosql', 'Wix：MySQL 是更好的 NoSQL', 'Wix 說明如何把 MySQL 當成鍵值儲存使用，兼顧效能與維運的簡單。', ['用 MySQL 存放 JSON 文件', '以主鍵查詢取代複雜聯結', '避免交易與外鍵的成本', '熟悉工具帶來的維運優勢']],
      ['https://engineering.fb.com/2023/05/16/data-infrastructure/mysql-raft-meta/', 'Meta 打造並部署 MySQL Raft', 'Meta 以 Raft 共識協定取代原本的半同步複寫，讓 MySQL 的主節點移轉更安全、更快速。', ['原本複寫與移轉方式的問題', 'Raft 共識協定的角色', '把共識整合進 MySQL 的挑戰', '大規模部署的過程']],
      ['https://medium.com/airbnb-engineering/unlocking-horizontal-scalability-in-our-web-serving-tier-d907449cdbcf', 'Airbnb 以 MaxScale 資料庫代理解鎖水平擴展', 'Airbnb 在應用程式與 MySQL 之間加入資料庫代理，解決連線數暴增限制網頁層擴展的問題。', ['應用程式擴展時資料庫連線數的瓶頸', '資料庫代理的連線多工', '代理層的高可用', '導入代理後的效能影響']],
      ['https://www.uber.com/en-NL/blog/postgres-to-mysql-migration/', 'Uber 為什麼從 PostgreSQL 換到 MySQL', 'Uber 說明 PostgreSQL 在寫入放大、複寫與升級上的問題，促使他們改用 MySQL。', ['PostgreSQL 更新資料時的寫入放大', '實體複寫帶來的問題', '版本升級的困難', 'MySQL 在這些面向的差異']],
      ['https://engineering.instagram.com/handling-growth-with-postgres-5-tips-from-instagram-d5d7e7ffdfcb', 'Instagram 應對成長的五個 PostgreSQL 技巧', 'Instagram 分享在快速成長時，讓 PostgreSQL 撐住的五個實用技巧。', ['部分索引', '函式索引', '以連線池降低連線成本', '批次寫入與非同步處理', '監控慢查詢']],
      ['http://tech.transferwise.com/scaling-our-analytics-database/', 'TransferWise 擴展分析用資料庫', 'TransferWise 說明分析資料庫在資料量成長後遇到的問題與擴展方式。', ['分析查詢與交易查詢的差異', '分析資料庫的效能瓶頸', '資料分割與彙總', '遷移到更適合的工具']],
      ['https://medium.com/adyen/updating-a-50-terabyte-postgresql-database-f64384b799e7', 'Adyen 更新 50TB 的 PostgreSQL 資料庫', 'Adyen 分享在支付業務不能停機的前提下，如何升級一個 50TB 的 PostgreSQL 資料庫。', ['大型資料庫升級的風險', '邏輯複寫與切換', '停機時間的最小化', '升級前的演練']],
      ['https://medium.com/paypal-engineering/scaling-database-access-for-100s-of-billions-of-queries-per-day-paypal-introducing-hera-e192adacda54', 'PayPal 的 Hera：每天數千億次查詢的資料庫存取層', 'PayPal 開源的資料庫代理，負責連線多工、分片路由與保護資料庫。', ['資料庫連線數的限制', '連線多工與請求排隊', '分片路由', '保護資料庫的限流與隔離']],
      ['https://engineeringblog.yelp.com/2020/11/minimizing-read-write-mysql-downtime.html', 'Yelp 縮短 MySQL 讀寫停機時間', 'Yelp 說明如何縮短 MySQL 主節點切換時的讀寫停機時間。', ['主節點切換的步驟與停機來源', '縮短偵測與切換時間', '應用程式端的重連機制', '自動化與演練']],
      ['https://engineering.fb.com/2021/07/22/data-infrastructure/mysql/', 'Facebook 把 MySQL 從 5.6 升級到 8.0', 'Facebook 分享把龐大的 MySQL 機群從 5.6 升級到 8.0 的多年歷程。', ['自訂修改造成的升級困難', '相容性測試與功能移植', '分階段升級與回復計畫', '升級後的效益']],
      ['https://quoraengineering.quora.com/Migration-from-HBase-to-MyRocks-at-Quora', 'Quora 從 HBase 遷移到 MyRocks', 'Quora 說明為什麼把部分資料從 HBase 搬到以 RocksDB 為儲存引擎的 MySQL，以及遷移過程。', ['HBase 的維運負擔', 'MyRocks 的寫入與壓縮優勢', '雙寫與資料驗證', '遷移後的效能與成本']],
    ],
  },
  {
    id: 's-replica-shard',
    group,
    name: '複寫與分片實戰',
    question: '讀不夠就複寫，寫不下就分片：真正做起來會遇到什麼？',
    lessons: [
      ['https://docs.microsoft.com/en-us/sql/relational-databases/replication/types-of-replication', '資料庫複寫的類型', 'SQL Server 文件，說明交易複寫、合併複寫與快照複寫的差異與適用情境。', ['交易複寫：近即時地傳遞變更', '合併複寫：多端修改後合併', '快照複寫：定期整份複製', '選擇複寫類型的考量']],
      ['https://medium.com/booking-com-infrastructure/evaluating-mysql-parallel-replication-part-4-annex-under-the-hood-eb456cf8b2fb', 'Booking.com 評估 MySQL 平行複寫', 'Booking.com 的系列文章，深入分析 MySQL 平行複寫如何縮短複本延遲。', ['單執行緒複寫造成的延遲', '平行複寫的運作原理', '影響平行度的因素', '實測結果與設定建議']],
      ['https://githubengineering.com/mitigating-replication-lag-and-reducing-read-load-with-freno/', 'GitHub 以 freno 緩解複寫延遲', 'GitHub 開源 freno，讓大量寫入的工作依複本延遲自動節流，避免讀取到過期資料。', ['大量寫入造成的複本延遲', '以複本延遲作為節流訊號', '讀取導向延遲低的複本', '集中式節流服務的設計']],
      ['https://shopify.engineering/read-consistency-database-replicas', 'Shopify 在資料庫副本上維持讀取一致性', 'Shopify 說明從副本讀取時可能看到舊資料的問題，以及確保讀取一致性的做法。', ['從副本讀取的一致性風險', '讀取自己寫入的保證', '以位置標記決定能否讀副本', '一致性與負載分散的平衡']],
      ['https://engineeringblog.yelp.com/2018/04/black-box-auditing.html', 'Yelp 以黑箱稽核驗證 MySQL 到 Redshift 的複寫', 'Yelp 建立稽核機制，從外部比對來源資料庫與資料倉儲，確認複寫資料完整正確。', ['資料管線複寫可能出錯的地方', '黑箱稽核：從兩端比對結果', '抽樣與校驗和', '發現差異後的處理']],
      ['https://medium.com/airbnb-engineering/how-we-partitioned-airbnb-s-main-database-in-two-weeks-55f7e006ff21', 'Airbnb 兩週內切分主資料庫', 'Airbnb 以垂直切分的方式，在兩週內把主資料庫拆成多個，緩解容量壓力。', ['垂直切分與水平分片的差別', '找出可以獨立出去的資料表', '以複寫完成切換', '切分後的應用程式調整']],
      ['https://eng.uber.com/herb-datacenter-replication/', 'Uber 的 Herb：Schemaless 的多資料中心複寫引擎', 'Uber 為自家 Schemaless 資料儲存打造跨資料中心的複寫引擎。', ['跨資料中心複寫的需求', '以變更日誌傳遞資料', '衝突與順序的處理', '複寫延遲的監控']],
      ['https://quabase.sei.cmu.edu/mediawiki/index.php/Shard_data_set_across_multiple_servers_(Range-based)', '依範圍分片：把資料集分散到多台伺服器', '卡內基美隆大學整理的分片設計模式：依鍵值範圍把資料分散到多台伺服器。', ['範圍分片的原理', '範圍分片對範圍查詢的好處', '熱點與資料不均的風險', '分割點的調整與搬移']],
      ['https://medium.com/@Pinterest_Engineering/sharding-pinterest-how-we-scaled-our-mysql-fleet-3f341e96ca6f', 'Pinterest 如何分片 MySQL 機群', 'Pinterest 詳細說明分片設計：以編號內嵌分片位置，讓資料可以在大量 MySQL 上擴展。', ['把分片編號內嵌在物件編號中', '邏輯分片與實體機器的對應', '避免跨分片查詢的資料設計', '新增容量時的分片搬移']],
      ['https://www.twilio.com/engineering/2014/06/26/how-we-replaced-our-data-pipeline-with-zero-downtime', 'Twilio 零停機替換資料管線', 'Twilio 分享在不停機的情況下，把 MySQL 資料管線換成分片架構的過程。', ['舊管線的瓶頸', '雙寫與逐步切換', '資料一致性的驗證', '零停機遷移的步驟']],
      ['https://medium.com/square-corner-blog/sharding-cash-10280fa3ef3b', 'Square 替 Cash App 分片 MySQL', 'Square 說明 Cash App 如何以 Vitess 把 MySQL 分片，撐住快速成長的交易量。', ['單一資料庫撐不住的時點', '以 Vitess 管理分片', '選擇分片鍵的考量', '線上重新分片的過程']],
      ['https://www.quora.com/q/quoraengineering/MySQL-sharding-at-Quora', 'Quora 的 MySQL 分片', 'Quora 說明從垂直切分走到水平分片的歷程，以及分片框架的設計。', ['何時從垂直切分走向水平分片', '分片框架的設計', '分片鍵與路由', '分片搬移與維運']],
      ['https://eng.uber.com/schemaless-rewrite/', 'Uber 在正式環境重寫 Schemaless 的分片層', 'Uber 把 Schemaless 資料儲存的分片層從 Python 重寫成 Go，並在不停機的情況下完成遷移。', ['重寫分片層的動機', '新舊實作並行比對', '以流量鏡像驗證正確性', '逐步切換的策略']],
      ['https://instagram-engineering.com/sharding-ids-at-instagram-1cf5a71e5a5c', 'Instagram 的分片與編號設計', 'Instagram 以 PostgreSQL 綱要做邏輯分片，並設計內含時間與分片資訊的 64 位元編號。', ['分散式唯一編號的需求', '編號組成：時間、分片、序號', '以資料庫預存程序產生編號', '邏輯分片與實體伺服器的對應']],
      ['https://www.notion.so/blog/sharding-postgres-at-notion', 'Notion 為 PostgreSQL 分片', 'Notion 在資料庫快撐不住時，將 PostgreSQL 分片成數百個邏輯分片。', ['單體資料庫的警訊', '以工作區作為分片鍵', '邏輯分片與實體主機的配置', '雙寫、回填與切換的遷移過程']],
      ['https://www.figma.com/blog/how-figmas-databases-team-lived-to-tell-the-scale/', 'Figma 為 PostgreSQL 水平分片', 'Figma 資料庫團隊分享從垂直切分到水平分片的歷程，以及自建分片代理層的設計。', ['垂直切分的極限', '水平分片的設計取捨', '分片代理層與查詢路由', '漸進式上線與風險控制']],
      ['https://blog.box.com/blog/solr-improving-performance-batch-indexing/', 'Box 提升 Solr 批次建立索引的效能', 'Box 說明如何調整 Solr 分片與建立索引的流程，加快大量文件的批次索引。', ['批次建立索引的瓶頸', '分片數與索引吞吐量', '提交頻率與合併設定', '批次與即時索引的分離']],
      ['https://medium.com/tinder-engineering/geosharded-recommendations-part-3-consistency-2d2cb2f0594b', 'Tinder 依地理分片的推薦系統', 'Tinder 依地理位置把使用者資料分片，並處理使用者移動時跨分片的一致性。', ['依地理位置分片的原因', '分片大小與人口密度的平衡', '使用者移動時的資料搬移', '跨分片的一致性處理']],
      ['https://engineering.fb.com/production-engineering/scaling-services-with-shard-manager/', 'Facebook 以 Shard Manager 擴展服務', 'Facebook 的通用分片管理平台，負責把應用程式的分片分配、搬移與容錯自動化。', ['有狀態服務的分片管理問題', '分片的分配與負載平衡', '故障時的自動移轉', '通用平台讓各服務共用']],
    ],
  },
  {
    id: 's-presto',
    group,
    name: '分散式 SQL 查詢引擎',
    question: '資料散在各處時，怎麼用一句 SQL 查完？',
    lessons: [
      ['https://research.fb.com/wp-content/uploads/2019/03/Presto-SQL-on-Everything.pdf?', 'Presto：可以查詢一切的 SQL 引擎', 'Facebook 的 Presto 論文，說明這個分散式 SQL 引擎如何透過連接器查詢各種資料來源。', ['連接器架構：查詢各種資料來源', '分散式查詢的規劃與排程', '記憶體內管線化執行', '多種工作負載下的設計取捨']],
      ['https://medium.com/@Pinterest_Engineering/presto-at-pinterest-a8bda7515e52', 'Pinterest 的 Presto', 'Pinterest 分享 Presto 叢集的部署、資源管理與維運經驗。', ['互動式查詢的需求', '叢集部署與路由', '查詢資源限制', '常見問題與調校']],
      ['https://eng.lyft.com/presto-infrastructure-at-lyft-b10adb9db01', 'Lyft 的 Presto 基礎設施', 'Lyft 說明 Presto 叢集的架構、閘道與自動擴展。', ['以閘道路由查詢到多個叢集', '依負載自動擴展', '查詢的監控與限制', '升級與維運']],
      ['https://engineering.grab.com/scaling-like-a-boss-with-presto', 'Grab 以 Presto 擴展資料分析', 'Grab 分享使用 Presto 支撐大量分析查詢的做法。', ['分析查詢量成長的挑戰', '叢集調校與資源管理', '查詢路由', '使用者體驗的改善']],
      ['https://eng.uber.com/presto/', 'Uber 以 Presto 與 Parquet 做資料分析', 'Uber 說明如何以 Presto 搭配欄式格式 Parquet，提供快速的互動式資料分析。', ['欄式格式對分析查詢的好處', 'Presto 與 Parquet 的整合', '讀取效能的最佳化', '大規模部署的經驗']],
      ['https://slack.engineering/data-wrangling-at-slack-f2e0ff633b69', 'Slack 的資料整理', 'Slack 介紹資料團隊如何以 Presto、Hive 等工具整理與分析資料。', ['資料倉儲的整體架構', '批次與互動式查詢的分工', '資料品質與綱要管理', '讓各團隊自助取得資料']],
      ['https://medium.com/netflix-techblog/using-presto-in-our-big-data-platform-on-aws-938035909fd4', 'Netflix 在 AWS 巨量資料平台上使用 Presto', 'Netflix 分享在 S3 上以 Presto 查詢巨量資料的架構與改進。', ['直接查詢 S3 上的資料', '對 Parquet 讀取的改進', '叢集部署與資源管理', '對開源專案的貢獻']],
      ['https://www.eventbrite.com/engineering/big-data-workloads-presto-auto-scaling/', 'Eventbrite 的 Presto 自動擴展', 'Eventbrite 依查詢負載自動擴縮 Presto 叢集，兼顧效能與成本。', ['分析負載的尖峰與離峰', '依佇列長度擴展工作節點', '縮減時的查詢保護', '成本節省的效果']],
      ['https://www.uber.com/en-MY/blog/speed-up-presto-with-alluxio-local-cache/', 'Uber 以 Alluxio 本地快取加速 Presto', 'Uber 在 Presto 工作節點加入 Alluxio 本地快取，減少重複讀取遠端資料。', ['重複讀取遠端資料的成本', '本地快取的運作方式', '快取命中率與一致性', '查詢延遲的改善']],
    ],
  },
  {
    id: 's-nosql',
    group,
    name: 'NoSQL：鍵值、文件與圖形',
    question: '放棄聯結與交易之後，換到了什麼？',
    lessons: [
      ['https://www.thoughtworks.com/insights/blog/nosql-databases-overview', 'NoSQL 資料庫總覽', 'ThoughtWorks 介紹 NoSQL 的起源與四大類型：鍵值、文件、欄族與圖形資料庫。', ['NoSQL 興起的背景', '鍵值、文件、欄族、圖形四種模型', '彙總導向的資料設計', '選擇 NoSQL 的時機']],
      ['http://www.cs.ucsb.edu/~agrawal/fall2009/dynamo.pdf', 'Dynamo：Amazon 的高可用鍵值儲存', 'Amazon 的經典論文，結合一致性雜湊、向量時鐘與八卦協定，打造永遠可寫入的鍵值儲存。', ['一致性雜湊與虛擬節點', '可調整的讀寫法定人數', '向量時鐘與衝突解決', '提示移交與反熵修復', '八卦協定與故障偵測']],
      ['https://medium.com/nikeengineering/becoming-a-nimble-giant-how-dynamo-db-serves-nike-at-scale-4cc375dbb18e', 'Nike 如何以 DynamoDB 支撐大規模服務', 'Nike 分享使用 DynamoDB 支撐限量商品搶購等高流量情境的經驗。', ['託管鍵值資料庫的好處', '分割鍵設計與熱點', '容量模式的選擇', '高流量活動的準備']],
      ['https://segment.com/blog/the-million-dollar-eng-problem/', 'Segment 的百萬美元 DynamoDB 問題', 'Segment 發現 DynamoDB 費用暴增，追查熱分割與存取模式後大幅降低成本。', ['從帳單發現的效能問題', '熱分割造成的容量浪費', '找出最貴的存取模式', '修正後的成本改善']],
      ['https://blog.mapbox.com/scaling-mapbox-infrastructure-with-dynamodb-streams-d53eabc5e972', 'Mapbox 以 DynamoDB Streams 擴展基礎設施', 'Mapbox 利用 DynamoDB 的變更串流觸發後續處理，打造事件驅動的資料流程。', ['變更串流的運作方式', '以變更事件觸發下游處理', '跨區域的資料同步', '事件處理的可靠性']],
      ['https://blog.twitter.com/engineering/en_us/a/2014/manhattan-our-real-time-multi-tenant-distributed-database-for-twitter-scale.html', 'Twitter 的 Manhattan：即時多租戶分散式資料庫', 'Twitter 自行打造的分散式鍵值資料庫，支援多租戶、可插拔儲存引擎與可調一致性。', ['多租戶資料庫的設計', '可插拔的儲存引擎', '最終一致與強一致的選擇', '自助式的維運']],
      ['https://yahooeng.tumblr.com/post/120730204806/sherpa-scales-new-heights', 'Yahoo 的 Sherpa：分散式 NoSQL 鍵值儲存', 'Yahoo 介紹支撐多項服務的 Sherpa，以及它如何跨資料中心擴展。', ['託管式鍵值儲存服務', '跨資料中心複寫', '一致性模型', '大規模多租戶營運']],
      ['https://yahooeng.tumblr.com/post/178262468576/introducing-halodb-a-fast-embedded-key-value', 'Yahoo 的 HaloDB：快速的嵌入式鍵值儲存引擎', 'Yahoo 開源以日誌結構為基礎的嵌入式鍵值儲存，為高吞吐寫入與低延遲讀取而設計。', ['日誌結構儲存的原理', '記憶體內索引與磁碟資料', '壓縮與空間回收', '與其他嵌入式引擎的比較']],
      ['http://engineering.indeedblog.com/blog/2018/02/indeed-mph/', 'Indeed 的 MPH：快速精簡的唯讀鍵值儲存', 'Indeed 以最小完美雜湊打造唯讀鍵值儲存，用極小的空間提供快速查詢。', ['唯讀資料的特殊需求', '最小完美雜湊的原理', '空間效率與查詢速度', '資料更新的方式']],
      ['https://engineering.linkedin.com/blog/2017/02/building-venice-with-apache-helix', 'LinkedIn 以 Apache Helix 打造 Venice', 'LinkedIn 的衍生資料鍵值儲存 Venice，利用 Helix 管理分割與叢集狀態。', ['衍生資料儲存的需求', '以 Helix 管理分割配置', '批次與串流資料的寫入', '版本化的資料推送']],
      ['https://msdn.microsoft.com/en-us/magazine/hh547103.aspx', '文件資料庫到底是什麼', 'MSDN 雜誌專欄，以淺顯的方式介紹文件資料庫的概念與使用方式。', ['文件資料庫的資料模型', '以文件為單位的讀寫', '索引與查詢方式', '與關聯式資料庫的比較']],
      ['https://www.mongodb.com/blog/post/ebay-building-mission-critical-multi-data-center-applications-with-mongodb', 'eBay 以 MongoDB 打造多資料中心的關鍵應用', 'eBay 分享在多個資料中心部署 MongoDB 支撐關鍵業務的架構與經驗。', ['多資料中心的副本配置', '讀寫偏好的設定', '故障時的自動移轉', '大規模維運的做法']],
      ['https://www.mongodb.com/blog/post/mongodb-at-baidu-powering-100-apps-across-600-nodes-at-pb-scale', '百度的 MongoDB：兩千億筆文件的多租戶叢集', '百度以多租戶 MongoDB 叢集支撐上百個應用程式、存放大量文件。', ['多租戶叢集的資源隔離', '大量分片的管理', '自動化維運', '效能監控']],
      ['https://medium.com/build-addepar/migrating-mountains-of-mongo-data-63e530539952', 'Addepar 遷移大量 MongoDB 資料', 'Addepar 分享把大量資料搬出 MongoDB 的過程與技巧。', ['遷移的動機與目標', '線上遷移與資料比對', '遷移期間的服務不中斷', '遷移後的驗證']],
      ['https://medium.baqend.com/parse-is-gone-a-few-secrets-about-their-infrastructure-91b3ab2fcf71', 'Parse 的 AWS 與 MongoDB 基礎設施', '回顧被 Facebook 收購後關閉的 Parse，其後端服務如何以 MongoDB 支撐大量應用程式。', ['多租戶後端服務的挑戰', 'MongoDB 叢集的配置', '吵雜鄰居問題', 'Parse 關閉帶來的教訓']],
      ['https://engineering.linkedin.com/blog/2017/12/couchbase-ecosystem-at-linkedin', 'LinkedIn 的 Couchbase 生態系', 'LinkedIn 說明如何使用 Couchbase 作為快取與儲存，以及周邊的維運工具。', ['Couchbase 的使用情境', '叢集部署與管理', '監控與告警', '自動化工具']],
      ['https://medium.com/zendesk-engineering/resurrecting-amazon-simpledb-9404034ec506', 'Zendesk 復活 Amazon SimpleDB', 'Zendesk 分享重新使用 SimpleDB 的特殊案例與原因。', ['SimpleDB 的特性與限制', '選擇冷門服務的理由', '使用上的設計考量', '成本與維運的比較']],
      ['https://engineering.linkedin.com/espresso/introducing-espresso-linkedins-hot-new-distributed-document-store', 'LinkedIn 的 Espresso：分散式文件儲存', 'LinkedIn 自行打造的分散式文件資料庫，支援次要索引、交易與跨資料中心複寫。', ['文件模型與階層式鍵值', '次要索引', '以變更擷取驅動的複寫', '分割與叢集管理']],
      ['https://www.eecs.harvard.edu/margo/papers/systor13-bench/', '圖形資料庫效能比較', '哈佛大學的研究，比較多種圖形資料庫在不同查詢與資料規模下的效能。', ['圖形資料庫的應用情境', '基準測試的設計', '走訪與查詢效能的差異', '選擇圖形資料庫的考量']],
      ['https://blog.twitter.com/engineering/en_us/a/2010/introducing-flockdb.html', 'Twitter 的 FlockDB：分散式圖形資料庫', 'Twitter 為追蹤關係打造的圖形資料庫，專注於大量鄰接清單的快速讀寫。', ['社交關係圖的存取特性', '以鄰接清單儲存關係', '分片與複寫', '只做需要的查詢']],
      ['https://www.cs.cmu.edu/~pavlo/courses/fall2013/static/papers/11730-atc13-bronson.pdf', 'Facebook 的 TAO：社交圖的分散式資料儲存', 'Facebook 的 TAO 論文，說明如何以物件與關聯模型、跨區域快取支撐每秒數十億次的社交圖讀取。', ['物件與關聯的資料模型', '讀多寫少的社交圖', '以快取層取代直接查資料庫', '跨區域的主從架構與一致性']],
      ['https://tech.ebayinc.com/engineering/akutan-a-distributed-knowledge-graph-store/', 'eBay 的 Akutan：分散式知識圖譜儲存', 'eBay 開源的知識圖譜資料庫，以日誌為中心的架構支援查詢與一致性。', ['知識圖譜的資料模型', '以共用日誌為核心的架構', '查詢規劃與執行', '一致性與可擴展性']],
    ],
  },
  {
    id: 's-columnar',
    group,
    name: '欄式資料庫：Cassandra、HBase、Redshift',
    question: '寫入量巨大、查詢固定時，資料要怎麼存？',
    lessons: [
      ['https://aws.amazon.com/nosql/columnar/', '什麼是欄式資料庫', 'AWS 的入門說明，介紹欄式資料庫如何依欄儲存資料，適合大量分析查詢。', ['列式儲存與欄式儲存的差別', '欄式儲存對分析查詢的好處', '壓縮效率', '適合與不適合的工作負載']],
      ['http://www.cs.cornell.edu/projects/ladis2009/papers/lakshman-ladis2009.pdf', 'Cassandra：去中心化的結構化儲存系統', 'Facebook 發表的 Cassandra 論文，結合 Dynamo 的分散式設計與 Bigtable 的資料模型。', ['無主節點的去中心化架構', '一致性雜湊與副本放置', '欄族資料模型', '寫入路徑：提交日誌與記憶體表']],
      ['https://www.slideshare.net/DataStax/cassandra-at-instagram-2016', 'Instagram 的 Cassandra', 'Instagram 分享用 Cassandra 支撐動態消息與通知的經驗，以及效能改善。', ['Cassandra 在 Instagram 的使用情境', '延遲與垃圾回收問題', '跨資料中心部署', '對 Cassandra 的改進']],
      ['https://medium.com/walmartlabs/building-object-store-storing-images-in-cassandra-walmart-scale-a6b9c02af593', 'Walmart 在 Cassandra 中儲存圖片', 'Walmart 以 Cassandra 打造物件儲存，存放大量商品圖片。', ['以 Cassandra 存放二進位物件', '切塊儲存大型檔案', '跨資料中心複寫', '讀寫效能調校']],
      ['https://blog.discordapp.com/how-discord-stores-billions-of-messages-7fa6ec7ee4c7', 'Discord 如何儲存數十億則訊息', 'Discord 說明從 MongoDB 改用 Cassandra 儲存訊息的原因，以及資料模型的設計。', ['訊息資料的讀寫特性', '以頻道與時間區間設計分割鍵', '最終一致性下的問題', '墓碑與刪除造成的效能陷阱']],
      ['https://medium.com/walmartlabs/avoid-pitfalls-in-scaling-your-cassandra-cluster-lessons-and-remedies-a71ca01f8c04', 'Walmart 擴展 Cassandra 叢集的陷阱', 'Walmart 整理擴展 Cassandra 叢集時常見的問題與對應方法。', ['大分割與熱點', '壓實策略的選擇', '修復與一致性', '節點新增時的資料串流']],
      ['https://engineeringblog.yelp.com/2016/08/how-we-scaled-our-ad-analytics-with-cassandra.html', 'Yelp 以 Cassandra 擴展廣告分析', 'Yelp 把廣告分析資料搬到 Cassandra，以支撐大量寫入與快速查詢。', ['廣告分析的寫入量', '資料模型與查詢設計', '從舊系統遷移', '效能與成本的改善']],
      ['https://medium.com/dream11-tech-blog/leaderboard-dream11-4efc6f93c23e', 'Dream11 以 Spark 與 Cassandra 撐起上億讀寫', 'Dream11 的即時排行榜系統，如何在賽事高峰時處理上億次讀寫。', ['排行榜的即時計算需求', '以 Spark 串流更新分數', 'Cassandra 的資料模型', '高峰流量的容量規劃']],
      ['https://www.zomato.com/blog/how-we-moved-our-food-feed-from-redis-to-cassandra', 'Zomato 把美食動態從 Redis 搬到 Cassandra', 'Zomato 說明動態資料量成長後，為何從 Redis 改用 Cassandra，以及遷移過程。', ['記憶體儲存的成本限制', '動態資料的存取模式', 'Cassandra 的資料模型設計', '無停機遷移']],
      ['https://medium.com/netflix-techblog/benchmarking-cassandra-scalability-on-aws-over-a-million-writes-per-second-39f45f066c9e', 'Netflix 在 AWS 上測試 Cassandra 的擴展性', 'Netflix 實測 Cassandra 在 AWS 上的線性擴展能力，達到每秒超過一百萬次寫入。', ['基準測試的設計', '節點數與吞吐量的線性關係', '跨可用區的副本配置', '雲端上的成本估算']],
      ['https://quickbooks-engineering.intuit.com/service-decomposition-at-scale-70405ac2f637', 'Intuit QuickBooks 以 Cassandra 進行服務拆分', 'Intuit 說明在拆分單體服務時，如何以 Cassandra 支撐新服務的資料需求。', ['服務拆分的資料問題', '資料所有權的切分', '從關聯式資料庫遷移', '拆分後的一致性處理']],
      ['https://developers.soundcloud.com/blog/keeping-counts-in-sync', 'SoundCloud 以 Cassandra 保持計數同步', 'SoundCloud 說明如何在大量播放與按讚下，讓各種計數保持正確與同步。', ['分散式計數的困難', '計數器的一致性問題', '定期校正與重算', '讀寫效能的取捨']],
      ['https://medium.com/glassdoor-engineering/cassandra-driver-configuration-for-improved-performance-and-load-balancing-1b0106ce12bb', 'Glassdoor 調整 Cassandra 驅動程式設定', 'Glassdoor 分享如何調整 Cassandra 用戶端驅動程式，改善效能與負載平衡。', ['驅動程式的負載平衡策略', '連線池設定', '重試與推測執行', '設定對延遲的影響']],
      ['https://labs.spotify.com/2018/09/04/introducing-cstar-the-spotify-cassandra-orchestration-tool-now-open-source/', 'Spotify 的 cstar：Cassandra 編排工具', 'Spotify 開源的工具，能安全地在大量 Cassandra 節點上依拓撲執行維運指令。', ['大規模 Cassandra 維運的痛點', '依拓撲安排執行順序', '避免同時影響同一份資料的副本', '維運工作的自動化']],
      ['https://hbase.apache.org/', 'Apache HBase', 'HBase 官方網站，這是建構在 HDFS 上、仿照 Bigtable 設計的分散式欄族資料庫。', ['Bigtable 式的資料模型', '以 HDFS 作為底層儲存', '區域分割與區域伺服器', '強一致的單列操作']],
      ['https://engineering.salesforce.com/investing-in-big-data-apache-hbase-b9d98661a66b', 'Salesforce 投資 Apache HBase', 'Salesforce 說明為什麼選擇 HBase 處理巨量資料，以及對社群的貢獻。', ['選擇 HBase 的理由', '大規模叢集的維運', 'Phoenix 提供的 SQL 介面', '對開源社群的投入']],
      ['https://www.facebook.com/notes/facebook-engineering/the-underlying-technology-of-messages/454991608919/', 'Facebook 訊息服務背後的 HBase', 'Facebook 說明為什麼選擇 HBase 作為新訊息系統的儲存。', ['訊息系統的資料特性', '選擇 HBase 的考量', '一致性模型的需求', '大規模部署的挑戰']],
      ['https://blog.imgur.com/2015/09/15/tech-tuesday-imgur-notifications-from-mysql-to-hbase/', 'Imgur 把通知系統從 MySQL 搬到 HBase', 'Imgur 說明通知資料量成長後，為何改用 HBase 以及遷移做法。', ['通知資料的讀寫模式', 'MySQL 遇到的瓶頸', 'HBase 的列鍵設計', '遷移與切換']],
      ['https://medium.com/@Pinterest_Engineering/improving-hbase-backup-efficiency-at-pinterest-86159da4b954', 'Pinterest 提升 HBase 備份效率', 'Pinterest 改善 HBase 備份流程，縮短備份時間並降低儲存成本。', ['HBase 備份的方式', '快照與匯出', '去除重複資料', '備份成本的降低']],
      ['https://www.slideshare.net/HBaseCon/hbase-practice-at-xiaomi', '小米的 HBase 實踐', '小米在 HBase 研討會上分享大規模 HBase 叢集的使用與改進。', ['HBase 在小米的使用情境', '效能與穩定性改進', '跨機房複寫', '維運自動化']],
      ['https://www.allthingsdistributed.com/2018/11/amazon-redshift-performance-optimization.html', 'Amazon Redshift 的效能最佳化', 'Werner Vogels 說明 Amazon 如何持續改善 Redshift 資料倉儲的查詢效能。', ['欄式儲存與壓縮', '結果快取與查詢編譯', '工作負載管理', '機器學習輔助的自動調校']],
      ['https://engineering.giphy.com/scaling-redshift-without-scaling-costs/', 'GIPHY 擴展 Redshift 而不增加成本', 'GIPHY 分享如何調整 Redshift 的使用方式，在資料量成長時控制成本。', ['資料倉儲成本的來源', '排序鍵與分布鍵的選擇', '冷資料的外移', '查詢調校']],
      ['https://www.hudl.com/bits/the-low-hanging-fruit-of-redshift-performance', 'Hudl：Redshift 效能的容易收穫', 'Hudl 整理幾個簡單卻有效的 Redshift 效能改善方法。', ['分布鍵與排序鍵', '清理與重新排序', '壓縮編碼', '查詢寫法的調整']],
      ['https://drivy.engineering/redshift_tips_ticks_part_1/', 'Drivy 的 Redshift 技巧', 'Drivy 分享使用 Redshift 時累積的實用技巧。', ['資料載入的最佳做法', '表格設計', '查詢效能調校', '維運注意事項']],
    ],
  },
  {
    id: 's-tsdb',
    group,
    name: '時間序列資料庫',
    question: '指標與事件照時間湧入時，怎麼存才查得快？',
    lessons: [
      ['https://www.influxdata.com/time-series-database/', '什麼是時間序列資料庫', 'InfluxData 介紹時間序列資料的特性，以及專用資料庫為何適合這類資料。', ['時間序列資料的特性', '寫入密集與依時間查詢', '降採樣與資料保存期限', '常見的使用情境']],
      ['https://code.facebook.com/posts/952820474848503/beringei-a-high-performance-time-series-storage-engine/', 'Facebook 的 Beringei：高效能時間序列儲存引擎', 'Facebook 開源的記憶體內時間序列儲存，以特殊壓縮方式大幅降低監控資料的記憶體用量。', ['監控資料的讀寫特性', '時間戳與數值的差值壓縮', '記憶體內儲存與持久化', '快速重啟與資料恢復']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/metricsdb.html', 'Twitter 的 MetricsDB：指標用時間序列資料庫', 'Twitter 為監控指標打造新的時間序列資料庫，取代原本以 Manhattan 為基礎的方案。', ['舊系統的成本與效能問題', '依時間分割的資料配置', '壓縮與記憶體效率', '遷移到新系統']],
      ['https://medium.com/netflix-techblog/introducing-atlas-netflixs-primary-telemetry-platform-bd31f4d8ed9a', 'Netflix 的 Atlas：記憶體內多維時間序列資料庫', 'Netflix 的主要遙測平台，以記憶體內儲存支撐大量多維度指標的即時查詢。', ['多維度指標的需求', '記憶體內儲存近期資料', '查詢語言與圖表', '大規模部署']],
      ['https://labs.spotify.com/2015/11/17/monitoring-at-spotify-introducing-heroic/', 'Spotify 的 Heroic：時間序列資料庫', 'Spotify 開源的監控時間序列資料庫，以 Cassandra 與 Elasticsearch 為基礎。', ['舊監控系統的限制', '以 Cassandra 儲存資料點', '以 Elasticsearch 索引中繼資料', '彙總與查詢']],
      ['https://developers.soundcloud.com/blog/roshi-a-crdt-system-for-timestamped-events', 'SoundCloud 的 Roshi：以 CRDT 儲存時間序列事件', 'SoundCloud 以無衝突複製資料型別打造的分散式事件儲存，用於動態消息。', ['無衝突複製資料型別的概念', '以時間戳決定事件狀態', '在 Redis 上實作', '讀取修復與一致性']],
      ['https://medium.com/@Pinterest_Engineering/goku-building-a-scalable-and-high-performant-time-series-database-system-a8ff5758a181', 'Pinterest 的 Goku：可擴展的時間序列資料庫', 'Pinterest 自行打造的時間序列資料庫，取代 OpenTSDB 以提升效能並降低成本。', ['OpenTSDB 遇到的瓶頸', '記憶體內儲存近期資料', '倒排索引與查詢', '分散式查詢的彙總']],
      ['https://medium.com/netflix-techblog/scaling-time-series-data-storage-part-ii-d67939655586', 'Netflix 擴展時間序列資料儲存', 'Netflix 說明觀看紀錄這類時間序列資料在 Cassandra 上的擴展方式與演進。', ['觀看紀錄的資料特性', '依時間分層存放', '壓縮舊資料', '讀取延遲與成本的平衡']],
      ['https://netflixtechblog.com/introducing-netflix-timeseries-data-abstraction-layer-31552f6326f8', 'Netflix 的時間序列資料抽象層', 'Netflix 打造時間序列資料抽象層，讓各團隊不必直接處理底層儲存的細節。', ['為什麼需要資料抽象層', '統一的時間序列介面', '底層儲存的分割與保存期限', '大規模寫入與查詢']],
      ['https://druid.apache.org/', 'Apache Druid：即時分析資料庫', 'Druid 官方網站，這是為低延遲即時分析設計的欄式分散式資料庫。', ['即時資料攝取', '欄式儲存與點陣索引', '預先彙總', '分散式查詢']],
      ['https://medium.com/airbnb-engineering/druid-airbnb-data-platform-601c312f2a4c', 'Airbnb 資料平台中的 Druid', 'Airbnb 說明如何在資料平台中使用 Druid，提供即時的分析儀表板。', ['即時分析的需求', '批次與串流資料攝取', '查詢效能', '叢集維運']],
      ['https://medium.com/walmartlabs/event-stream-analytics-at-walmart-with-druid-dcf1a37ceda7', 'Walmart 以 Druid 做事件串流分析', 'Walmart 使用 Druid 分析大量事件串流，提供即時的業務洞察。', ['事件串流分析的需求', '與 Kafka 的整合', '資料保存與彙總', '擴展與效能']],
      ['https://tech.ebayinc.com/engineering/monitoring-at-ebay-with-druid/', 'eBay 以 Druid 做監控', 'eBay 使用 Druid 儲存與查詢監控資料，支撐即時的維運分析。', ['監控資料的量級', '以 Druid 儲存指標', '即時查詢與儀表板', '叢集的擴展']],
      ['https://netflixtechblog.com/how-netflix-uses-druid-for-real-time-insights-to-ensure-a-high-quality-experience-19e1e8568d06', 'Netflix 以 Druid 掌握即時播放品質', 'Netflix 使用 Druid 分析來自裝置的大量事件，即時掌握播放品質。', ['裝置事件的量級', '即時攝取與查詢', '資料彙總與保存', '以分析確保播放體驗']],
    ],
  },
  {
    id: 's-storage',
    group,
    name: '分散式儲存',
    question: '檔案與物件多到數十億時，要怎麼存、怎麼找？',
    lessons: [
      ['http://highscalability.com/blog/2011/11/1/finding-the-right-data-solution-for-your-application-in-the.html', '在資料儲存的叢林中找對方案', '整理各類資料儲存方案的特性，幫助依應用需求挑選合適的儲存。', ['依資料模型分類的儲存方案', '一致性與可用性的需求', '讀寫比例與存取模式', '選擇儲存方案的流程']],
      ['https://medium.com/@denisanikin/what-an-in-memory-database-is-and-how-it-persists-data-efficiently-f43868cff4c1', '記憶體內資料庫如何有效率地持久化資料', '說明記憶體內資料庫的原理，以及如何透過交易日誌與快照確保資料不遺失。', ['記憶體內資料庫的速度來源', '以交易日誌保證持久性', '快照與日誌的組合', '重啟後的資料恢復']],
      ['http://highscalability.com/blog/2012/8/14/memsql-architecture-the-fast-mvcc-inmem-lockfree-codegen-and.html', 'MemSQL 的架構', '介紹 MemSQL 如何結合多版本並行控制、記憶體內儲存、無鎖資料結構與程式碼產生來加速 SQL。', ['記憶體內儲存與多版本並行控制', '無鎖資料結構', '把查詢編譯成機器碼', '相容 MySQL 的介面']],
      ['https://quoraengineering.quora.com/Optimizing-Memcached-Efficiency', 'Quora 最佳化 Memcached 效率', 'Quora 分析 Memcached 的使用狀況，找出浪費並提升記憶體效率。', ['分析快取的使用狀況', '記憶體配置造成的浪費', '鍵值大小的最佳化', '效率提升的量測']],
      ['https://blogs.cisco.com/datacenter/memsql', '在 Cisco UCS 上以 MemSQL 建立即時資料倉儲', 'Cisco 說明在自家伺服器上以 MemSQL 建立即時資料倉儲的測試與成果。', ['即時資料倉儲的需求', '硬體與記憶體內資料庫的搭配', '即時攝取與查詢', '效能測試結果']],
      ['http://eng.tapjoy.com/blog-list/moving-to-memsql', 'Tapjoy 改用 MemSQL', 'Tapjoy 說明為什麼把部分工作負載搬到 MemSQL，以及遷移的經驗。', ['原有資料庫的瓶頸', '記憶體內資料庫的優勢', '遷移過程', '成本與效能比較']],
      ['https://conferences.oreilly.com/strata/strata-ca/public/schedule/detail/68131', 'Disney 以 MemSQL 與 Kinesis 取得即時洞察', 'Disney 在研討會分享以串流與記憶體內資料庫打造即時分析的架構。', ['即時分析的業務需求', '以串流服務攝取事件', '記憶體內資料庫的查詢', '架構的擴展']],
      ['https://engineering.pandora.com/using-memsql-at-pandora-79a86cb09b57', 'Pandora 以 MemSQL 在儀表板中查詢數千億筆資料', 'Pandora 以 MemSQL 支撐需要查詢大量資料的儀表板，兼顧速度與成本。', ['儀表板查詢的延遲需求', '欄式儲存與記憶體內儲存的搭配', '資料載入流程', '查詢效能']],
      ['http://www.datacenterknowledge.com/archives/2013/10/04/object-storage-the-future-of-scale-out', '物件儲存：水平擴展的未來', '介紹物件儲存的概念，以及它為何適合大規模、非結構化的資料。', ['物件儲存與檔案、區塊儲存的差異', '扁平的命名空間', '以中繼資料描述物件', '水平擴展與耐久性']],
      ['https://eng.uber.com/scaling-hdfs/', 'Uber 擴展 Apache Hadoop 分散式檔案系統', 'Uber 分享 HDFS 叢集快速成長時遇到的瓶頸，以及擴展的做法。', ['名稱節點的記憶體與負載瓶頸', '聯邦式命名空間', '小檔案問題', '垃圾回收與效能調校']],
      ['https://databricks.com/blog/2017/05/31/top-5-reasons-for-choosing-s3-over-hdfs.html', 'Databricks：選擇 S3 而非 HDFS 的五個理由', 'Databricks 比較雲端物件儲存與 HDFS 在成本、彈性、耐久性與效能上的差異。', ['儲存與運算分離的好處', '成本比較', '耐久性與可用性', '效能差異與應對方式']],
      ['https://www.quantcast.com/blog/quantcast-file-system-on-amazon-s3/', 'Quantcast 在 Amazon S3 上的檔案系統', 'Quantcast 讓自家的分散式檔案系統可以使用 S3 作為後端。', ['自建檔案系統的特性', '以 S3 作為儲存後端', '效能與成本的考量', '雲端與自建機房的混合']],
      ['https://tech.trivago.com/2018/09/03/efficient-image-recovery-at-scale-using-amazon-s3-versioning/', 'Trivago 以 S3 版本控制大規模復原圖片', 'Trivago 利用 S3 的版本控制功能，在大量圖片被誤刪時快速復原。', ['誤刪資料的風險', 'S3 版本控制的原理', '大規模復原的做法', '版本保留的成本']],
      ['https://yahooeng.tumblr.com/post/116391291701/yahoo-cloud-object-store-object-storage-at', 'Yahoo 的雲端物件儲存', 'Yahoo 以 Ceph 打造雲端物件儲存，支撐照片、影片等大量資料。', ['大規模物件儲存的需求', '以 Ceph 為基礎的架構', '糾刪碼降低儲存成本', '效能與維運']],
      ['https://www.usenix.org/conference/srecon17americas/program/presentation/shenoy', 'LinkedIn 的 Ambry：分散式不可變物件儲存', 'LinkedIn 打造的物件儲存，專為照片、影片等不可變的媒體檔案設計。', ['不可變物件的特性', '分割與副本配置', '跨資料中心複寫', '大規模維運']],
      ['https://engineering.linkedin.com/blog/2018/02/dynamometer--scale-testing-hdfs-on-minimal-hardware-with-maximum', 'LinkedIn 的 Dynamometer：用少量硬體測試 HDFS 規模', 'LinkedIn 開源的工具，能以少量機器模擬大型 HDFS 叢集，測試名稱節點的效能。', ['大型叢集難以測試的問題', '模擬資料節點與真實工作負載', '重播正式環境的操作', '在升級前找出效能退步']],
      ['https://medium.com/airbnb-engineering/hammerspace-persistent-concurrent-off-heap-storage-3db39bb04472', 'Airbnb 的 Hammerspace：持久化的堆外儲存', 'Airbnb 為 Ruby 服務打造的堆外儲存，讓大量資料不佔用行程記憶體又能快速讀取。', ['大量資料載入記憶體的問題', '堆外儲存的原理', '多行程共享與並行讀取', '資料更新的方式']],
      ['https://medium.com/netflix-techblog/mezzfs-mounting-object-storage-in-netflixs-media-processing-platform-cda01c446ba', 'Netflix 的 MezzFS：把物件儲存掛載成檔案系統', 'Netflix 讓媒體處理程式能像讀取本機檔案一樣，直接讀取 S3 上的大型影片。', ['媒體處理需要讀取大型檔案', '把物件儲存掛載成檔案系統', '按需下載與快取', '效能調校']],
      ['https://dropbox.tech/infrastructure/inside-the-magic-pocket', 'Dropbox 的 Magic Pocket：自建多 EB 儲存系統', 'Dropbox 自建的區塊儲存系統，存放使用者檔案並提供極高的耐久性。', ['為什麼從雲端搬回自建儲存', '區塊與分區的資料配置', '糾刪碼與跨區域複寫', '持續驗證資料的完整性']],
    ],
  },
  {
    id: 's-search',
    group,
    name: '分散式搜尋',
    question: '資料量很大時，怎麼在幾十毫秒內找到結果？',
    lessons: [
      ['http://nwds.cs.washington.edu/files/nwds/pdf/Distributed-WR.pdf', '分散式搜尋與索引', '華盛頓大學的講義，介紹分散式資訊檢索的架構與索引切分方式。', ['倒排索引的原理', '依文件切分與依詞彙切分索引', '查詢的分散與結果合併', '索引更新與一致性']],
      ['https://instagram-engineering.com/search-architecture-eeb34a936d3a', 'Instagram 的搜尋架構', 'Instagram 說明搜尋服務的架構，包括索引建立、查詢處理與排序。', ['使用者、標籤與地點的搜尋需求', '索引的建立與更新', '查詢處理流程', '排序與個人化']],
      ['http://www.cs.otago.ac.nz/homepages/andrew/papers/2017-8.pdf', 'eBay 的搜尋架構', '學術論文分析 eBay 搜尋引擎的架構與效能設計。', ['電商搜尋的特殊需求', '索引切分與複製', '即時更新商品資料', '查詢延遲的控制']],
      ['https://medium.com/box-tech-blog/scaling-box-search-using-lumos-22d9e0cb4175', 'Box 以 Lumos 擴展搜尋', 'Box 說明如何以新的索引架構擴展檔案搜尋，支撐大量企業內容。', ['企業檔案搜尋的挑戰', '索引分片與路由', '權限過濾', '索引延遲的改善']],
      ['https://medium.com/coupang-tech/the-evolution-of-search-discovery-indexing-platform-fa43e41305f9', 'Coupang 搜尋探索索引平台的演進', 'Coupang 分享商品搜尋索引平台如何隨業務成長演進。', ['索引平台的演進階段', '全量與增量索引', '索引建置的效能', '資料品質']],
      ['https://medium.com/pinterest-engineering/building-a-universal-search-system-for-pinterest-e4cb03a898d4', 'Pinterest 的通用搜尋系統', 'Pinterest 打造通用搜尋系統，整合圖釘、使用者、看板等多種內容的搜尋。', ['多種內容類型的搜尋', '統一的查詢處理', '混合排序', '系統的擴展']],
      ['https://www.ebayinc.com/stories/blogs/tech/making-e-commerce-search-faster/', 'eBay 讓搜尋引擎效率提升 25% 以上', 'eBay 分享提升搜尋引擎效率的技術改進。', ['搜尋延遲的組成', '查詢處理的最佳化', '索引結構的改進', '效能量測']],
      ['https://medium.com/palantir/indexing-and-querying-telemetry-logs-with-lucene-234c5ce3e5f3', 'Palantir 以 Lucene 索引與查詢遙測日誌', 'Palantir 以 Lucene 為遙測日誌建立索引，讓大量日誌也能快速查詢。', ['日誌查詢的需求', 'Lucene 索引的建立', '依時間切分索引', '查詢效能與儲存成本']],
      ['https://www.tripadvisor.com/engineering/query-understanding-at-tripadvisor/', 'TripAdvisor 的查詢理解', 'TripAdvisor 說明如何理解使用者的搜尋意圖，例如地點、類別與屬性。', ['查詢理解的目標', '實體辨識', '意圖分類', '改善搜尋結果']],
      ['https://engineering.linkedin.com/blog/2018/03/search-federation-architecture-at-linkedin', 'LinkedIn 的搜尋聯邦架構', 'LinkedIn 把多個垂直搜尋整合成一個入口，並處理結果合併與排序。', ['聯邦搜尋的概念', '查詢分派到各垂直搜尋', '結果合併與排序', '延遲控制']],
      ['https://slack.engineering/search-at-slack-431f8c80619e', 'Slack 的搜尋', 'Slack 介紹訊息與檔案搜尋的架構，以及排序的改進。', ['訊息搜尋的特性', '索引與權限', '依相關性排序', '搜尋品質的量測']],
      ['https://careersatdoordash.com/blog/introducing-doordashs-in-house-search-engine/', 'DoorDash 的自建搜尋引擎', 'DoorDash 說明為什麼自建搜尋引擎，以及它的架構設計。', ['現成搜尋方案的限制', '索引與查詢服務分離', '即時更新', '擴展與維運']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2022/stability-and-scalability-for-search', 'Twitter 搜尋的穩定性與擴展性', 'Twitter 分享改善搜尋服務穩定性與擴展性的工作。', ['搜尋服務的瓶頸', '索引叢集的擴展', '穩定性改善', '監控與告警']],
      ['https://blog.twitter.com/engineering/en_us/a/2014/building-a-complete-tweet-index.html', 'Twitter 建立完整的推文索引', 'Twitter 說明如何為所有歷史推文建立搜尋索引。', ['全量歷史索引的規模', '分層儲存索引', '索引建置流程', '查詢延遲的控制']],
      ['https://medium.com/traveloka-engineering/high-quality-autocomplete-search-part-2-d5b15bb0dadf', 'Traveloka 的高品質自動完成搜尋', 'Traveloka 說明自動完成搜尋的設計，從資料準備到排序。', ['自動完成的延遲要求', '前綴索引', '排序訊號', '拼字錯誤容忍']],
      ['https://product.canva.com/building-a-data-driven-autocorrection-system/', 'Canva 的資料驅動自動校正系統', 'Canva 以使用者搜尋資料打造拼字自動校正，改善搜尋結果。', ['拼字錯誤對搜尋的影響', '從搜尋紀錄學習校正', '編輯距離與候選字', '效果評估']],
      ['https://blog.flipkart.tech/adapting-search-to-indian-phonetics-cdbe65259686', 'Flipkart 讓搜尋適應印度語音拼寫', 'Flipkart 處理使用者依發音拼寫商品名稱造成的搜尋問題。', ['依發音拼寫的查詢', '語音相似度演算法', '候選字產生', '搜尋召回率的改善']],
      ['https://dropbox.tech/machine-learning/architecture-of-nautilus-the-new-dropbox-search-engine', 'Dropbox 的 Nautilus 搜尋引擎', 'Dropbox 新一代搜尋引擎的架構，涵蓋索引、檢索與以機器學習排序。', ['檔案搜尋的需求', '索引與檢索的分離', '以機器學習排序', '權限與隱私']],
      ['https://engineering.linkedin.com/search/did-you-mean-galene', 'LinkedIn 的 Galene 搜尋架構', 'LinkedIn 以 Lucene 為基礎打造的搜尋架構，支撐人才等多種搜尋。', ['以 Lucene 為基礎的改造', '索引建置與部署', '即時更新', '排序與相關性']],
      ['https://medium.com/@Pinterest_Engineering/manas-a-high-performing-customized-search-system-cf189f6ca40f', 'Pinterest 的 Manas：高效能客製化搜尋系統', 'Pinterest 自建的搜尋系統，支撐文字與圖片等多種搜尋需求。', ['自建搜尋系統的理由', '索引結構', '查詢服務', '效能與擴展']],
      ['https://blog.flipkart.tech/sherlock-near-real-time-search-indexing-95519783859d', 'Flipkart 的 Sherlock：近即時搜尋索引', 'Flipkart 讓商品價格與庫存的變更能在很短時間內反映到搜尋結果。', ['商品資料頻繁變動', '增量索引', '近即時更新的架構', '一致性與延遲']],
      ['https://medium.com/airbnb-engineering/nebula-as-a-storage-platform-to-build-airbnbs-search-backends-ecc577b05f06', 'Airbnb 的 Nebula：打造搜尋後端的儲存平台', 'Airbnb 以 Nebula 作為搜尋相關服務的儲存平台，支援批次與即時資料。', ['搜尋後端的資料需求', '批次與即時資料合併', '版本化資料', '服務效能']],
    ],
  },
  {
    id: 's-elk',
    group,
    name: 'ELK 與 Elasticsearch',
    question: '把 Elasticsearch 用到大規模時，會在哪裡卡住？',
    lessons: [
      ['https://logz.io/blog/15-tech-companies-chose-elk-stack/', '十五家科技公司為何選擇 ELK', '整理多家公司使用 Elasticsearch、Logstash、Kibana 組合的理由與情境。', ['ELK 三個元件的分工', '日誌收集與分析的需求', '開源與社群', '常見的使用情境']],
      ['https://eng.uber.com/elk/', 'Uber 以 ELK 做即時預測', 'Uber 使用 ELK 處理即時資料，支援預測與分析。', ['即時資料的收集', 'Elasticsearch 的查詢', '視覺化分析', '擴展的挑戰']],
      ['https://webuild.envato.com/blog/building-a-scalable-elk-stack/', 'Envato 打造可擴展的 ELK', 'Envato 分享建置可擴展 ELK 的架構與經驗。', ['日誌量成長的挑戰', '以佇列緩衝日誌', '叢集擴展', '索引管理']],
      ['https://robinhood.engineering/taming-elk-4e1349f077c3', 'Robinhood 馴服 ELK', 'Robinhood 分享讓 ELK 穩定運作的調校與維運經驗。', ['叢集不穩定的原因', '索引與分片設定', '記憶體與垃圾回收', '監控與告警']],
      ['https://www.infoq.com/presentations/uber-elasticsearch-clusters?utm_source=presentations_about_Case_Study&utm_medium=link&utm_campaign=Case_Study', 'Uber 擴展 Elasticsearch 叢集', 'Uber 演講分享管理大量 Elasticsearch 叢集的經驗。', ['多叢集的管理', '容量規劃', '效能調校', '自動化維運']],
      ['https://www.ebayinc.com/stories/blogs/tech/elasticsearch-performance-tuning-practice-at-ebay/', 'eBay 的 Elasticsearch 效能調校實務', 'eBay 整理 Elasticsearch 在索引與查詢上的效能調校方法。', ['索引效能調校', '查詢效能調校', '分片數量的規劃', '硬體與設定']],
      ['https://medium.com/tinder-engineering/how-we-improved-our-performance-using-elasticsearch-plugins-part-2-b051da2ee85b', 'Tinder 以 Elasticsearch 外掛提升效能', 'Tinder 以自訂外掛把排序邏輯放進 Elasticsearch，減少資料傳輸並提升效能。', ['排序邏輯放在應用程式的成本', '自訂評分外掛', '效能改善的量測', '外掛的維護']],
      ['https://kickstarter.engineering/elasticsearch-at-kickstarter-db3c487887fc', 'Kickstarter 的 Elasticsearch', 'Kickstarter 分享以 Elasticsearch 支撐專案搜尋的做法。', ['搜尋需求', '索引設計', '資料同步', '搜尋相關性']],
      ['https://tech.trivago.com/2016/01/19/logstash_protobuf_codec/', 'Trivago 以 Logstash 解析 Protocol Buffers 日誌', 'Trivago 為 Logstash 開發 Protocol Buffers 編解碼器，處理二進位格式的日誌。', ['二進位日誌格式的好處', 'Logstash 編解碼器', '綱要管理', '處理效能']],
      ['https://engineeringblog.yelp.com/2018/06/fast-order-search.html', 'Yelp 以資料管線與 Elasticsearch 快速搜尋訂單', 'Yelp 以資料管線把訂單資料送進 Elasticsearch，提供快速的訂單搜尋。', ['訂單搜尋的需求', '以資料管線同步資料', '索引設計', '查詢效能']],
      ['https://engineeringblog.yelp.com/2017/06/moving-yelps-core-business-search-to-elasticsearch.html', 'Yelp 把核心商家搜尋搬到 Elasticsearch', 'Yelp 說明把核心商家搜尋從舊系統遷移到 Elasticsearch 的過程。', ['舊搜尋系統的限制', '遷移的規劃', '排序邏輯的移植', '上線與比對']],
      ['http://engineering.vinted.com/2017/06/05/sharding-out-elasticsearch/', 'Vinted 為 Elasticsearch 分片', 'Vinted 分享調整 Elasticsearch 分片以因應資料成長的經驗。', ['分片數量的影響', '重新分片的方式', '查詢效能', '叢集穩定性']],
      ['http://engineering.wattpad.com/post/146216619727/self-ranking-search-with-elasticsearch-at-wattpad', 'Wattpad 以 Elasticsearch 做自我排序搜尋', 'Wattpad 以使用者行為自動調整搜尋排序。', ['搜尋排序的訊號', '以點擊回饋調整排序', 'Elasticsearch 評分設定', '效果評估']],
      ['https://github.blog/2019-03-05-vulcanizer-a-library-for-operating-elasticsearch/', 'GitHub 的 Vulcanizer：維運 Elasticsearch 的函式庫', 'GitHub 開源的 Go 函式庫與工具，讓 Elasticsearch 叢集的日常維運更安全方便。', ['叢集維運的常見操作', '以函式庫封裝維運動作', '安全地移除節點', '自動化工具']],
    ],
  },
];
