import type { UnitSource } from './types';

// 第三階：技能｜效能調校
const group = '效能調校';

export const skillPerf: UnitSource[] = [
  {
    id: 's-perf-profile',
    group,
    name: '效能量測與剖析',
    question: '不要猜：怎麼用量測找出真正的熱點？',
    lessons: [
      ['https://stackify.com/application-performance-metrics/', '應用程式效能的關鍵指標', '整理應用程式效能監控該看的指標，例如回應時間、錯誤率、吞吐量與資源使用率。', ['使用者滿意度指標', '平均與百分位回應時間', '錯誤率與請求量', '處理器與記憶體使用率', '垃圾回收與執行緒指標']],
      ['https://medium.com/netflix-techblog/linux-performance-analysis-in-60-000-milliseconds-accc10403c55', 'Netflix 的六十秒 Linux 效能分析', 'Netflix 整理登入主機後前六十秒該執行的十個指令，快速判斷效能問題出在哪裡。', ['用 uptime 看負載趨勢', '用 vmstat 與 mpstat 看處理器', '用 iostat 看磁碟', '用 free 看記憶體', '用 sar 看網路']],
      ['https://slack.engineering/continuous-load-testing/', 'Slack 的持續負載測試', 'Slack 在正式環境持續進行負載測試，提早發現容量與效能問題。', ['為什麼要持續做負載測試', '模擬真實的使用者行為', '在正式環境安全地測試', '及早發現效能退步']],
      ['https://medium.com/@Pinterest_Engineering/driving-user-growth-with-performance-improvements-cfc50dafadd7', 'Pinterest 以效能改善驅動使用者成長', 'Pinterest 發現頁面變快後使用者與註冊數明顯成長，說明效能投資的商業價值。', ['效能與成長的關係', '以實驗量測效能改善的影響', '前端效能的改善手法', '效能指標的選擇']],
      ['https://www.zynga.com/blogs/engineering/live-games-have-evolving-performance', 'Zynga 線上遊戲的效能追蹤儀表板', 'Zynga 打造效能儀表板，持續追蹤線上遊戲在各種裝置上的效能變化。', ['遊戲效能指標的選擇', '持續收集與比較', '找出版本之間的效能退步', '用儀表板推動改善']],
      ['https://engineering.riotgames.com/news/profiling-optimisation', 'Riot Games 的 C++ 效能剖析', 'Riot Games 的系列文章，說明如何量測與分析 C++ 遊戲程式的效能並加以最佳化。', ['先量測、再最佳化', '取樣式與插樁式剖析', '快取未命中與記憶體配置', '最佳化結果的驗證']],
      ['https://medium.com/homeaway-tech-blog/profiling-react-server-side-rendering-to-free-the-node-js-event-loop-7f0fe455a901', 'HomeAway 剖析 React 伺服器端渲染', 'HomeAway 找出伺服器端渲染阻塞 Node.js 事件迴圈的原因並加以改善。', ['伺服器端渲染的處理器成本', '事件迴圈被阻塞的影響', '剖析工具的使用', '改善方式']],
      ['https://medium.com/@Pinterest_Engineering/api-profiling-at-pinterest-6fa9333b4961', 'Pinterest 的 API 效能剖析', 'Pinterest 持續剖析 API 服務，找出效能熱點並降低成本。', ['持續剖析的做法', '找出耗用處理器的程式碼', '以剖析結果排定最佳化優先順序', '節省的成本']],
      ['https://medium.com/mindgeek-engineering-blog/ad-delivery-network-performance-optimization-with-flame-graphs-bc550cf59cf7', 'MindGeek 以火焰圖最佳化廣告投放效能', 'MindGeek 以火焰圖找出廣告投放服務的效能熱點並加以改善。', ['火焰圖的判讀', '找出處理器熱點', '最佳化的步驟', '成效量測']],
      ['https://medium.com/walmartlabs/performance-monitoring-with-riemann-and-clojure-eafc07fcd375', 'Walmart 以 Riemann 與 Clojure 做效能監控', 'Walmart 使用 Riemann 串流處理監控事件，即時掌握系統效能。', ['以事件串流做監控', 'Riemann 的規則處理', '即時告警', '與其他工具的整合']],
      ['https://engineeringblog.yelp.com/2018/02/making-30x-performance-improvements-on-yelps-mysqlstreamer.html', 'Yelp 讓 MySQLStreamer 效能提升三十倍', 'Yelp 以效能剖析找出資料串流工具的瓶頸，把處理速度提升三十倍。', ['以效能剖析找出熱點', '序列化與解析的成本', '批次處理', '改善後的驗證']],
      ['https://codeascraft.com/2020/04/23/cloud-jewels-estimating-kwh-in-the-cloud/', 'Etsy 的 Cloud Jewels：估算雲端耗電量', 'Etsy 建立方法估算雲端資源的耗電量，把能源效率納入工程決策。', ['雲端耗電難以量測', '以資源用量估算耗電', '建立能源係數', '以量化結果推動節能']],
    ],
  },
  {
    id: 's-perf-system',
    group,
    name: '系統資源調校',
    question: '處理器、記憶體、磁碟、網路：資源用在刀口上了嗎？',
    lessons: [
      ['https://engineering.instagram.com/improving-performance-with-background-data-prefetching-b191acb39898', 'Instagram 以背景預取資料提升效能', 'Instagram 在使用者打開畫面前先在背景下載資料，改善弱網路環境下的體驗。', ['行動網路不穩定的影響', '預測使用者接下來要看的內容', '背景下載的時機與電量考量', '預取的成效量測']],
      ['https://engineering.linkedin.com/blog/2020/fixing-linux-filesystem-performance-regressions', 'LinkedIn 修正 Linux 檔案系統效能退步', 'LinkedIn 追查核心升級後的檔案系統效能退步，找出原因並修正。', ['核心升級帶來的效能風險', '以基準測試比較版本差異', '追查檔案系統的行為變化', '修正並回報社群']],
      ['https://www.ebayinc.com/stories/blogs/tech/how-ebays-shopping-cart-used-compression-techniques-to-solve-network-io-bottlenecks/', 'eBay 購物車以壓縮解決網路輸入輸出瓶頸', 'eBay 發現購物車資料的網路傳輸成為瓶頸，以壓縮大幅降低流量與延遲。', ['網路輸入輸出瓶頸的發現', '壓縮演算法的選擇', '處理器成本與頻寬的取捨', '效能改善的量測']],
      ['https://dropbox.tech/infrastructure/optimizing-web-servers-for-high-throughput-and-low-latency', 'Dropbox 為高吞吐低延遲最佳化網頁伺服器', 'Dropbox 從硬體、核心、網路堆疊到 Nginx 設定，逐層調校網頁伺服器效能。', ['硬體與處理器設定', '核心與網路堆疊調校', '加密連線與 HTTP/2 的最佳化', 'Nginx 設定']],
      ['https://engineering.mixpanel.com/2018/07/31/live-downsizing-google-cloud-pds-for-fun-and-profit/', 'Mixpanel 線上縮小雲端固態磁碟', 'Mixpanel 分享在不停機的情況下縮小雲端磁碟容量以節省成本的做法。', ['雲端磁碟只能擴大不能縮小的限制', '以資料搬移完成縮減', '不停機的切換', '節省的成本']],
      ['https://zapier.com/engineering/celery-python-jemalloc/', 'Zapier 以 jemalloc 讓記憶體用量降低四成', 'Zapier 發現記憶體碎片化讓 Python 與 Celery 的用量持續上升，改用 jemalloc 配置器後大幅改善。', ['記憶體碎片化的成因', '不同記憶體配置器的差異', '替換配置器的做法', '改善效果的量測']],
      ['https://slack.engineering/reducing-slacks-memory-footprint-4480fec7e8eb', 'Slack 降低桌面應用程式的記憶體用量', 'Slack 說明桌面應用程式記憶體用量過高的原因與改善方法。', ['多個工作區造成的記憶體負擔', '找出記憶體佔用的來源', '架構調整', '改善後的量測']],
      ['https://www.youtube.com/watch?v=f9xI2jR71Ms', 'Wix 的伺服器端渲染', 'Wix 演講分享以伺服器端渲染加快大量使用者網站的載入速度。', ['使用者網站的載入需求', '伺服器端渲染的架構', '快取與效能', '擴展的挑戰']],
      ['https://medium.com/netflix-techblog/optimizing-the-netflix-api-5c9ac715cf19', 'Netflix 最佳化 API', 'Netflix 說明如何重新設計 API，讓裝置以更少的請求取得需要的資料。', ['通用 API 對多種裝置的限制', '由裝置團隊客製端點', '在伺服器端合併多個呼叫', '並行處理降低延遲']],
      ['https://www.ebayinc.com/stories/blogs/tech/optimization-of-cal-report-hadoop-mapreduce-job/', 'eBay 最佳化報表的 MapReduce 工作', 'eBay 調整 Hadoop MapReduce 工作的設定與邏輯，大幅縮短報表產生時間。', ['MapReduce 工作的瓶頸', '資料傾斜的處理', '合併器與壓縮', '工作時間的縮短']],
      ['https://www.ebayinc.com/stories/blogs/tech/performance-tuning-on-quartz-scheduler/', 'eBay 調校 Quartz 排程器效能', 'eBay 分析 Quartz 排程器在大量工作下的效能問題並加以調校。', ['排程器的資料庫鎖競爭', '執行緒池設定', '叢集模式的調整', '調校後的效果']],
      ['https://medium.com/dailymotion-engineering/hardware-assisted-video-transcoding-at-dailymotion-66cd2db448ae', 'Dailymotion 以硬體輔助影片轉碼', 'Dailymotion 以硬體加速影片轉碼，提升速度並降低成本。', ['軟體轉碼的成本', '硬體轉碼的原理', '畫質與速度的取捨', '導入後的效益']],
      ['https://dropbox.tech/infrastructure/cross-shard-transactions-at-10-million-requests-per-second', 'Dropbox 每秒千萬次請求的跨分片交易', 'Dropbox 說明在高吞吐量的中繼資料系統中實作跨分片交易的做法。', ['跨分片交易的需求', '兩階段提交的實作', '效能最佳化', '正確性的驗證']],
      ['https://engineeringblog.yelp.com/2017/07/generating-web-pages-in-parallel-with-pagelets.html', 'Yelp 以頁面片段平行化伺服器端處理', 'Yelp 把頁面拆成可平行產生的片段，縮短伺服器端的回應時間。', ['頁面產生的循序瓶頸', '頁面片段的平行處理', '片段之間的相依', '效能改善']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/improving-key-expiration-in-redis.html', 'Twitter 改善 Redis 的鍵值過期機制', 'Twitter 發現 Redis 過期鍵清理不及造成記憶體浪費，並改良過期演算法。', ['Redis 的主動與被動過期', '過期鍵累積的問題', '改良後的清理策略', '對記憶體與延遲的影響']],
      ['https://medium.com/netflix-techblog/predictive-cpu-isolation-of-containers-at-netflix-91f014d856c7', 'Netflix 預測式的容器處理器隔離', 'Netflix 以預測模型安排容器在處理器上的配置，減少彼此干擾。', ['吵雜鄰居效應', '處理器快取與核心的配置', '以預測模型決定配置', '效能改善']],
      ['https://eng.uber.com/improving-hdfs-i-o-utilization-for-efficiency/', 'Uber 提升 HDFS 的輸入輸出使用率', 'Uber 分析 HDFS 叢集的輸入輸出使用情形，提升硬體使用效率。', ['輸入輸出使用不均的問題', '冷熱資料的分布', '調整資料放置', '效率改善']],
      ['https://engineering.indeedblog.com/blog/2019/12/unthrottled-fixing-cpu-limits-in-the-cloud/', 'Indeed 修正雲端環境的處理器限制', 'Indeed 發現容器處理器限額造成不必要的節流，追查核心錯誤並提出修正。', ['容器處理器限額的機制', '節流造成的延遲', '核心排程器的錯誤', '修正與成效']],
    ],
  },
  {
    id: 's-perf-gc',
    group,
    name: '垃圾回收與記憶體調校',
    question: '程式停頓的那幾百毫秒，是誰偷走的？',
    lessons: [
      ['https://confluence.atlassian.com/enterprise/garbage-collection-gc-tuning-guide-461504616.html', '垃圾回收調校指南', 'Atlassian 的 Java 垃圾回收調校指南，說明如何讀懂垃圾回收日誌並調整參數。', ['Java 堆積的分代結構', '常見的垃圾回收器', '垃圾回收日誌的解讀', '調整堆積大小與回收器參數']],
      ['https://engineering.linkedin.com/garbage-collection/garbage-collection-optimization-high-throughput-and-low-latency-java-applications', 'LinkedIn 為高吞吐低延遲的 Java 應用程式調校垃圾回收', 'LinkedIn 分享調整垃圾回收以同時達成高吞吐量與低延遲的經驗。', ['垃圾回收暫停對延遲的影響', '新生代大小的調整', '物件晉升的控制', '調校前後的比較']],
      ['https://medium.com/adobetech/engineering-high-throughput-low-latency-machine-learning-services-7d45edac0271', 'Adobe 機器學習服務的垃圾回收', 'Adobe 說明高吞吐、低延遲的機器學習服務在垃圾回收上的挑戰與調校方式。', ['模型服務的記憶體特性', '垃圾回收暫停對推論延遲的影響', '回收器的選擇', '記憶體配置的調整']],
      ['https://developers.soundcloud.com/blog/garbage-collection-in-redux-applications', 'SoundCloud 談 Redux 應用程式的垃圾回收', 'SoundCloud 分析前端 Redux 應用程式中的記憶體與垃圾回收問題。', ['前端應用程式的記憶體洩漏', '不可變資料與物件配置', '垃圾回收對畫面流暢度的影響', '改善方法']],
      ['https://blog.twitch.tv/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap-26c2462549a2', 'Twitch 的 Go 記憶體壓艙物技巧', 'Twitch 預先配置一大塊不使用的記憶體，降低 Go 垃圾回收的頻率與處理器成本。', ['Go 垃圾回收的觸發條件', '堆積太小導致頻繁回收', '記憶體壓艙物的原理', '延遲與處理器用量的改善']],
      ['https://www.linux.com/blog/can-nodejs-scale-ask-team-alibaba', '阿里巴巴分析 V8 垃圾回收日誌', '阿里巴巴分享如何分析 Node.js 的 V8 垃圾回收日誌，找出效能問題。', ['V8 的記憶體結構', '垃圾回收日誌的判讀', '找出記憶體問題', 'Node.js 的擴展經驗']],
      ['https://instagram-engineering.com/copy-on-write-friendly-python-garbage-collection-ad6ed5233ddf', 'Instagram 讓 Python 垃圾回收不破壞寫入時複製', 'Instagram 調整 Python 垃圾回收，避免多行程共用的記憶體被寫入時複製破壞，每個請求的記憶體成長減半。', ['寫入時複製與多行程伺服器', '垃圾回收如何觸發記憶體複製', '停用或凍結垃圾回收', '記憶體用量的改善']],
      ['https://githubengineering.com/removing-oobgc/', 'GitHub 移除頻外垃圾回收的效能影響', 'GitHub 評估移除 Ruby 頻外垃圾回收之後，對回應時間與處理器用量的影響。', ['頻外垃圾回收的原理', 'Ruby 垃圾回收的改進', '移除前後的效能比較', '決策的依據']],
      ['https://allegro.tech/2018/05/a-comedy-of-errors-debugging-java-memory-leaks.html', 'Allegro 除錯 Java 記憶體洩漏的一連串錯誤', 'Allegro 分享追查 Java 記憶體洩漏的過程與教訓。', ['記憶體洩漏的徵兆', '堆積傾印的分析', '找出根因', '避免類似問題']],
      ['https://www.youtube.com/watch?v=X4tmr3nhZRg', '阿里巴巴最佳化 JVM', '阿里巴巴演講分享在大規模 Java 應用中最佳化 JVM 的經驗。', ['大規模 Java 應用的挑戰', '自訂 JVM 的改進', '垃圾回收調校', '診斷工具']],
      ['https://eng.uber.com/jvm-tuning-garbage-collection/', 'Uber 調校大型服務的 JVM 記憶體', 'Uber 分享調校 JVM 記憶體與垃圾回收的技巧，改善大型服務的延遲。', ['垃圾回收暫停的分析', '堆積大小與回收器的選擇', '記憶體配置的最佳化', '調校的驗證']],
      ['https://medium.com/walmartglobaltech/solr-performance-tuning-beb7d0d0f8d9', 'Walmart 調校 Solr 效能', 'Walmart 分享 Solr 搜尋服務的效能調校，包括快取與垃圾回收。', ['Solr 快取的設定', '垃圾回收調校', '索引與查詢的最佳化', '效能量測']],
      ['https://blog.flipkart.tech/memory-tuning-a-high-throughput-microservice-ed57b3e60997', 'Flipkart 為高吞吐微服務調校記憶體', 'Flipkart 調整 JVM 記憶體設定，解決高吞吐服務的延遲問題。', ['高吞吐服務的記憶體壓力', '垃圾回收暫停分析', '堆積與回收器設定', '延遲改善']],
    ],
  },
  {
    id: 's-perf-web',
    group,
    name: '圖片、影片與頁面載入',
    question: '使用者感受到的「快」，是從哪裡來的？',
    lessons: [
      ['https://developers.google.com/web/fundamentals/performance/why-performance-matters/', '為什麼效能很重要', 'Google 的網頁基礎文章，說明頁面速度如何影響使用者留存、轉換率與體驗。', ['效能與使用者留存', '效能與轉換率', '效能與使用者體驗', '效能與流量成本']],
      ['https://code.facebook.com/posts/129055711052260/optimizing-360-photos-at-scale/', 'Facebook 大規模最佳化 360 度照片', 'Facebook 說明如何處理與傳送 360 度照片，兼顧畫質與載入速度。', ['360 度照片的格式與投影', '分塊與多解析度', '依視角載入', '畫質與頻寬的取捨']],
      ['https://codeascraft.com/2017/05/30/reducing-image-file-size-at-etsy/', 'Etsy 縮小照片檔案大小', 'Etsy 調整圖片壓縮設定，在不影響畫質的前提下大幅縮小檔案。', ['圖片大小對載入速度的影響', '壓縮品質的選擇', '以感知指標評估畫質', '節省的頻寬']],
      ['https://medium.com/@Pinterest_Engineering/improving-gif-performance-on-pinterest-8dad74bf92f1', 'Pinterest 改善動圖效能', 'Pinterest 把動圖轉成影片格式，大幅降低檔案大小並加快載入。', ['動圖格式的效率問題', '轉為影片格式', '播放體驗的一致性', '頻寬與速度的改善']],
      ['https://medium.com/@Pinterest_Engineering/optimizing-video-playback-performance-caf55ce310d1', 'Pinterest 最佳化影片播放效能', 'Pinterest 改善影片起播時間與播放流暢度的做法。', ['起播時間的組成', '預先載入與緩衝策略', '自適應串流', '效能指標']],
      ['https://medium.com/netflix-techblog/optimized-shot-based-encodes-now-streaming-4b9464204830', 'Netflix 以動態最佳化器改善低頻寬串流', 'Netflix 依鏡頭內容調整編碼參數，在低頻寬下仍提供更好的畫質。', ['依鏡頭切分影片', '每個鏡頭各自選擇編碼參數', '以感知畫質指標評估', '低頻寬下的畫質提升']],
      ['https://youtube-eng.googleblog.com/2018/04/making-high-quality-video-efficient.html', 'YouTube 讓高畫質影片更有效率', 'YouTube 說明以更好的編碼與自適應串流，在相同頻寬下提供更高畫質。', ['影片編碼的效率', '自適應位元率串流', '新編碼格式的導入', '使用者體驗']],
      ['https://medium.com/dailymotion/reducing-video-loading-time-fa9c997a2294', 'Dailymotion 縮短影片載入時間', 'Dailymotion 分析影片載入流程，逐一移除造成延遲的步驟。', ['影片載入的各個階段', '播放器載入的最佳化', '預先連線與預取', '量測與改善']],
      ['https://www.zillow.com/engineering/improving-homepage-performance/', 'Zillow 改善首頁效能', 'Zillow 分享改善首頁載入速度的具體手法。', ['找出首頁的效能瓶頸', '關鍵資源優先載入', '圖片與腳本的最佳化', '成效量測']],
      ['https://medium.com/expedia-engineering/go-fast-or-go-home-the-process-of-optimizing-for-client-performance-57bb497402e', 'Expedia 最佳化用戶端效能的流程', 'Expedia 說明建立用戶端效能最佳化流程的做法。', ['效能預算', '量測與監控', '最佳化手法', '團隊流程']],
      ['https://medium.com/bbc-design-engineering/bbc-world-service-web-performance-26b08f7abfcc', 'BBC 國際頻道的網頁效能', 'BBC 國際頻道為全球網路較慢的使用者改善網頁效能。', ['全球使用者的網路條件', '控制頁面重量', '漸進式載入', '成效量測']],
    ],
  },
  {
    id: 's-perf-brotli',
    group,
    name: '壓縮：Brotli',
    question: '同樣的內容，能不能用更少的位元組送到？',
    lessons: [
      ['https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html', '了解 Brotli 壓縮的潛力', 'Akamai 分析 Brotli 壓縮相較於 Gzip 在檔案大小上的改善幅度。', ['Brotli 與 Gzip 的差異', '靜態資源與動態內容的壓縮', '壓縮等級與處理器成本', '瀏覽器支援']],
      ['https://engineering.linkedin.com/blog/2017/05/boosting-site-speed-using-brotli-compression', 'LinkedIn 以 Brotli 壓縮提升網站速度', 'LinkedIn 導入 Brotli 壓縮靜態資源，縮小檔案並加快網站載入。', ['導入 Brotli 的過程', '預先壓縮靜態資源', '檔案大小的減少', '載入時間的改善']],
      ['https://medium.com/booking-com-development/bookings-journey-with-brotli-978b249d34f3', 'Booking.com 導入 Brotli 的歷程', 'Booking.com 分享導入 Brotli 壓縮的過程、挑戰與成效。', ['導入的動機', '與內容傳遞網路的整合', '壓縮等級的選擇', '成效量測']],
      ['https://tech.treebo.com/a-tale-of-brotli-compression-bcb071d9780a', 'Treebo 的 Brotli 壓縮故事', 'Treebo 以 Brotli 壓縮改善使用者體驗的做法與成效。', ['壓縮對行動使用者的影響', '在建置流程中預先壓縮', '伺服器設定', '成效量測']],
      ['https://dropbox.tech/infrastructure/deploying-brotli-for-static-content', 'Dropbox 為靜態內容部署 Brotli', 'Dropbox 說明為靜態內容部署 Brotli 的做法與遇到的問題。', ['預先壓縮與即時壓縮', '內容協商與快取', '部署的步驟', '節省的頻寬']],
      ['https://engineeringblog.yelp.com/2017/07/progressive-enhancement-with-brotli.html', 'Yelp 以 Brotli 做漸進式增強', 'Yelp 對支援的瀏覽器提供 Brotli 壓縮，其他瀏覽器仍使用 Gzip。', ['漸進式增強的概念', '依瀏覽器支援選擇壓縮', '快取的變化', '成效']],
      ['https://doordash.engineering/2019/01/02/speeding-up-redis-with-compression/', 'DoorDash 以壓縮加速 Redis', 'DoorDash 比較多種壓縮演算法，壓縮 Redis 中的資料以降低記憶體與網路負擔。', ['大型值對 Redis 的影響', '壓縮演算法的比較', '壓縮與解壓縮的處理器成本', '延遲與記憶體的改善']],
    ],
  },
  {
    id: 's-perf-lang',
    group,
    name: '程式語言與框架的選擇',
    question: '換一種語言，能解決的是效能問題，還是團隊問題？',
    lessons: [
      ['https://www.techempower.com/benchmarks/', 'TechEmpower 網頁框架效能基準測試', '比較上百種網頁框架在各種情境下的效能表現。', ['基準測試情境：序列化、資料庫查詢、樣板渲染', '框架之間的效能差異', '基準測試的限制', '如何解讀結果']],
      ['https://netflixtechblog.com/python-at-netflix-bba45dae649e', 'Netflix 的 Python', 'Netflix 各團隊分享 Python 在內容傳遞、資安、機器學習等領域的應用。', ['Python 在基礎設施中的角色', '自動化與維運工具', '資料分析與機器學習', '效能考量']],
      ['https://instagram-engineering.com/python-at-scale-strict-modules-c0bb9245c834', 'Instagram 大規模使用 Python：嚴格模組', 'Instagram 為大型 Python 程式碼庫設計嚴格模組，避免匯入時的副作用。', ['大型程式碼庫的匯入問題', '匯入時副作用的風險', '嚴格模組的規則', '對啟動時間與可靠性的影響']],
      ['https://engineering.issuu.com/2018/12/10/our-current-ocaml-best-practices-part-2', 'Issuu 的 OCaml 最佳實務', 'Issuu 分享在正式環境使用 OCaml 的最佳實務。', ['型別系統的好處', '程式碼組織', '建置與相依管理', '團隊的實務經驗']],
      ['https://slack.engineering/taking-php-seriously-cf7a60065329', 'Slack 認真看待 PHP', 'Slack 說明為什麼仍然選擇 PHP 與 Hack，以及它在網頁開發上的優勢。', ['每個請求獨立的執行模型', '開發迭代的速度', 'Hack 帶來的型別與並行', '對語言的刻板印象']],
      ['https://tech.trivago.com/2020/03/02/why-we-chose-go/', 'Trivago 為什麼選擇 Go', 'Trivago 說明選擇 Go 開發後端服務的理由。', ['效能與資源使用', '並行模型', '部署的簡單', '團隊的學習成本']],
      ['https://codeascraft.com/2021/11/08/etsys-journey-to-typescript/', 'Etsy 導入 TypeScript 的歷程', 'Etsy 說明把大型 JavaScript 程式碼庫逐步遷移到 TypeScript 的過程。', ['導入型別的動機', '漸進式遷移策略', '型別定義與工具', '對開發效率的影響']],
      ['https://www.etsy.com/sg-en/codeascraft/sealed-classes-opened-my-mind', 'Etsy 以 Kotlin 密封類別管理狀態', 'Etsy 分享用 Kotlin 密封類別讓畫面狀態更清楚、更不容易出錯。', ['狀態管理的常見錯誤', '密封類別的特性', '以型別確保每種狀態都被處理', '程式碼可讀性']],
      ['https://doordash.engineering/2022/03/22/how-to-leverage-functional-programming-in-kotlin-to-write-better-cleaner-code/', 'DoorDash 在 Kotlin 中運用函數式程式設計', 'DoorDash 分享用函數式程式設計寫出更好、更清楚的 Kotlin 程式碼。', ['函數式程式設計的概念', '不可變資料', '純函式與副作用', '錯誤處理']],
      ['https://medium.com/bumble-tech/bpf-and-go-modern-forms-of-introspection-in-linux-6b9802682223', 'Bumble 以 BPF 與 Go 觀察 Linux', 'Bumble 介紹以 BPF 搭配 Go 進行系統內部觀察的現代做法。', ['BPF 的原理', '以 Go 撰寫觀察工具', '追蹤核心與應用程式事件', '效能分析的應用']],
      ['https://medium.com/gitlab-magazine/why-we-use-ruby-on-rails-to-build-gitlab-601dce4a7a38', 'GitLab 為什麼使用 Ruby on Rails', 'GitLab 說明選擇 Ruby on Rails 的理由，以及在大型專案中的取捨。', ['開發速度的優勢', '龐大的生態系', '效能與擴展的挑戰', '以其他語言補強']],
      ['https://medium.com/figma-design/rust-in-production-at-figma-e10a0ec31929', 'Figma 在正式環境使用 Rust', 'Figma 說明把效能關鍵的服務改用 Rust 撰寫的經驗與心得。', ['改用 Rust 的動機', '記憶體安全與效能', '學習曲線與生態系', '實際效益']],
      ['https://engineering.wework.com/choosing-a-language-stack-cac3726928f6', 'WeWork 選擇程式語言堆疊', 'WeWork 以實驗方式比較多種程式語言，決定新服務的技術堆疊。', ['選擇語言的評估標準', '以實作實驗比較', '團隊與生態系的考量', '決策過程']],
      ['https://blog.discord.com/why-discord-is-switching-from-go-to-rust-a190bbca2b1f', 'Discord 為什麼從 Go 換成 Rust', 'Discord 發現 Go 的垃圾回收造成週期性的延遲尖峰，改用 Rust 後延遲穩定下來。', ['垃圾回收造成的週期性延遲尖峰', '快取服務的記憶體特性', '沒有垃圾回收的好處', '改寫後的效能比較']],
      ['https://medium.com/agoda-engineering/happy-asp-net-core-performance-optimization-4e21a383d299', 'Agoda 的 ASP.NET Core 效能最佳化', 'Agoda 分享 ASP.NET Core 服務的效能最佳化技巧。', ['找出效能瓶頸', '非同步程式設計', '減少記憶體配置', '成效量測']],
      ['https://eng.uber.com/data-race-patterns-in-go/', 'Uber 整理的 Go 資料競爭模式', 'Uber 分析大量 Go 程式碼中的資料競爭，整理出常見的錯誤模式。', ['資料競爭的偵測', '閉包捕捉迴圈變數', '切片與映射的並行存取', '預防的方法']],
      ['https://netflixtechblog.com/java-21-virtual-threads-dude-wheres-my-lock-3052540e231d', 'Netflix 的 Java 21 虛擬執行緒：我的鎖到哪去了', 'Netflix 導入虛擬執行緒後遇到死結，追查原因是同步區塊造成的執行緒釘住。', ['虛擬執行緒的原理', '同步區塊造成的釘住', '死結的追查過程', '使用虛擬執行緒的注意事項']],
    ],
  },
];
