import type { UnitSource } from './types';

// 第三階：技能｜巨量資料與機器學習
const group = '資料與機器學習';

export const skillIntel: UnitSource[] = [
  {
    id: 's-bd-platform',
    group,
    name: '資料平台全貌',
    question: '一家公司的資料，從產生到被使用，要經過哪些地方？',
    lessons: [
      ['https://insights.sei.cmu.edu/sei_blog/2017/05/reference-architectures-for-big-data-systems.html', '巨量資料系統的參考架構', '卡內基美隆大學軟體工程研究所整理巨量資料系統的參考架構，說明各個元件的角色。', ['參考架構的用途', '資料來源、收集、儲存、處理與使用各層', '批次與串流處理', '選擇技術時的考量']],
      ['https://eng.uber.com/uber-big-data-platform/', 'Uber 的巨量資料平台：百 PB 級、分鐘級延遲', 'Uber 回顧巨量資料平台的四個世代演進，以及如何把資料延遲縮短到分鐘級。', ['從資料倉儲到資料湖的演進', '小檔案與資料延遲問題', 'Hudi 的增量更新', '平台演進的經驗']],
      ['https://www.unibw.de/code/events-u/jt-2018-workshops/ws3_bigdata_vortrag_widmann.pdf', 'BMW 的資料平台', 'BMW 在研討會分享車輛與企業資料平台的架構。', ['車輛資料的收集', '資料平台的架構', '資料治理', '應用案例']],
      ['https://www.youtube.com/watch?v=CSDIThSwA7s', 'Netflix 的資料平台', 'Netflix 演講介紹資料平台的整體架構與工具。', ['資料平台的組成', '資料儲存與查詢引擎', '工作流程與排程', '自助式資料工具']],
      ['https://blog.flipkart.tech/overview-of-flipkart-data-platform-20c6d3e9a196', 'Flipkart 資料平台總覽', 'Flipkart 介紹支撐電商業務的資料平台架構。', ['資料攝取與處理', '資料湖與資料倉儲', '批次與串流', '資料服務']],
      ['https://medium.com/coupang-tech/evolving-the-coupang-data-platform-308e305a9c45', 'Coupang 資料平台的演進', 'Coupang 說明資料平台如何隨業務成長演進。', ['早期平台的限制', '遷移到雲端', '資料湖架構', '自助式分析']],
      ['https://doordash.engineering/2020/09/25/how-doordash-is-scaling-its-data-platform/', 'DoorDash 如何擴展資料平台', 'DoorDash 說明資料平台在業務快速成長時的擴展策略。', ['資料量的快速成長', '即時與批次管線', '資料品質', '平台團隊的組織']],
      ['http://engineering.khanacademy.org/posts/khanalytics.htm', '可汗學院的資料平台', '可汗學院介紹學習資料的收集與分析平台。', ['學習事件的收集', '資料倉儲', '分析與報表', '以資料改善教學']],
      ['https://medium.com/airbnb-engineering/data-infrastructure-at-airbnb-8adfb34f169c', 'Airbnb 的資料基礎設施', 'Airbnb 介紹資料基礎設施的全貌，涵蓋收集、儲存、處理與查詢。', ['事件與資料庫資料的收集', 'Hadoop 叢集的配置', '工作流程排程', '查詢與分析工具']],
      ['https://www.infoq.com/presentations/big-data-infrastructure-linkedin', 'LinkedIn 的巨量資料基礎設施', 'LinkedIn 演講分享巨量資料基礎設施的架構與演進。', ['資料的收集與傳遞', '離線與線上資料系統', '衍生資料的服務', '平台的演進']],
      ['https://blog.gojekengineering.com/data-infrastructure-at-go-jek-cd4dc8cbd929', 'GO-JEK 的資料基礎設施', 'GO-JEK 介紹支撐多項業務的資料基礎設施。', ['事件的收集', '串流處理', '資料倉儲', '資料的自助存取']],
      ['https://medium.com/@Pinterest_Engineering/behind-the-pins-building-analytics-f7b508cdacab', 'Pinterest 的資料分析架構', 'Pinterest 說明資料分析平台的架構與工具。', ['分析平台的組成', '批次處理與查詢', '指標與儀表板', '實驗分析']],
      ['https://engineering.atspotify.com/2022/03/why-we-switched-our-data-orchestration-service/', 'Spotify 為什麼更換資料編排服務', 'Spotify 說明從自建工具換成新的資料編排服務的原因與過程。', ['舊編排工具的限制', '選擇新工具的考量', '大規模遷移', '遷移後的效益']],
      ['https://engineering.zalando.com/posts/2017/10/zalando-smart-product-platform.html', 'Zalando 的智慧商品平台', 'Zalando 以資料與機器學習打造商品平台，自動化商品資訊處理。', ['商品資料的品質問題', '以機器學習補足資訊', '平台架構', '業務效益']],
      ['https://www.slideshare.net/wyukawa/strata2017-sg', 'LINE 的日誌分析平台', 'LINE 在研討會分享大規模日誌分析平台的架構。', ['日誌的收集與傳遞', 'Hadoop 與查詢引擎', '分析工具', '平台維運']],
      ['https://medium.com/myntra-engineering/universal-dashboarding-platform-udp-data-visualisation-platform-at-myntra-5f2522fcf72d', 'Myntra 的通用儀表板平台', 'Myntra 打造統一的資料視覺化平台，讓各團隊快速建立儀表板。', ['儀表板需求的多樣性', '統一的資料來源', '視覺化元件', '權限與效能']],
    ],
  },
  {
    id: 's-bd-batch',
    group,
    name: '批次處理與分析管線',
    question: '每天數十億筆事件，怎麼在天亮前算完？',
    lessons: [
      ['https://labs.spotify.com/2017/10/23/big-data-processing-at-spotify-the-road-to-scio-part-2/', 'Spotify 的巨量資料處理：走向 Scio', 'Spotify 說明巨量資料處理框架的演進，以及打造 Scio 的原因。', ['批次處理框架的演進', 'Scio：以 Scala 撰寫資料管線', '統一批次與串流', '開發者體驗']],
      ['https://cdn.oreillystatic.com/en/assets/1/event/160/Big%20data%20processing%20with%20Hadoop%20and%20Spark%2C%20the%20Uber%20way%20Presentation.pdf', 'Uber 以 Hadoop 與 Spark 處理巨量資料', 'Uber 在研討會分享以 Hadoop 與 Spark 處理巨量資料的做法。', ['資料處理的需求', 'Spark 的使用方式', '資源管理', '效能調校']],
      ['https://cdn.oreillystatic.com/en/assets/1/event/269/Lyft_s%20analytics%20pipeline_%20From%20Redshift%20to%20Apache%20Hive%20and%20Presto%20Presentation.pdf', 'Lyft 的分析管線：從 Redshift 到 Hive 與 Presto', 'Lyft 分享分析管線從 Redshift 遷移到 Hive 與 Presto 的過程。', ['Redshift 的限制', '儲存與運算分離', '遷移策略', '查詢效能']],
      ['https://tech.grammarly.com/blog/building-a-versatile-analytics-pipeline-on-top-of-apache-spark', 'Grammarly 以 Spark 打造多用途分析管線', 'Grammarly 說明以 Spark 建立分析管線，支援多種分析需求。', ['分析需求的多樣性', '以 Spark 建立管線', '資料模型', '查詢效能']],
      ['https://medium.com/teads-engineering/give-meaning-to-100-billion-analytics-events-a-day-d6ba09aa8f44', 'Teads 每天處理一千億筆分析事件', 'Teads 說明廣告分析管線如何處理每天上千億筆事件。', ['事件量的挑戰', '批次與串流的組合', '彙總與儲存', '成本控制']],
      ['https://cdn.oreillystatic.com/en/assets/1/event/269/Big%20data%20analytics%20and%20machine%20learning%20techniques%20to%20drive%20and%20grow%20business%20Presentation%201.pdf', 'LinkedIn 的巨量資料分析與機器學習技術', 'LinkedIn 在研討會分享以巨量資料分析與機器學習推動業務成長。', ['業務分析的需求', '分析與建模方法', '實驗與因果推論', '案例分享']],
      ['https://cdn.oreillystatic.com/en/assets/1/event/137/Building%20a%20self-serve%20real-time%20reporting%20platform%20at%20LinkedIn%20Presentation%201.pdf', 'LinkedIn 以 Hadoop 打造自助式報表平台', 'LinkedIn 在研討會分享自助式報表平台的架構。', ['自助式報表的需求', '資料的預先彙總', '查詢服務', '平台化的好處']],
      ['https://medium.com/walmartlabs/how-we-build-a-robust-analytics-platform-using-spark-kafka-and-cassandra-lambda-architecture-70c2d1bc8981', 'Walmart 以 Lambda 架構追蹤商品供貨狀況', 'Walmart 以 Spark、Kafka 與 Cassandra 組成 Lambda 架構，分析商品的供貨狀況。', ['Lambda 架構：批次層與速度層', '以 Kafka 收集事件', '以 Spark 處理資料', '以 Cassandra 提供查詢']],
      ['https://www.ebayinc.com/stories/blogs/tech/announcing-the-accelerator-processing-1-000-000-000-lines-per-second-on-a-single-computer/', 'eBay 的 Accelerator：單機每秒處理十億行資料', 'eBay 開源的資料處理框架，強調在單台電腦上充分利用平行處理與快取結果。', ['單機高效能處理的思路', '平行處理與資料分割', '結果快取與重用', '與分散式框架的比較']],
      ['https://medium.com/adobetech/spark-on-scala-adobe-analytics-reference-architecture-7457f5614b4c', 'Adobe 以 Scala 撰寫 Spark 的分析參考架構', 'Adobe 分享以 Scala 與 Spark 打造分析應用的參考架構。', ['專案結構', '測試策略', '效能調校', '部署方式']],
      ['https://medium.com/airbnb-engineering/scaling-a-mature-data-pipeline-managing-overhead-f34835cbc866', 'Airbnb 擴展成熟的資料管線：管理額外負擔', 'Airbnb 說明資料管線成熟後，如何降低重複計算與維運負擔。', ['管線成長帶來的額外負擔', '找出重複的計算', '管線的重構', '效率的提升']],
      ['https://medium.com/airbnb-engineering/on-spark-hive-and-small-files-an-in-depth-look-at-spark-partitioning-strategies-a9a364f908', 'Airbnb 深入探討 Spark 分割策略與小檔案', 'Airbnb 分析 Spark 寫入 Hive 時產生大量小檔案的原因，比較多種分割策略。', ['小檔案對儲存與查詢的影響', 'Spark 分割的原理', '各種重新分割策略的比較', '選擇策略的建議']],
      ['https://engineering.linkedin.com/blog/2021/the-exabyte-club--linkedin-s-journey-of-scaling-the-hadoop-distr', 'LinkedIn 擴展 Hadoop 分散式檔案系統到 EB 級', 'LinkedIn 分享 HDFS 叢集擴展到 EB 級的歷程與改進。', ['名稱節點的擴展', '效能最佳化', '叢集的穩定性', '維運經驗']],
      ['https://engineering.linkedin.com/blog/2021/scaling-linkedin-s-hadoop-yarn-cluster-beyond-10-000-nodes', 'LinkedIn 把 Hadoop YARN 叢集擴展到一萬個節點以上', 'LinkedIn 說明 YARN 資源管理器在超大叢集中的瓶頸與改進。', ['資源管理器的瓶頸', '排程效能的改善', '模擬大規模叢集測試', '擴展的成果']],
      ['https://www.uber.com/en-SG/blog/jupiter-batch-ingestion-platform/', 'Uber 的 Jupiter：以設定驅動的廣告批次攝取平台', 'Uber 打造以設定檔驅動的批次資料攝取平台，簡化廣告資料的匯入。', ['批次攝取的重複工作', '以設定取代客製程式', '資料驗證', '平台的擴展']],
    ],
  },
  {
    id: 's-bd-realtime',
    group,
    name: '即時分析與串流處理',
    question: '要在幾秒內看到結果時，資料管線要怎麼改？',
    lessons: [
      ['https://www.uber.com/en-SG/blog/real-time-analytics-for-mobile-app-crashes/', 'Uber 以 Apache Pinot 即時分析行動應用程式當機', 'Uber 以 Pinot 即時分析大量當機事件，讓團隊快速發現並定位問題。', ['當機事件的即時分析需求', 'Pinot 的即時攝取與查詢', '資料模型設計', '查詢延遲']],
      ['https://techblog.king.com/rbea-scalable-real-time-analytics-king/', 'King 的 RBEA：可擴展的即時分析平台', 'King 打造以 Flink 為基礎的即時分析平台，讓分析師能即時部署分析腳本。', ['即時分析的需求', '以 Flink 為核心', '動態部署分析邏輯', '平台的擴展']],
      ['https://eng.uber.com/aresdb/', 'Uber 的 AresDB：以 GPU 加速的即時分析引擎', 'Uber 開源以 GPU 加速查詢的即時分析資料庫。', ['即時分析的延遲需求', '以 GPU 平行處理查詢', '欄式儲存與記憶體管理', '適用情境']],
      ['https://eng.uber.com/athenax/', 'Uber 的 AthenaX：開源串流分析平台', 'Uber 讓使用者以 SQL 撰寫串流分析工作，並自動部署到 Flink。', ['以 SQL 撰寫串流工作', '編譯並部署到 Flink', '工作的管理與監控', '降低串流處理的門檻']],
      ['https://medium.com/netflix-techblog/delta-a-data-synchronization-and-enrichment-platform-e82c36a79aee', 'Netflix 的 Delta：資料同步與豐富化平台', 'Netflix 打造平台，把資料庫變更同步到搜尋索引等其他系統，並補充相關資料。', ['多資料系統同步的問題', '變更資料擷取', '資料豐富化', '最終一致性']],
      ['https://medium.com/netflix-techblog/keystone-real-time-stream-processing-platform-a3ee651812a', 'Netflix 的 Keystone：即時串流處理平台', 'Netflix 的資料管線與串流處理平台，每天處理上兆筆事件。', ['資料管線的架構', '自助式串流處理', '以 Flink 執行處理工作', '平台的可靠性']],
      ['https://medium.com/airbnb-engineering/capturing-data-evolution-in-a-service-oriented-architecture-72f7c643ee6f', 'Airbnb 的 SpinalTap：變更資料擷取系統', 'Airbnb 在服務導向架構中擷取資料庫變更，讓其他服務能即時得知資料變化。', ['服務之間的資料同步', '從資料庫日誌擷取變更', '順序與一致性保證', '系統的可靠性']],
      ['https://yahooeng.tumblr.com/post/180867271141/a-new-chapter-for-omid', 'Yahoo 的 Omid：交易處理平台', 'Yahoo 為 HBase 等儲存系統提供交易能力的平台，並說明新版的改進。', ['在 NoSQL 上提供交易', '快照隔離', '低延遲的交易提交', '新版的效能改進']],
      ['https://www.infoq.com/presentations/paypal-ml-fraud-prevention-2018', 'PayPal 即時詐騙防制的機器學習資料管線', 'PayPal 演講分享即時詐騙偵測背後的資料管線。', ['即時詐騙偵測的需求', '特徵的即時計算', '模型服務', '低延遲的資料管線']],
      ['https://code.fb.com/data-center-engineering/hardware-analytics-and-lifecycle-optimization-halo-at-facebook/', 'Facebook 的 HALO：硬體分析與生命週期最佳化', 'Facebook 收集並分析大量伺服器的硬體資料，預測故障並最佳化硬體生命週期。', ['硬體資料的收集', '故障的分析與預測', '維修流程的自動化', '生命週期的最佳化']],
    ],
  },
  {
    id: 's-bd-governance',
    group,
    name: '資料治理、探索與實驗',
    question: '資料多到沒人知道哪張表可以信時，怎麼辦？',
    lessons: [
      ['https://eng.uber.com/databook/', 'Uber 的 Databook：以中繼資料把巨量資料變成知識', 'Uber 打造資料目錄，讓員工能找到、理解並信任資料。', ['資料探索的困難', '中繼資料的收集', '資料目錄的功能', '資料的信任與品質']],
      ['https://eng.lyft.com/amundsen-lyfts-data-discovery-metadata-engine-62d27254fbb9', 'Lyft 的 Amundsen：資料探索與中繼資料引擎', 'Lyft 開源的資料探索工具，以使用頻率等訊號幫助使用者找到合適的資料。', ['找資料的時間成本', '以搜尋與排序幫助探索', '中繼資料的收集', '使用資訊作為排序訊號']],
      ['https://eng.uber.com/maze/', 'Uber 的 Maze：漏斗視覺化平台', 'Uber 打造的漏斗分析工具，視覺化使用者在各步驟的流失。', ['漏斗分析的需求', '使用者流程的視覺化', '大量事件的處理', '找出流失點']],
      ['https://medium.com/netflix-techblog/metacat-making-big-data-discoverable-and-meaningful-at-netflix-56fb36a53520', 'Netflix 的 Metacat：讓巨量資料可被發現、有意義', 'Netflix 打造統一的中繼資料服務，整合多種資料儲存的資料表資訊。', ['多種資料儲存的中繼資料', '統一的中繼資料介面', '資料表的探索', '與其他工具的整合']],
      ['https://medium.com/netflix-techblog/building-and-scaling-data-lineage-at-netflix-to-improve-data-infrastructure-reliability-and-1a52526a7977', 'Netflix 建立並擴展資料血緣', 'Netflix 追蹤資料從來源到報表的血緣關係，提升資料基礎設施的可靠性。', ['資料血緣的用途', '血緣資料的收集', '以圖形儲存血緣', '影響分析與除錯']],
      ['https://medium.com/pinterest-engineering/securely-scaling-big-data-access-controls-at-pinterest-bbc3406a1695', 'Pinterest 安全地擴展巨量資料存取控制', 'Pinterest 說明如何在大量資料與使用者下，管理細粒度的資料存取權限。', ['資料存取權限的挑戰', '細粒度的存取控制', '權限的申請與稽核', '與資料工具的整合']],
      ['https://engineering.linkedin.com/blog/2019/04/privacy-preserving-analytics-and-reporting-at-linkedin', 'LinkedIn 保護隱私的分析與報表', 'LinkedIn 以差分隱私等技術，在提供分析報表的同時保護會員隱私。', ['分析報表的隱私風險', '差分隱私的原理', '雜訊與準確度的取捨', '實際應用']],
      ['https://codeascraft.com/2019/07/31/an-introduction-to-structured-data-at-etsy/', 'Etsy 結構化資料入門', 'Etsy 說明如何把商品資訊結構化，改善搜尋與推薦。', ['非結構化商品資訊的問題', '分類與屬性的建立', '資料的收集與補齊', '對搜尋與推薦的幫助']],
      ['https://medium.com/@Pinterest_Engineering/building-a-scalable-data-management-system-for-computer-vision-tasks-a6dee8f1c580', 'Pinterest 為電腦視覺任務打造可擴展的資料管理系統', 'Pinterest 打造系統管理大量圖片標註資料，支援電腦視覺模型的訓練。', ['標註資料的管理需求', '資料集的版本管理', '標註流程', '訓練資料的品質']],
      ['https://engineering.atspotify.com/2020/11/02/spotifys-new-experimentation-platform-part-2/', 'Spotify 的新實驗平台', 'Spotify 說明新一代實驗平台的設計，涵蓋實驗設定、分析與協調。', ['實驗平台的需求', '實驗的設定與分派', '統計分析', '多個實驗之間的協調']],
      ['https://medium.com/airbnb-engineering/https-medium-com-jonathan-parks-scaling-erf-23fd17c91166', 'Airbnb 擴展實驗報告框架', 'Airbnb 說明實驗報告框架如何擴展到每天大量的實驗。', ['實驗數量的成長', '指標的計算管線', '報告產生的效能', '實驗文化']],
    ],
  },
  {
    id: 's-ml-platform',
    group,
    name: '機器學習平台與基礎設施',
    question: '模型從筆電走到正式環境，中間缺了什麼？',
    lessons: [
      ['https://www.csie.ntu.edu.tw/~cjlin/talks/bigdata-bilbao.pdf', '巨量資料的大規模機器學習', '臺灣大學林智仁教授的演講，說明大規模機器學習在資料、演算法與系統上的挑戰。', ['資料放不進單機時的挑戰', '分散式最佳化方法', '通訊成本與計算成本', '線性模型與核方法的取捨']],
      ['https://engineeringblog.yelp.com/2020/07/ML-platform-overview.html', 'Yelp 的機器學習平台', 'Yelp 介紹機器學習平台的架構，涵蓋特徵、訓練與部署。', ['機器學習平台的組成', '特徵的管理', '模型訓練與追蹤', '模型部署與服務']],
      ['https://codeascraft.com/2021/12/21/redesigning-etsys-machine-learning-platform/', 'Etsy 重新設計機器學習平台', 'Etsy 說明重新設計機器學習平台的原因與架構。', ['舊平台的問題', '採用託管服務', '訓練與服務的流程', '對資料科學家的改善']],
      ['https://engineering.zalando.com/posts/2022/04/zalando-machine-learning-platform.html', 'Zalando 的機器學習平台', 'Zalando 介紹機器學習平台，讓團隊能快速從實驗走到正式環境。', ['從實驗到正式環境的落差', '工作流程工具', '模型部署', '平台的推廣']],
      ['https://www.uber.com/en-SG/blog/scaling-ai-ml-infrastructure-at-uber/', 'Uber 擴展人工智慧與機器學習基礎設施', 'Uber 說明機器學習基礎設施如何擴展，支撐大量模型的訓練與服務。', ['模型數量與規模的成長', '訓練叢集與硬體', '模型服務的擴展', '成本與效率']],
      ['https://eng.lyft.com/introducing-flyte-cloud-native-machine-learning-and-data-processing-platform-fb2bb3046a59', 'Lyft 的 Flyte：雲端原生的機器學習與資料處理平台', 'Lyft 開源的工作流程平台，讓機器學習與資料處理工作可重現、可擴展。', ['可重現的工作流程', '強型別的任務介面', '在 Kubernetes 上執行', '版本化與快取']],
      ['https://eng.lyft.com/lyftlearn-ml-model-training-infrastructure-built-on-kubernetes-aef8218842bb', 'Lyft 的 LyftLearn：以 Kubernetes 打造的模型訓練基礎設施', 'Lyft 以 Kubernetes 打造模型訓練環境，提升資料科學家的開發速度。', ['訓練環境的需求', '以 Kubernetes 管理訓練資源', '互動式開發環境', '從訓練到部署']],
      ['https://eng.lyft.com/ml-feature-serving-infrastructure-at-lyft-d30bf2d3c32a', 'Lyft 的機器學習特徵服務基礎設施', 'Lyft 打造特徵服務，讓線上模型能低延遲地取得最新特徵。', ['特徵服務的需求', '批次與串流特徵', '線上與離線特徵的一致性', '低延遲的查詢']],
      ['https://eng.uber.com/horovod/', 'Uber 的 Horovod：開源分散式深度學習框架', 'Uber 開源的分散式訓練框架，以環狀全歸約讓多張 GPU 高效率地訓練模型。', ['分散式訓練的通訊瓶頸', '環狀全歸約演算法', '只需少量修改程式碼', '擴展效率']],
      ['https://eng.uber.com/manifold/', 'Uber 的 Manifold：與模型無關的機器學習視覺化除錯工具', 'Uber 開源的工具，以視覺化比較模型在不同資料區段上的表現，找出模型的弱點。', ['模型除錯的困難', '依資料區段比較表現', '與模型種類無關的分析', '改善模型的方向']],
      ['https://tech.ebayinc.com/engineering/pykrylov-accelerating-machine-learning-research-at-ebay/', 'eBay 的 PyKrylov：加速機器學習研究', 'eBay 打造的 Python 函式庫，讓研究人員輕鬆地在平台上執行分散式實驗。', ['研究實驗的門檻', '以 Python 描述工作流程', '分散式執行', '實驗的追蹤']],
      ['https://eng.lyft.com/lyfts-reinforcement-learning-platform-670f77ff46ec', 'Lyft 的強化學習平台', 'Lyft 打造強化學習平台，用於即時決策問題。', ['強化學習的應用情境', '線上學習與探索', '平台架構', '評估方式']],
      ['https://engineering.atspotify.com/2022/06/how-we-built-infrastructure-to-run-user-forecasts-at-spotify/', 'Spotify 打造使用者預測的基礎設施', 'Spotify 說明如何建立大規模執行使用者預測的基礎設施。', ['預測的業務需求', '大量預測的計算', '工作流程與排程', '結果的服務']],
      ['https://blog.twitter.com/engineering/en_us/topics/insights/2018/ml-workflows.html', 'Twitter 以工作流程讓機器學習上線', 'Twitter 說明以工作流程工具讓機器學習模型從訓練到上線自動化。', ['模型上線的手動流程', '以工作流程串起各步驟', '模型的重新訓練', '可重現性']],
      ['https://netflixtechblog.com/scaling-media-machine-learning-at-netflix-f19b400243', 'Netflix 擴展媒體機器學習', 'Netflix 打造基礎設施，讓團隊能對大量影片、音訊與圖片執行機器學習。', ['媒體資料的處理挑戰', '媒體特徵的計算與儲存', '大規模批次推論', '平台化']],
      ['http://engineering.taboola.com/deep-learning-from-prototype-to-production/', 'Taboola 的深度學習：從原型到正式環境', 'Taboola 分享把深度學習推薦模型從原型推到正式環境的經驗。', ['原型與正式環境的落差', '模型服務的效能', '線上實驗', '持續訓練']],
      ['http://engineering.indeedblog.com/blog/2016/04/building-a-large-scale-machine-learning-pipeline-for-job-recommendations/', 'Indeed 打造職缺推薦的大規模機器學習管線', 'Indeed 說明職缺推薦的機器學習管線，從資料準備到線上服務。', ['推薦系統的資料準備', '特徵工程', '模型訓練', '線上服務']],
      ['https://engineeringblog.yelp.com/2018/01/building-a-distributed-ml-pipeline-part1.html', 'Yelp 擴展梯度提升樹的點擊率預測', 'Yelp 打造分散式機器學習管線，訓練梯度提升樹模型預測廣告點擊率。', ['點擊率預測的需求', '分散式訓練梯度提升樹', '特徵管線', '模型評估']],
      ['https://www.infoq.com/presentations/doordash-real-time-predictions', 'DoorDash 的即時預測', 'DoorDash 演講分享即時預測系統的架構，例如預估送達時間。', ['即時預測的需求', '特徵的即時計算', '模型服務', '延遲與準確度']],
      ['https://yahooeng.tumblr.com/post/157196488076/open-sourcing-tensorflowonspark-distributed-deep', 'Yahoo 開源 TensorFlowOnSpark：在巨量資料叢集上分散式深度學習', 'Yahoo 讓 TensorFlow 能直接在 Spark 與 Hadoop 叢集上執行，免去搬移資料。', ['資料與訓練叢集分離的問題', '在 Spark 叢集上執行 TensorFlow', '分散式訓練的方式', '與既有資料管線整合']],
      ['https://yahooeng.tumblr.com/post/139916828451/caffeonspark-open-sourced-for-distributed-deep', 'Yahoo 開源 CaffeOnSpark：在巨量資料叢集上分散式深度學習', 'Yahoo 讓 Caffe 深度學習框架能在 Spark 與 Hadoop 叢集上分散式訓練。', ['在巨量資料叢集上做深度學習', '以 Spark 管理訓練工作', '節點之間的通訊', '與資料處理的整合']],
    ],
  },
  {
    id: 's-ml-rec',
    group,
    name: '推薦、排序與搜尋',
    question: '在上億個選項中，怎麼挑出這個人最想看的十個？',
    lessons: [
      ['https://eng.lyft.com/the-recommendation-system-at-lyft-67bc9dcc1793', 'Lyft 的推薦系統', 'Lyft 介紹推薦系統的架構與應用情境。', ['推薦在叫車服務中的應用', '候選產生與排序', '特徵與模型', '線上實驗']],
      ['https://www.etsy.com/sg-en/codeascraft/building-a-platform-for-serving-recommendations-at-etsy', 'Etsy 打造推薦服務平台', 'Etsy 說明推薦服務平台的設計，讓各種推薦模型能統一上線。', ['推薦服務的需求', '候選產生與排序的分層', '平台的抽象', '延遲與擴展']],
      ['https://medium.com/bbc-design-engineering/developing-personalised-recommender-systems-at-the-bbc-e26c5e0c4216', 'BBC 開發個人化推薦系統', 'BBC 分享打造個人化推薦時，在公共媒體責任與演算法之間的考量。', ['公共媒體的推薦原則', '推薦演算法的選擇', '多樣性與編輯價值', '評估方式']],
      ['https://www.tripadvisor.com/engineering/personalized-recommendations-for-experiences-using-deep-learning/', 'TripAdvisor 以深度學習推薦旅遊體驗', 'TripAdvisor 以深度學習為使用者推薦個人化的旅遊體驗。', ['旅遊推薦的特性', '深度學習模型', '使用者行為特徵', '效果評估']],
      ['https://labs.spotify.com/2016/08/07/commodity-music-ml-services/', 'Spotify 的音樂個人化', 'Spotify 分享以通用的機器學習服務支撐音樂個人化推薦。', ['音樂推薦的訊號', '協同過濾與內容特徵', '通用化的機器學習服務', '大規模計算']],
      ['https://quoraengineering.quora.com/A-Machine-Learning-Approach-to-Ranking-Answers-on-Quora', 'Quora 以機器學習排序回答', 'Quora 說明如何以機器學習判斷回答品質並排序。', ['回答品質的定義', '特徵設計', '模型訓練與評估', '排序的線上效果']],
      ['https://medium.com/booking-com-development/the-engineering-behind-booking-coms-ranking-platform-a-system-overview-2fb222003ca6', 'Booking.com 排序平台的工程設計', 'Booking.com 說明住宿排序平台的系統架構。', ['排序平台的組成', '模型服務', '特徵的取得', '實驗與上線']],
      ['https://codeascraft.com/2020/10/29/bringing-personalized-search-to-etsy/', 'Etsy 導入個人化搜尋', 'Etsy 把使用者偏好加入搜尋排序，讓搜尋結果更貼近個人喜好。', ['個人化搜尋的需求', '使用者表徵', '排序模型', '線上實驗']],
      ['https://engineering.zalando.com/posts/2018/02/search-deep-neural-network.html', 'Zalando 以深度學習做跨語言的端到端商品搜尋', 'Zalando 以深度神經網路理解多種語言的查詢，直接對應到商品。', ['多語言查詢的挑戰', '端到端的神經網路模型', '查詢與商品的表徵', '搜尋效果']],
      ['https://medium.com/pinterest-engineering/searchsage-learning-search-query-representations-at-pinterest-654f2bb887fc', 'Pinterest 的 SearchSage：學習搜尋查詢的表徵', 'Pinterest 學習搜尋查詢的向量表徵，改善搜尋與推薦。', ['查詢表徵的用途', '以使用者互動訓練', '與圖釘表徵對齊', '應用與效果']],
      ['https://medium.com/pinterest-engineering/pintext-a-multitask-text-embedding-system-in-pinterest-b80ece364555', 'Pinterest 的 PinText：多任務文字嵌入系統', 'Pinterest 以多任務學習訓練文字嵌入，支援多種下游應用。', ['文字嵌入的用途', '多任務學習', '訓練資料的來源', '在各系統中的應用']],
      ['https://tech.ebayinc.com/engineering/ebays-blazingly-fast-billion-scale-vector-similarity-engine/', 'eBay 十億級的向量相似度引擎', 'eBay 打造高速的向量相似度搜尋引擎，支援以圖找圖等應用。', ['向量相似度搜尋的需求', '近似最近鄰演算法', '十億級向量的擴展', '延遲與準確度']],
      ['https://code.flickr.net/2017/03/07/introducing-similarity-search-at-flickr/', 'Flickr 的相似圖片搜尋', 'Flickr 以深度學習特徵與近似最近鄰搜尋，找出視覺上相似的照片。', ['以深度學習擷取圖片特徵', '近似最近鄰搜尋', '大量照片的索引', '搜尋體驗']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/splitnet-architecture-for-ad-candidate-ranking.html', 'Twitter 以 SplitNet 架構排序廣告候選', 'Twitter 設計拆分式的神經網路架構，兼顧廣告排序的效果與效率。', ['廣告候選排序的挑戰', '使用者與廣告分開計算', '效率與準確度的取捨', '線上效果']],
      ['https://codeascraft.com/2021/03/23/how-we-built-a-context-specific-bidding-system-for-etsy-ads/', 'Etsy 打造依情境出價的廣告系統', 'Etsy 依不同情境自動調整廣告出價，提升廣告效益。', ['廣告出價的問題', '依情境預測轉換', '出價策略', '效益評估']],
      ['https://codeascraft.com/2018/07/12/modeling-user-journey-via-semantic-embeddings/', 'Etsy 以語意嵌入建模使用者旅程', 'Etsy 以嵌入向量表示使用者的瀏覽旅程，用於推薦與搜尋。', ['使用者旅程的建模', '以序列訓練嵌入', '嵌入的應用', '效果評估']],
      ['https://engineering.linkedin.com/blog/2018/05/concourse--generating-personalized-content-notifications-in-near', 'LinkedIn 的 Concourse：近即時產生個人化內容通知', 'LinkedIn 以串流處理即時判斷哪些內容值得通知哪些會員。', ['通知的時效性', '串流處理的架構', '個人化的判斷', '避免過度打擾']],
      ['https://engineering.indeedblog.com/blog/2019/09/jobs-filter/', 'Indeed 的職缺篩選器', 'Indeed 以機器學習篩選不合適的職缺，提升求職者看到的職缺品質。', ['職缺品質的問題', '分類模型', '規則與模型的搭配', '效果評估']],
      ['https://githubengineering.com/topics/', 'GitHub 的 Repo-Topix：主題擷取框架', 'GitHub 從儲存庫內容自動擷取主題標籤，幫助使用者探索專案。', ['主題擷取的需求', '從說明文件擷取關鍵字', '候選主題的排序', '人工回饋']],
      ['https://medium.engineering/mapping-mediums-tags-1b9a78d77cf0', 'Medium 的標籤地圖', 'Medium 分析標籤之間的關係，建立標籤地圖以改善內容探索。', ['標籤的關聯分析', '以共同出現建立關係', '標籤地圖的視覺化', '對推薦的幫助']],
      ['https://blog.box.com/blog/box-graph-how-we-built-spontaneous-social-network/', 'Box Graph：自發形成的社交網路', 'Box 從檔案協作行為建立員工之間的關係圖，用於推薦內容與協作者。', ['從協作行為推論關係', '關係圖的建立', '推薦的應用', '隱私考量']],
      ['http://engineering.flipboard.com/2017/02/storyclustering', 'Flipboard 以 LDA 將相似新聞分群', 'Flipboard 以主題模型把報導同一事件的新聞分群，避免重複推薦。', ['重複新聞的問題', '主題模型的原理', '分群的方法', '效果評估']],
    ],
  },
  {
    id: 's-ml-vision',
    group,
    name: '電腦視覺與內容理解',
    question: '機器要怎麼「看懂」圖片、影片與文字？',
    lessons: [
      ['https://medium.com/mercari-engineering/mercaris-image-classification-experiment-using-deep-learning-9b4e994a18ec', 'Mercari 以深度學習做商品圖片分類實驗', 'Mercari 以深度學習自動辨識商品圖片的類別。', ['圖片分類的需求', '模型選擇與訓練', '資料標註', '實驗結果']],
      ['https://allegro.tech/2016/12/deep-learning-for-frame-detection.html', 'Allegro 以深度學習偵測商品圖片的邊框', 'Allegro 以深度學習找出商品圖片中不符合規範的邊框。', ['圖片規範的問題', '偵測模型', '訓練資料', '上線效果']],
      ['https://medium.com/hulu-tech-blog/content-based-video-relevance-prediction-b2c448e14752', 'Hulu 以內容預測影片相關性', 'Hulu 以影片內容特徵預測影片之間的相關性，解決新影片冷啟動問題。', ['冷啟動問題', '影片內容特徵', '相關性模型', '推薦效果']],
      ['https://engineeringblog.yelp.com/2024/03/moderating-inappropriate-video-content-at-yelp.html', 'Yelp 審核不當影片內容', 'Yelp 以機器學習自動審核使用者上傳的影片。', ['影片審核的挑戰', '擷取影格與音訊特徵', '分類模型', '人工審核的搭配']],
      ['http://engineering.tripadvisor.com/improving-tripadvisor-photo-selection-deep-learning/', 'TripAdvisor 以深度學習改善照片挑選', 'TripAdvisor 以深度學習為旅館與景點挑選最具代表性的照片。', ['照片挑選的標準', '美感與內容評分', '模型訓練', '使用者效果']],
      ['https://technology.condenast.com/story/handbag-brand-and-color-detection', 'Condé Nast 辨識手提包的品牌與顏色', 'Condé Nast 以機器學習辨識時尚圖片中手提包的品牌與顏色。', ['時尚圖片的辨識需求', '物件偵測', '品牌與顏色分類', '應用情境']],
      ['https://technology.condenast.com/story/natural-language-processing-and-content-analysis-at-conde-nast-part-2-system-architecture', 'Condé Nast 的自然語言處理與內容分析', 'Condé Nast 說明內容分析系統的架構，以自然語言處理理解文章內容。', ['文章內容分析的需求', '實體與主題擷取', '系統架構', '應用情境']],
      ['https://tech.iheart.com/mapping-the-world-of-music-using-machine-learning-part-2-aa50b6a0304c', 'iHeartRadio 以機器學習繪製音樂世界地圖', 'iHeartRadio 以機器學習分析歌曲與藝人之間的關係。', ['音樂相似度', '嵌入向量', '視覺化', '推薦應用']],
      ['https://youtube-eng.googleblog.com/2015/10/improving-youtube-video-thumbnails-with_8.html', 'YouTube 以深度神經網路改善影片縮圖', 'YouTube 以深度學習從影片中挑選品質較好的縮圖。', ['縮圖品質的重要性', '訓練資料的來源', '品質評分模型', '上線效果']],
      ['https://dropbox.tech/machine-learning/using-machine-learning-to-index-text-from-billions-of-images', 'Dropbox 以機器學習為數十億張圖片中的文字建立索引', 'Dropbox 以光學字元辨識讓圖片與掃描檔中的文字可以被搜尋。', ['圖片文字辨識的需求', '文字偵測與辨識模型', '大規模處理的成本', '搜尋整合']],
      ['https://medium.com/airbnb-engineering/amenity-detection-and-beyond-new-frontiers-of-computer-vision-at-airbnb-144a4441b72e', 'Airbnb 的設施偵測與電腦視覺', 'Airbnb 從房源照片中自動偵測設施，減少房東手動輸入。', ['設施偵測的需求', '物件偵測模型', '訓練資料', '應用效果']],
      ['https://tech.mercari.com/entry/2019/04/26/163000', 'Mercari 以神經架構搜尋偵測違禁品', 'Mercari 以神經架構搜尋找出適合的模型，偵測違禁商品。', ['違禁品偵測的需求', '神經架構搜尋', '模型的效率', '上線效果']],
      ['https://www.zillow.com/engineering/behind-zillow-3d-home-backend-algorithms/', 'Zillow 3D Home 背後的演算法', 'Zillow 說明 3D 看屋功能背後的影像處理與演算法。', ['全景影像的處理', '房間結構的推論', '後端處理流程', '使用者體驗']],
      ['https://engineeringblog.yelp.com/2019/10/discovering-popular-dishes-with-deep-learning.html', 'Yelp 以深度學習找出熱門菜色', 'Yelp 從評論與照片中找出每家餐廳的熱門菜色。', ['從文字擷取菜色', '照片與菜色的對應', '熱門程度排序', '產品應用']],
      ['https://engineeringblog.yelp.com/2021/05/moderating-promotional-spam-and-inappropriate-content-in-photos-at-scale-at-yelp.html', 'Yelp 大規模審核照片中的廣告垃圾與不當內容', 'Yelp 以機器學習自動找出照片中的推銷內容與不當內容。', ['照片審核的規模', '分類模型', '誤判的處理', '人工審核的搭配']],
      ['https://www.etsy.com/codeascraft/machine-learning-in-content-moderation-at-etsy', 'Etsy 以機器學習審核內容', 'Etsy 以機器學習協助審核違反政策的商品。', ['內容審核的挑戰', '多種訊號的模型', '審核流程', '持續改善']],
      ['https://eng.uber.com/cota/', 'Uber 的 COTA：以自然語言處理與機器學習改善客服', 'Uber 以自然語言處理分析客服工單，自動分類並建議處理方式。', ['客服工單的量級', '文字分類', '建議回覆', '處理效率的提升']],
      ['https://dropbox.tech/machine-learning/cannes--how-ml-saves-us--1-7m-a-year-on-document-previews', 'Dropbox 的 Cannes：以機器學習每年省下文件預覽成本', 'Dropbox 預測哪些檔案會被預覽，只預先產生可能用到的預覽，大幅節省運算成本。', ['預先產生預覽的成本', '預測檔案是否會被預覽', '成本與使用者體驗的取捨', '節省的效果']],
    ],
  },
  {
    id: 's-ml-predict',
    group,
    name: '預測、定價、風控與更多應用',
    question: '機器學習還能用在哪些你想不到的地方？',
    lessons: [
      ['https://tech.instacart.com/how-instacart-delivers-on-time-using-quantile-regression-2383e2e03edb', 'Instacart 以分位數迴歸準時送達', 'Instacart 以分位數迴歸預估送達時間的不確定性，提升準時率。', ['平均預測的不足', '分位數迴歸的原理', '以不確定性做決策', '準時率的改善']],
      ['https://eng.uber.com/forecasting-introduction/', 'Uber 的預測入門', 'Uber 介紹預測在業務中的角色，以及常見的預測方法。', ['預測的業務應用', '經典統計方法', '機器學習方法', '預測的評估']],
      ['https://eng.uber.com/transforming-financial-forecasting-machine-learning/', 'Uber 以機器學習改造財務預測', 'Uber 以機器學習自動化財務預測，提升準確度與效率。', ['財務預測的需求', '模型的選擇', '預測平台', '與財務流程整合']],
      ['https://eng.lyft.com/making-long-term-forecasts-at-lyft-fac475b3ba52', 'Lyft 的長期預測', 'Lyft 說明如何做長期的需求預測，支援業務規劃。', ['長期預測的挑戰', '模型與假設', '不確定性的呈現', '業務規劃的應用']],
      ['https://engineeringblog.yelp.com/2019/12/architecting-wait-time-estimations.html', 'Yelp 預估餐廳候位時間的架構', 'Yelp 說明預估餐廳候位時間的系統架構與模型。', ['候位時間預估的需求', '即時資料', '預測模型', '系統架構']],
      ['https://blog.gojekengineering.com/how-we-use-machine-learning-to-match-drivers-riders-b06d617b9e5', 'GO-JEK 以機器學習媒合司機與乘客', 'GO-JEK 說明以機器學習改善司機與乘客的媒合。', ['媒合問題的特性', '預測接單機率', '最佳化指派', '效果評估']],
      ['https://medium.com/netflix-techblog/using-machine-learning-to-improve-streaming-quality-at-netflix-9651263ef09f', 'Netflix 以機器學習提升串流品質', 'Netflix 以機器學習預測網路狀況，改善位元率選擇與預先快取。', ['串流品質的挑戰', '網路品質預測', '自適應位元率', '預測快取內容']],
      ['https://hackernoon.com/pricingnet-modelling-the-global-airline-industry-with-neural-networks-833844d20ea6', 'Skyscanner 的 PricingNet：以神經網路建模全球機票價格', 'Skyscanner 以神經網路預測機票價格。', ['機票價格的複雜性', '神經網路模型', '特徵設計', '預測的應用']],
      ['https://sg.godaddy.com/engineering/2019/07/26/domain-name-valuation/', 'GoDaddy 以深度學習估算網域名稱價值', 'GoDaddy 以深度學習預測網域名稱的市場價值。', ['網域估價的需求', '名稱的特徵', '深度學習模型', '評估方式']],
      ['https://stripe.com/blog/similarity-clustering', 'Stripe 以相似度分群找出詐騙集團', 'Stripe 以帳號之間的相似度分群，找出協同運作的詐騙集團。', ['詐騙集團的特徵', '帳號相似度的計算', '分群演算法', '人工調查的搭配']],
      ['https://engineering.linkedin.com/blog/2018/09/automated-fake-account-detection-at-linkedin', 'LinkedIn 自動偵測假帳號', 'LinkedIn 以多層防線與機器學習自動偵測假帳號。', ['假帳號的危害', '註冊時的偵測', '行為分析', '分群偵測']],
      ['https://dropbox.tech/machine-learning/optimizing-payments-with-machine-learning', 'Dropbox 以機器學習最佳化付款', 'Dropbox 以機器學習選擇重試扣款的時機，提升付款成功率。', ['扣款失敗的問題', '預測最佳重試時機', '實驗與評估', '營收改善']],
      ['http://engineering.pivotal.io/post/scaling-machine-learning-to-recommend-driving-routes/', 'Pivotal 擴展機器學習推薦行車路線', 'Pivotal 說明以機器學習推薦行車路線的做法與擴展方式。', ['路線推薦的需求', '以歷史軌跡學習', '模型的擴展', '應用情境']],
      ['https://engineering.foursquare.com/you-are-probably-here-better-map-pins-with-dbscan-random-forests-9d51e8c1964d', 'Foursquare 以 DBSCAN 與隨機森林改善地圖標記', 'Foursquare 以分群與分類模型，讓地點在地圖上的標記更準確。', ['地點座標不準的問題', 'DBSCAN 密度分群', '隨機森林分類', '效果評估']],
      ['http://engineering.monsanto.com/2015/11/23/chinese-restaurant-process/', 'Monsanto 以 Scala 實作狄利克雷過程混合模型分群', 'Monsanto 以中國餐館過程說明狄利克雷過程混合模型，並以 Scala 實作分群。', ['不需預設群數的分群', '中國餐館過程', '吉布斯抽樣', 'Scala 實作']],
      ['https://cdn.oreillystatic.com/en/assets/1/event/144/Atom%20smashing%20using%20machine%20learning%20at%20CERN%20Presentation.pdf', '歐洲核子研究組織以機器學習分析粒子碰撞', '歐洲核子研究組織在研討會分享以機器學習分析粒子碰撞資料。', ['粒子物理的資料量', '事件篩選', '機器學習模型', '運算基礎設施']],
      ['https://blog.janestreet.com/real-world-machine-learning-part-1/', 'Jane Street 的真實世界機器學習', 'Jane Street 分享在交易公司中應用機器學習的經驗。', ['金融資料的特性', '模型的評估', '過度擬合的風險', '實務經驗']],
      ['https://machinelearning.apple.com/2017/12/06/learning-with-privacy-at-scale.html', 'Apple 大規模的隱私保護學習', 'Apple 以本地差分隱私收集使用趨勢，同時保護個人資料。', ['本地差分隱私', '在裝置上加入雜訊', '彙總統計', '隱私與準確度的取捨']],
      ['https://www.ebayinc.com/stories/blogs/tech/gui-testing-powered-by-deep-learning/', 'eBay 以深度學習做圖形介面測試', 'eBay 以深度學習辨識畫面元素，自動化圖形介面測試。', ['介面測試的維護成本', '以影像辨識畫面元素', '測試的自動化', '效果評估']],
      ['https://www.ebayinc.com/stories/blogs/tech/altus-care-apply-chatbot-to-ebay-platform-engineering/', 'eBay 的 Altus Care：把聊天機器人用在平台工程', 'eBay 以聊天機器人回答開發者對平台的常見問題。', ['平台支援的負擔', '問題分類與回覆', '知識庫', '效率改善']],
      ['https://www.uber.com/blog/genie-ubers-gen-ai-on-call-copilot/', 'Uber 的 Genie：生成式人工智慧值班助手', 'Uber 以生成式人工智慧回答值班頻道中的問題，減輕值班工程師的負擔。', ['值班支援的負擔', '以檢索增強生成回答問題', '知識來源的整理', '回答品質的評估']],
      ['https://code.fb.com/developer-tools/aroma/', 'Facebook 的 Aroma：以機器學習推薦程式碼', 'Facebook 以程式碼結構比對，推薦相似的程式碼寫法。', ['程式碼推薦的需求', '以語法結構表示程式碼', '相似程式碼的搜尋與分群', '推薦結果']],
      ['https://medium.com/airbnb-engineering/contextualizing-airbnb-by-building-knowledge-graph-b7077e268d5a', 'Airbnb 建立知識圖譜', 'Airbnb 以知識圖譜整合地點、活動與房源等資訊。', ['知識圖譜的用途', '實體與關係', '圖譜的建立與維護', '應用情境']],
      ['https://instagram-engineering.com/core-modeling-at-instagram-a51e0158aa48', 'Instagram 的核心建模', 'Instagram 說明核心機器學習建模團隊的工作方式與技術。', ['核心模型的角色', '共用的特徵與模型', '實驗與評估', '團隊協作']],
    ],
  },
];
