import type { UnitSource } from './types';

// 第三階：技能｜可觀測性、資安、服務與交付
export const skillOps: UnitSource[] = [
  {
    id: 's-logging',
    group: '可觀測性',
    name: '日誌',
    question: '事情發生之後，你能從紀錄中還原真相嗎？',
    lessons: [
      ['https://blog.codinghorror.com/the-problem-with-logging/', '日誌的問題', 'Jeff Atwood 反思過度寫日誌的代價：日誌太多反而讓問題更難找，還拖慢系統。', ['日誌過多造成的效能負擔', '雜訊掩蓋真正的問題', '只記錄值得採取行動的事件', '以監控與例外追蹤補足日誌']],
      ['https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying', '日誌：每個軟體工程師都該知道的即時資料統一抽象', 'Jay Kreps 的經典長文，說明只能附加、依時間排序的日誌，如何成為資料庫、資料整合與串流處理的共同基礎。', ['日誌是依時間排序的紀錄', '以日誌同步多個資料系統', '以日誌作為資料整合的中樞', '串流處理與日誌的關係', '狀態機複寫']],
      ['https://medium.com/@Pinterest_Engineering/scalable-and-reliable-data-ingestion-at-pinterest-b921c2ee8754', 'Pinterest 可擴展又可靠的資料攝取', 'Pinterest 說明如何從大量伺服器收集日誌，並可靠地送進 Kafka 與資料倉儲。', ['從大量主機收集日誌的挑戰', '以本機代理程式緩衝與傳送', '確保不遺失、不重複', '攝取流程的監控']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2015/building-distributedlog-twitter-s-high-performance-replicated-log-servic.html', 'Twitter 的 DistributedLog：高效能複寫日誌服務', 'Twitter 以 BookKeeper 打造的複寫日誌服務，提供低延遲、高持久性的日誌儲存。', ['複寫日誌服務的需求', '以 BookKeeper 儲存日誌分段', '寫入延遲與持久性', '讀寫分離的架構']],
      ['https://databricks.com/blog/2017/12/14/the-architecture-of-the-next-cern-accelerator-logging-service.html', '歐洲核子研究組織以 Spark 打造加速器日誌服務', '歐洲核子研究組織說明下一代加速器日誌服務的架構，以 Spark 處理大量設備資料。', ['加速器設備資料的量級', '以 Spark 擷取與查詢資料', '儲存格式與分割', '科學家的資料存取需求']],
      ['https://quoraengineering.quora.com/Logging-and-Aggregation-at-Quora', 'Quora 的日誌與彙總', 'Quora 說明日誌收集、彙總與分析的流程。', ['日誌的收集方式', '集中式彙總', '從日誌產生指標', '保存與查詢']],
      ['https://badoo.com/techblog/blog/2016/06/06/collection-and-analysis-of-daemon-logs-at-badoo/', 'Badoo 收集與分析常駐程式日誌', 'Badoo 分享從大量常駐程式收集日誌並加以分析的做法。', ['常駐程式日誌的特性', '集中收集', '結構化與搜尋', '異常偵測']],
      ['https://medium.com/palantir/using-static-code-analysis-to-improve-log-parsing-18f0d1843965', 'Palantir 以靜態程式碼分析改善日誌解析', 'Palantir 從程式碼中自動擷取日誌格式，讓非結構化日誌也能被準確解析。', ['非結構化日誌難以解析', '從原始碼找出日誌格式', '自動產生解析規則', '解析準確度的提升']],
      ['https://tech.ebayinc.com/engineering/low-latency-and-high-throughput-cal-ingress/', 'eBay 集中式應用程式日誌的攝取層', 'eBay 改善集中式應用程式日誌系統的攝取層，兼顧低延遲與高吞吐量。', ['集中式日誌系統的角色', '攝取層的瓶頸', '非阻塞架構與批次處理', '延遲與吞吐量的改善']],
      ['https://netflixtechblog.com/hyper-scale-vpc-flow-logs-enrichment-to-provide-network-insight-e5f1db02910d', 'Netflix 超大規模豐富雲端網路流量日誌', 'Netflix 為雲端網路流量日誌補上服務與應用程式資訊，提供網路層的洞察。', ['網路流量日誌的量級', '把網路位址對應到應用程式', '串流處理與資料豐富化', '網路洞察的應用']],
      ['https://yahooeng.tumblr.com/post/109908973316/bookkeeper-yahoos-distributed-log-storage-is', 'Yahoo 的 BookKeeper：分散式日誌儲存', 'Yahoo 分享以 Apache BookKeeper 作為分散式日誌儲存的經驗。', ['只附加日誌的儲存需求', '分段與副本', '寫入的一致性', '在訊息系統中的應用']],
      ['https://code.facebook.com/posts/357056558062811/logdevice-a-distributed-data-store-for-logs/', 'Facebook 的 LogDevice：分散式日誌資料儲存', 'Facebook 為日誌打造的分散式儲存，重視寫入可用性與依序讀取。', ['日誌儲存的特殊需求', '彈性的副本放置提升寫入可用性', '序號產生與依序讀取', '故障時的恢復']],
      ['https://engineeringblog.yelp.com/2018/03/introducing-logfeeder.html', 'Yelp 的 LogFeeder：日誌收集系統', 'Yelp 打造的日誌收集系統，把第三方服務的日誌匯入內部平台。', ['第三方服務日誌的收集需求', '定期拉取與匯入', '資料格式的轉換', '安全與權限']],
      ['https://medium.com/netflix-techblog/dblog-a-generic-change-data-capture-framework-69351fb9099b', 'Netflix 的 DBLog：通用的變更資料擷取框架', 'Netflix 的變更資料擷取框架，能在不鎖表的情況下同時處理全量資料與即時變更。', ['變更資料擷取的用途', '全量傾印與交易日誌交錯處理', '不鎖表、不暫停寫入', '支援多種資料庫']],
    ],
  },
  {
    id: 's-monitoring',
    group: '可觀測性',
    name: '監控與告警',
    question: '你是在使用者發現之前，還是之後才知道系統壞了？',
    lessons: [
      ['https://www.oreilly.com/ideas/monitoring-distributed-systems', '監控分散式系統', '《Google 網站可靠性工程》的章節，說明監控的目的、四個黃金訊號與告警原則。', ['白箱監控與黑箱監控', '四個黃金訊號：延遲、流量、錯誤、飽和度', '區分症狀與原因', '告警要能採取行動，避免雜訊']],
      ['https://www.ebayinc.com/stories/blogs/tech/unicorn-rheos-remediation-center/', 'eBay 的 Unicorn：自動修復中心', 'eBay 為串流平台打造的自動修復系統，偵測到問題後自動執行修復動作。', ['從告警走向自動修復', '規則與修復動作的設計', '修復動作的安全機制', '減少人工介入']],
      ['https://eng.uber.com/optimizing-m3/', 'Uber 最佳化 M3 指標與監控平台', 'Uber 說明如何最佳化自建的 M3 指標平台，把指標攝取延遲大幅縮短。', ['大規模指標平台的挑戰', '指標攝取的延遲來源', '彙總層的最佳化', '效能改善的量測']],
      ['https://dropbox.tech/infrastructure/athena-our-automated-build-health-management-system', 'Dropbox 的 Athena：自動化建置健康管理', 'Dropbox 自動偵測並隔離不穩定的測試，維持持續整合的健康。', ['不穩定測試對開發的影響', '自動偵測與隔離', '通知負責的團隊', '建置健康指標']],
      ['https://dropbox.tech/infrastructure/monitoring-server-applications-with-vortex', 'Dropbox 的 Vortex：伺服器應用程式監控', 'Dropbox 自建的指標監控系統，處理大量指標的收集、儲存與查詢。', ['取代舊監控系統的原因', '指標的收集與彙總', '高基數指標的處理', '查詢與告警']],
      ['https://engineering.linkedin.com/blog/2019/solving-manageability-challenges-with-nuage', 'LinkedIn 的 Nuage：雲端資源管理服務', 'LinkedIn 打造的管理平台，讓工程師自助管理資料庫、快取等基礎設施資源。', ['基礎設施管理的痛點', '自助式資源管理', '統一的管理介面', '權限與稽核']],
      ['https://netflixtechblog.com/telltale-netflix-application-monitoring-simplified-5c08bfa780ba', 'Netflix 的 Telltale：簡化的應用程式監控', 'Netflix 綜合多種訊號自動判斷應用程式的健康狀態，減少人工盯圖表。', ['人工監控的負擔', '綜合多種訊號判斷健康', '智慧告警', '事故時提供脈絡資訊']],
      ['https://engineering.linkedin.com/blog/2019/06/smart-alerts-in-thirdeye--linkedins-real-time-monitoring-platfor', 'LinkedIn 的 ThirdEye：即時監控平台的智慧告警', 'LinkedIn 以異常偵測演算法監控業務指標，並提供根因分析。', ['業務指標的異常偵測', '季節性與趨勢', '減少誤報', '根因分析']],
      ['https://developers.soundcloud.com/blog/periskop-exception-monitoring-service', 'SoundCloud 的 Periskop：例外監控服務', 'SoundCloud 開源的例外彙總服務，從各服務收集例外並彙總呈現。', ['例外資訊的收集', '以拉取方式彙總', '例外的分組與計數', '與既有監控整合']],
      ['https://dropbox.tech/security/meet-securitybot-open-sourcing-automated-security-at-scale', 'Dropbox 的 Securitybot：分散式資安告警機器人', 'Dropbox 開源的機器人，在可疑行為發生時直接詢問當事人，減少資安團隊的人工調查。', ['資安告警量過大的問題', '由機器人向當事人確認', '以雙因素驗證確認身分', '縮短誤報的處理時間']],
      ['https://www.usenix.org/conference/srecon18asia/presentation/xinchi', '阿里巴巴的監控系統', '阿里巴巴演講分享大規模監控系統的架構與挑戰。', ['大規模監控的資料量', '資料收集與處理架構', '告警與關聯分析', '維運經驗']],
      ['https://medium.com/dailymotion/real-user-monitoring-1948375f8be5', 'Dailymotion 的真實使用者監控', 'Dailymotion 收集真實使用者的效能資料，了解實際的播放與載入體驗。', ['真實使用者監控與合成監控的差異', '收集瀏覽器效能資料', '指標的彙總與分析', '以量測結果改善體驗']],
      ['https://eng.uber.com/observability-at-scale/', 'Uber 的告警生態系', 'Uber 說明大規模告警系統的架構，涵蓋指標告警與日誌告警。', ['以指標與日誌為基礎的告警', '告警規則的管理', '大規模告警的評估', '減少告警疲勞']],
      ['https://medium.com/airbnb-engineering/alerting-framework-at-airbnb-35ba48df894f', 'Airbnb 的告警框架', 'Airbnb 以程式碼定義告警，讓告警設定可以審查、測試與版本控制。', ['以程式碼定義告警', '告警的審查與測試', '統一的告警格式', '減少重複設定']],
      ['https://developers.soundcloud.com/blog/alerting-on-slos', 'SoundCloud 依服務水準目標告警', 'SoundCloud 改以服務水準目標與錯誤預算的消耗速度發出告警，減少雜訊。', ['服務水準指標與服務水準目標', '錯誤預算', '依消耗速度告警', '多時間視窗的告警']],
      ['https://eng.uber.com/observability-anomaly-detection/', 'Uber 以預測工作流程偵測可觀測性異常', 'Uber 打造以工作排程為基礎的預測流程，偵測指標異常。', ['異常偵測的需求', '時間序列預測', '大規模預測工作的排程', '降低誤報']],
      ['http://engineering.hackerearth.com/2017/03/21/monitoring-and-alert-system-using-graphite-and-cabot/', 'HackerEarth 以 Graphite 與 Cabot 打造監控告警', 'HackerEarth 分享以開源工具組成監控與告警系統的做法。', ['以 Graphite 收集與儲存指標', '以 Cabot 設定告警', '健康檢查', '整合通知管道']],
      ['https://blog.twitter.com/engineering/en_us/a/2016/observability-at-twitter-technical-overview-part-ii.html', 'Twitter 的可觀測性技術總覽', 'Twitter 介紹可觀測性平台的架構，涵蓋指標收集、儲存、查詢與告警。', ['指標收集與儲存', '查詢語言與儀表板', '告警系統', '平台的擴展']],
      ['https://slack.engineering/distributed-security-alerting-c89414c992d6', 'Slack 的分散式資安告警', 'Slack 把資安告警直接發給相關員工確認，讓資安團隊專注在真正的威脅。', ['集中式資安告警的瓶頸', '把告警分派給當事人', '自動化的確認流程', '只升級真正可疑的事件']],
      ['https://www.infoq.com/presentations/news-alerting-bloomberg', 'Bloomberg 的即時新聞告警', 'Bloomberg 演講分享如何在新聞發布後極短時間內通知大量使用者。', ['即時新聞告警的延遲需求', '訂閱條件的比對', '大量通知的發送', '系統的可靠性']],
      ['https://engineering.linkedin.com/blog/2019/an-inside-look-at-linkedins-data-pipeline-monitoring-system-', 'LinkedIn 的資料管線監控系統', 'LinkedIn 說明如何監控資料管線的延遲、完整性與品質。', ['資料管線的監控需求', '資料延遲與完整性指標', '異常告警', '管線之間的相依關係']],
      ['https://blog.picnic.nl/monitoring-and-observability-at-picnic-684cefd845c4', 'Picnic 的監控與可觀測性', 'Picnic 分享以開源工具建立監控與可觀測性的做法。', ['指標、日誌與追蹤', '工具的選擇', '儀表板與告警', '可觀測性的團隊文化']],
    ],
  },
  {
    id: 's-tracing',
    group: '可觀測性',
    name: '分散式追蹤與量測',
    question: '一個請求穿過二十個服務，慢在哪一段？',
    lessons: [
      ['https://www.oreilly.com/ideas/understanding-the-value-of-distributed-tracing', '理解分散式追蹤的價值', '說明分散式追蹤如何串起一個請求在多個服務之間的旅程，找出延遲與錯誤的來源。', ['追蹤、跨度與脈絡傳遞', '找出請求路徑上的瓶頸', '取樣策略', '與指標、日誌的互補']],
      ['https://blog.twitter.com/engineering/en_us/a/2012/distributed-systems-tracing-with-zipkin.html', 'Twitter 的 Zipkin：分散式系統追蹤', 'Twitter 開源的分散式追蹤系統，參考 Google Dapper 設計，呈現請求在服務之間的時間分布。', ['參考 Dapper 的設計', '追蹤資料的收集與儲存', '時間軸視覺化', '取樣與效能負擔']],
      ['https://developers.soundcloud.com/blog/using-kubernetes-pod-metadata-to-improve-zipkin-traces', 'SoundCloud 以 Kubernetes 容器資訊改善 Zipkin 追蹤', 'SoundCloud 把容器的中繼資料加進追蹤資料，方便定位問題發生在哪個執行個體。', ['追蹤資料缺乏部署脈絡', '自動加入容器與節點資訊', '追蹤與部署的關聯', '除錯效率的提升']],
      ['https://www.infoq.com/presentations/canopy-scalable-tracing-analytics-facebook', 'Facebook 的 Canopy：可擴展的追蹤與分析', 'Facebook 的端到端效能追蹤系統，從瀏覽器到後端收集追蹤資料並進行大規模分析。', ['端到端追蹤的範圍', '追蹤資料的建模', '大規模的特徵擷取與分析', '效能退步的偵測']],
      ['https://medium.com/@Pinterest_Engineering/distributed-tracing-at-pinterest-with-new-open-source-tools-a4f8a5562f6b', 'Pinterest 的 Pintrace：分散式追蹤', 'Pinterest 以開源工具建立分散式追蹤，找出請求在各服務中的延遲。', ['追蹤資料的收集', '以 Kafka 與 Spark 處理追蹤資料', '跨程式語言的支援', '找出延遲熱點']],
      ['https://engineering.atspotify.com/2021/01/20/introducing-xcmetrics-our-all-in-one-tool-for-tracking-xcode-build-metrics/', 'Spotify 的 XCMetrics：追蹤 Xcode 建置指標', 'Spotify 開源的工具，收集 iOS 專案的建置時間與警告等指標，找出影響開發效率的問題。', ['建置時間對開發效率的影響', '收集 Xcode 建置日誌', '指標的彙總與分析', '以量測結果改善建置']],
      ['https://engineering.linkedin.com/distributed-service-call-graph/real-time-distributed-tracing-website-performance-and-efficiency', 'LinkedIn 的即時分散式追蹤', 'LinkedIn 建立服務呼叫圖的即時追蹤，用來分析網站效能與效率。', ['服務呼叫圖', '即時收集追蹤資料', '找出效能瓶頸', '容量與效率分析']],
      ['https://www.usenix.org/conference/srecon17americas/program/presentation/arthorne', 'Shopify 大規模追蹤服務基礎設施', 'Shopify 演講分享如何追蹤與管理大量服務的基礎設施資訊。', ['服務目錄與負責人', '基礎設施資訊的收集', '服務之間的相依', '事故時的資訊查找']],
      ['https://engineering.hellofresh.com/scaling-hellofresh-distributed-tracing-7b182928247d', 'HelloFresh 的分散式追蹤', 'HelloFresh 分享導入分散式追蹤的過程與擴展方式。', ['導入追蹤的動機', '追蹤工具的選擇', '取樣與儲存成本', '團隊的導入']],
      ['https://medium.com/@Pinterest_Engineering/analyzing-distributed-trace-data-6aae58919949', 'Pinterest 分析分散式追蹤資料', 'Pinterest 把大量追蹤資料彙總分析，找出系統層級的效能問題。', ['單一追蹤與彙總分析的差別', '追蹤資料的處理管線', '找出常見的延遲模式', '分析結果的應用']],
      ['https://eng.uber.com/distributed-tracing/', 'Uber 分散式追蹤的演進', 'Uber 說明分散式追蹤從早期工具演進到 Jaeger 的過程。', ['追蹤系統的演進', 'Jaeger 的架構', '脈絡傳遞的導入', '取樣策略']],
      ['https://eng.uber.com/jvm-profiler/', 'Uber 的 JVM Profiler：追蹤分散式 JVM 應用程式', 'Uber 開源的效能剖析工具，收集 Spark 等分散式 JVM 應用程式的資源用量與方法呼叫。', ['分散式應用程式難以剖析', '以 Java 代理程式收集資料', '記憶體與處理器用量', '方法層級的追蹤']],
      ['https://www.usenix.org/conference/srecon17asia/program/presentation/mah', 'Dropbox 的資料檢查', 'Dropbox 演講分享如何持續檢查儲存資料的正確性與完整性。', ['資料損毀的風險', '持續驗證資料', '檢查的效率與涵蓋範圍', '發現問題後的修復']],
      ['https://tech.showmax.com/2016/10/tracing-distributed-systems-at-showmax/', 'Showmax 的分散式系統追蹤', 'Showmax 分享在串流服務中導入分散式追蹤的做法。', ['追蹤的需求', '追蹤資料的收集', '視覺化', '除錯的應用']],
      ['https://medium.com/@palantir/osquery-across-the-enterprise-3c3c9d13ec55', 'Palantir 在企業內部署 osquery', 'Palantir 分享以 osquery 查詢大量主機的狀態，用於資安監控。', ['以 SQL 查詢作業系統狀態', '大規模部署與設定', '資安偵測的應用', '資料的收集與分析']],
      ['https://codeascraft.com/2011/02/15/measure-anything-measure-everything/', 'Etsy 的 StatsD：量測一切', 'Etsy 發表 StatsD 的經典文章，主張把所有事情都量測起來，並讓新增指標幾乎沒有成本。', ['量測一切的文化', '以 UDP 送出指標', '計數器與計時器', '讓新增指標幾乎沒有成本']],
    ],
  },
  {
    id: 's-security',
    group: '資安',
    name: '分散式資安',
    question: '機器與人都變多之後，要怎麼只讓對的人做對的事？',
    lessons: [
      ['https://msdn.microsoft.com/en-us/library/cc767123.aspx', '分散式安全性', '微軟技術文件，說明分散式環境中的身分驗證、授權與信任關係。', ['分散式環境的身分驗證', '授權與存取控制', '網域之間的信任', '加密與憑證']],
      ['https://medium.com/netflix-techblog/introducing-aardvark-and-repokid-53b081bf3a7e', 'Netflix 的 Aardvark 與 Repokid：自動落實最小權限', 'Netflix 開源工具，自動找出並移除雲端角色沒用到的權限，落實最小權限。', ['權限過大的風險', '分析實際使用的權限', '自動移除未使用的權限', '在快速開發中維持最小權限']],
      ['https://www.slideshare.net/MikeSvoboda/2017-lisa-linkedins-distributed-firewall-dfw', 'LinkedIn 的分散式防火牆', 'LinkedIn 在研討會分享以主機層級防火牆，實現分散式的網路存取控制。', ['傳統邊界防火牆的限制', '主機層級的防火牆規則', '規則的集中管理與分發', '大規模部署']],
      ['https://engineering.coinbase.com/how-coinbase-builds-secure-infrastructure-to-store-bitcoin-in-the-cloud-30a6504e40ba', 'Coinbase 在雲端安全存放比特幣的基礎設施', 'Coinbase 說明如何在雲端設計高安全性的基礎設施，保護加密貨幣資產。', ['冷錢包與熱錢包的分離', '多重簽章與金鑰管理', '最小權限與隔離', '稽核與監控']],
      ['https://medium.com/airbnb-engineering/binaryalert-real-time-serverless-malware-detection-ca44370c1b90', 'Airbnb 的 BinaryAlert：即時無伺服器惡意程式偵測', 'Airbnb 開源的無伺服器工具，以 YARA 規則即時掃描上傳到儲存空間的檔案。', ['以 YARA 規則描述惡意程式特徵', '無伺服器架構的掃描', '即時告警', '規模與成本']],
      ['https://segment.com/blog/secure-access-to-100-aws-accounts/', 'Segment 保護上百個 AWS 帳號的存取架構', 'Segment 說明如何以可擴展的身分與存取管理架構，管理大量 AWS 帳號的權限。', ['多帳號架構的好處', '集中式身分管理', '角色切換與最小權限', '稽核']],
      ['http://engineering.indeedblog.com/blog/2018/04/oaudit-toolbox/', 'Indeed 的授權稽核工具箱', 'Indeed 開源工具，稽核員工授予第三方應用程式的存取權限。', ['第三方應用程式授權的風險', '找出高風險的授權', '自動化稽核', '撤銷不必要的授權']],
      ['https://engineeringblog.yelp.com/2018/04/ad-password-blacklisting.html', 'Yelp 的公司帳號密碼黑名單', 'Yelp 在公司帳號系統中阻擋常見與外洩的密碼。', ['弱密碼的風險', '外洩密碼清單', '設定密碼時即時檢查', '對使用者的影響']],
      ['https://slack.engineering/syscall-auditing-at-scale-e6a3ca8ac1b8', 'Slack 大規模稽核系統呼叫', 'Slack 以 go-audit 收集大量主機的系統呼叫紀錄，用於資安偵測。', ['系統呼叫稽核的價值', '傳統稽核工具的效能問題', '以 go-audit 收集並輸出紀錄', '大規模分析']],
      ['https://yahooeng.tumblr.com/post/160481899076/open-sourcing-athenz-fine-grained-role-based', 'Yahoo 開源 Athenz：細粒度的角色存取控制', 'Yahoo 開源的授權系統，以角色為基礎提供服務之間的細粒度存取控制。', ['以角色為基礎的存取控制', '服務身分與憑證', '集中式政策管理', '去中心化的授權檢查']],
      ['https://slack.engineering/moving-fast-and-securing-things-540e6c5ae58a', 'Slack：開發快速又兼顧安全', 'Slack 說明如何把資安審查融入開發流程，又不拖慢速度。', ['資安開發生命週期', '自助式的風險評估', '依風險決定審查深度', '用工具降低摩擦']],
      ['https://kinvolk.io/blog/2018/04/towards-unprivileged-container-builds/', 'Kinvolk：邁向無特權的容器建置', 'Kinvolk 探討如何在不需要特權的情況下建置容器映像檔。', ['特權建置的資安風險', '使用者命名空間', '無特權建置工具', '限制與取捨']],
      ['https://medium.com/netflix-techblog/netflix-sirt-releases-diffy-a-differencing-engine-for-digital-forensics-in-the-cloud-37b71abd2698', 'Netflix 的 Diffy：雲端數位鑑識差異比對引擎', 'Netflix 資安事件應變團隊開源的工具，比對大量主機的差異，快速找出遭入侵的機器。', ['大規模事件應變的挑戰', '以差異找出異常主機', '收集主機狀態', '加速鑑識流程']],
      ['https://medium.com/netflix-techblog/netflix-cloud-security-detecting-credential-compromise-in-aws-9493d6fd373a', 'Netflix 偵測 AWS 憑證外洩', 'Netflix 說明如何偵測雲端暫時憑證在公司以外的地方被使用。', ['暫時憑證外洩的風險', '以使用位置判斷異常', '稽核紀錄的分析', '自動告警與應變']],
      ['https://labs.spotify.com/2018/09/18/scalable-user-privacy/', 'Spotify 可擴展的使用者隱私保護', 'Spotify 以每位使用者專屬的加密金鑰保護個人資料，讓刪除資料可以大規模落實。', ['隱私法規的要求', '以每位使用者的金鑰加密資料', '銷毀金鑰即等於刪除資料', '在資料管線中的應用']],
      ['https://engineering.indeedblog.com/blog/2018/09/application-scanning/', 'Indeed 的 AVA：網頁應用程式稽核', 'Indeed 開源的網頁弱點掃描器，整合進開發流程自動檢查網頁應用程式。', ['自動化弱點掃描', '整合持續整合流程', '減少誤報', '弱點的追蹤']],
      ['https://engineeringblog.yelp.com/2018/11/ttl-as-a-service.html', 'Yelp 自動撤銷過期權限的服務', 'Yelp 讓臨時權限在期限到時自動撤銷，避免權限長期累積。', ['權限累積的風險', '為權限設定期限', '自動撤銷流程', '稽核與通知']],
      ['https://slack.engineering/engineering-dive-into-slack-enterprise-key-management-1fce471b178c', 'Slack 企業金鑰管理的工程細節', 'Slack 說明讓企業客戶自行掌控加密金鑰的設計。', ['客戶自行掌控金鑰的需求', '信封加密', '撤銷金鑰的影響', '效能與快取']],
      ['https://blog.twitch.tv/en/2019/03/15/how-twitch-addresses-scalability-and-authentication/', 'Twitch 的擴展性與身分驗證', 'Twitch 說明身分驗證系統如何在大量使用者下擴展。', ['身分驗證系統的負載', '權杖的設計', '快取與效能', '安全性考量']],
      ['https://netflixtechblog.com/edge-authentication-and-token-agnostic-identity-propagation-514e47e0b602', 'Netflix 的邊緣身分驗證與內部身分傳遞', 'Netflix 把身分驗證移到邊緣閘道，並在內部以統一的身分結構傳遞使用者身分。', ['各服務自行驗證的問題', '在邊緣統一驗證', '內部身分資訊的傳遞', '降低各服務的複雜度']],
      ['https://blog.palantir.com/hardening-palantirs-kubernetes-infrastructure-with-cilium-1c40d4c7ef0', 'Palantir 以 Cilium 強化 Kubernetes 基礎設施', 'Palantir 以 Cilium 的網路政策隔離工作負載，強化 Kubernetes 的安全性。', ['容器網路的安全需求', '以 eBPF 實作網路政策', '工作負載之間的隔離', '導入與遷移']],
      ['https://eng.lyft.com/improving-web-vulnerability-management-through-automation-2631570d8415', 'Lyft 以自動化改善網頁弱點管理', 'Lyft 把網頁弱點的掃描、分派與追蹤流程自動化。', ['弱點管理的人工負擔', '自動化掃描', '自動分派給負責團隊', '追蹤修復進度']],
      ['https://dropbox.tech/application/dropbox-passwords-clock-skew-payload-sync-merge', 'Dropbox Passwords 同步資料時的時鐘偏差', 'Dropbox 說明密碼管理服務在多裝置同步時，因時鐘偏差造成的合併問題與解法。', ['多裝置同步的衝突', '時鐘偏差的影響', '合併策略的設計', '確保資料不遺失']],
    ],
  },
  {
    id: 's-micro',
    group: '服務與交付',
    name: '微服務',
    question: '服務拆開之後，複雜度跑去哪裡了？',
    lessons: [
      ['https://martinfowler.com/microservices/', '微服務資源指南', 'Martin Fowler 整理的微服務指南，涵蓋定義、先決條件、取捨，以及什麼時候不該使用。', ['微服務的定義與特徵', '依業務能力劃分服務', '導入微服務的先決條件', '先做單體的建議']],
      ['https://eng.uber.com/microservice-architecture/', 'Uber 的領域導向微服務架構', 'Uber 在累積數千個微服務之後，改以領域、層級與閘道重新組織服務。', ['微服務數量爆炸的問題', '以領域收斂相關服務', '領域閘道', '分層的相依規則']],
      ['https://developers.soundcloud.com/blog/service-architecture-3', 'SoundCloud 的服務架構：領域閘道、加值服務與前端專屬後端', 'SoundCloud 的系列文章，說明服務架構如何分層，以及前端專屬後端的角色。', ['前端專屬後端模式', '領域閘道', '加值服務層', '架構的演進']],
      ['https://developers.soundcloud.com/blog/inside-a-soundcloud-microservice', '走進 SoundCloud 的一個微服務', 'SoundCloud 以單一微服務為例，說明它的結構、部署與維運。', ['微服務的內部結構', '部署與設定', '監控與告警', '服務的負責團隊']],
      ['https://labs.spotify.com/2018/01/11/testing-of-microservices/', 'Spotify 的微服務測試', 'Spotify 主張以整合測試為主的蜂巢式測試策略，取代傳統的測試金字塔。', ['微服務測試的挑戰', '蜂巢式測試模型', '整合測試的重點', '減少脆弱的單元測試']],
      ['https://medium.engineering/microservice-architecture-at-medium-9c33805eb74f', 'Medium 的微服務架構', 'Medium 說明從單體走向微服務的原因、原則與做法。', ['拆分的時機與原則', '服務之間的溝通', '共享資料的處理', '避免微服務的陷阱']],
      ['https://medium.com/building-nubank/microservices-at-nubank-an-overview-2ebcb336c64d', 'Nubank 的微服務總覽', 'Nubank 介紹以 Clojure 與 Kafka 為基礎的微服務架構。', ['服務的組成方式', '非同步訊息溝通', '資料的所有權', '基礎設施的自動化']],
      ['https://medium.com/bbc-design-engineering/powering-bbc-online-with-nanoservices-727840ba015b', 'BBC 以奈米服務支撐線上服務', 'BBC 以極小的無伺服器函式組成網站，說明這種細粒度架構的好處與取捨。', ['奈米服務的概念', '以無伺服器函式實作', '細粒度帶來的彈性', '延遲與成本的取捨']],
      ['https://engineering.mercari.com/en/blog/entry/20210831-2019-06-07-155849/', 'Mercari 微服務中的支付交易管理', 'Mercari 說明在微服務架構中處理支付交易一致性的做法。', ['跨服務交易的挑戰', '以狀態機管理交易', '冪等性與重試', '對帳機制']],
      ['https://tech.ebayinc.com/engineering/grit-a-protocol-for-distributed-transactions-across-microservices/', 'eBay 的 GRIT：跨微服務的分散式交易協定', 'eBay 提出以樂觀並行控制與確定性執行，在微服務之間實現分散式交易。', ['跨資料庫交易的困難', '樂觀並行控制', '交易管理器與資料庫的分工', '效能與一致性']],
      ['https://eng.uber.com/crisp-critical-path-analysis-for-microservice-architectures/', 'Uber 的 CRISP：微服務架構的關鍵路徑分析', 'Uber 以追蹤資料計算請求的關鍵路徑，找出真正影響延遲的服務。', ['關鍵路徑的概念', '從追蹤資料計算關鍵路徑', '找出最值得最佳化的服務', '大規模分析']],
      ['https://medium.com/netflix-techblog/netflix-conductor-a-microservices-orchestrator-2e8d4771bf40', 'Netflix 的 Conductor：微服務編排器', 'Netflix 開源的工作流程編排引擎，以流程定義協調多個微服務完成業務流程。', ['編排與協作的差別', '以 JSON 定義工作流程', '任務的排程與重試', '流程的視覺化']],
      ['https://eng.snap.com/monolith-to-multicloud-microservices-snap-service-mesh', 'Snap 的服務網格：從單體到多雲微服務', 'Snap 從單體遷移到多雲微服務，並以服務網格統一服務之間的通訊。', ['從單體遷移的過程', '以 Envoy 為基礎的服務網格', '多雲部署', '統一的安全與可觀測性']],
      ['https://tech.trivago.com/2020/06/10/cross-cluster-traffic-mirroring-with-istio/', 'Trivago 以 Istio 做跨叢集流量鏡像', 'Trivago 利用 Istio 把正式流量複製到另一個叢集，在不影響使用者的情況下測試新版本。', ['流量鏡像的用途', '以 Istio 設定鏡像', '跨叢集的網路', '驗證新版本的行為']],
    ],
  },
  {
    id: 's-container',
    group: '服務與交付',
    name: '容器與 Kubernetes',
    question: '把一切裝進容器之後，誰來決定它們跑在哪裡？',
    lessons: [
      ['https://engineering.riotgames.com/news/thinking-inside-container', 'Riot Games 的容器系列文章', 'Riot Games 分享導入 Docker 容器的八篇系列文章，從建置環境到正式部署。', ['以容器統一建置環境', '容器網路', '服務探索', '正式環境部署']],
      ['https://medium.com/@Pinterest_Engineering/containerization-at-pinterest-92295347f2f3', 'Pinterest 的容器化', 'Pinterest 說明把服務容器化的動機、過程與收穫。', ['容器化的動機', '映像檔建置流程', '部署與編排', '遷移策略']],
      ['https://medium.com/netflix-techblog/the-evolution-of-container-usage-at-netflix-3abfc096781b', 'Netflix 容器使用的演進', 'Netflix 說明從虛擬機器走向容器的演進，以及自建容器平台 Titus 的角色。', ['為什麼導入容器', 'Titus 容器管理平台', '批次與服務工作負載', '與既有雲端工具的整合']],
      ['https://eng.uber.com/dockerizing-mysql/', 'Uber 把 MySQL 放進 Docker', 'Uber 說明以 Docker 部署與管理大量 MySQL 執行個體的做法。', ['以容器標準化資料庫部署', '目標狀態與實際狀態的調和', '資料的持久化', '維運的自動化']],
      ['https://medium.com/treehouse-engineering/lessons-learned-running-docker-in-production-5dce99ece770', 'Treehouse 在正式環境執行 Docker 的教訓', 'Treehouse 分享在正式環境使用 Docker 所學到的經驗與陷阱。', ['映像檔的大小與建置', '日誌與監控', '網路與服務探索', '正式環境的注意事項']],
      ['https://shopifyengineering.myshopify.com/blogs/engineering/docker-at-shopify-how-we-built-containers-that-power-over-100-000-online-shops', 'Shopify 以 Docker 容器支撐十萬個網路商店', 'Shopify 說明如何以 Docker 部署核心應用程式，支撐大量商店。', ['容器化的動機', '映像檔建置流程', '部署與滾動更新', '效能與可靠性']],
      ['https://stripe.com/blog/operating-kubernetes', 'Stripe 可靠地維運 Kubernetes', 'Stripe 分享自建 Kubernetes 叢集並讓它可靠運作的經驗。', ['自建叢集的理由', '逐一驗證每個元件', '以壓力測試找出問題', '排程批次工作']],
      ['https://open.nytimes.com/agrarian-scale-kubernetes-part-3-ee459887ed7e', '紐約時報的 Kubernetes 系列', '紐約時報分享以 Kubernetes 支撐新聞業務的三篇系列文章。', ['導入 Kubernetes 的動機', '叢集的設定與管理', '服務的遷移', '團隊的學習曲線']],
      ['https://www.techatbloomberg.com/blog/powerfulseal-testing-tool-kubernetes-clusters/', 'Bloomberg 的 PowerfulSeal：Kubernetes 叢集測試工具', 'Bloomberg 開源的混沌測試工具，隨機終止 Kubernetes 中的容器與節點以驗證韌性。', ['在 Kubernetes 中做混沌測試', '隨機終止容器與節點', '互動模式與自動模式', '驗證服務的韌性']],
      ['https://boxunix.com/post/bare_metal_to_kube/', 'Betabrand 從實體機遷移到 Kubernetes', 'Betabrand 分享把網站從實體伺服器遷移到 Kubernetes 的完整過程。', ['遷移的規劃', '應用程式的容器化', '持續交付的建立', '遷移後的效益']],
      ['https://medium.com/tinder-engineering/tinders-move-to-kubernetes-cda2a6372f44', 'Tinder 遷移到 Kubernetes', 'Tinder 分享把所有服務遷移到 Kubernetes 的過程與遇到的問題。', ['遷移的動機', 'DNS 與網路的擴展問題', '大量服務的遷移', '遷移後的成果']],
      ['https://www.quora.com/q/quoraengineering/Adopting-Kubernetes-at-Quora', 'Quora 導入 Kubernetes', 'Quora 說明導入 Kubernetes 的理由與做法。', ['導入的動機', '叢集設定', '服務遷移', '維運經驗']],
      ['https://medium.com/pinterest-engineering/building-a-kubernetes-platform-at-pinterest-fb3d9571c948', 'Pinterest 打造 Kubernetes 平台', 'Pinterest 說明如何打造內部的 Kubernetes 平台，提供給各團隊使用。', ['平台化的目標', '自訂資源與運算子', '多租戶與資源管理', '與既有系統的整合']],
      ['https://medium.com/palantir/introducing-rubix-kubernetes-at-palantir-ab0ce16ea42e', 'Palantir 的 Rubix：Kubernetes 平台', 'Palantir 打造的 Kubernetes 平台，重視安全性與不可變基礎設施。', ['平台的設計目標', '安全性優先', '不可變基礎設施', '節點的定期替換']],
    ],
  },
  {
    id: 's-repo',
    group: '服務與交付',
    name: '儲存庫、相依與組態管理',
    question: '程式碼、相依套件與設定一多，怎麼不讓它們失控？',
    lessons: [
      ['https://betterexplained.com/articles/intro-to-distributed-version-control-illustrated/', '分散式版本控制圖解入門', '以圖解方式說明分散式版本控制與集中式版本控制的差別。', ['集中式與分散式版本控制', '本機儲存庫與遠端儲存庫', '分支與合併', '推送與拉取']],
      ['https://githubengineering.com/introducing-dgit/', 'GitHub 的 DGit：分散式 Git', 'GitHub 把每個儲存庫複製到多台伺服器，提升 Git 服務的可用性與效能。', ['單一儲存庫副本的風險', '在應用層複寫 Git', '分散讀取負載', '故障時的自動修復']],
      ['https://medium.com/@palantir/stemma-distributed-git-server-70afbca0fc29', 'Palantir 的 Stemma：分散式 Git 伺服器', 'Palantir 打造的分散式 Git 伺服器，支援高可用與大量儲存庫。', ['Git 伺服器的擴展需求', '分散式架構', '複寫與一致性', '維運方式']],
      ['https://code.flickr.net/2016/03/24/configuration-management-for-distributed-systems-using-github-and-cfg4j/', 'Flickr 以 GitHub 與 cfg4j 管理分散式系統的組態', 'Flickr 以 Git 儲存組態並動態載入，讓組態變更可以審查與版本控制。', ['組態與程式碼分離', '以 Git 管理組態', '動態重新載入', '組態變更的審查']],
      ['https://blogs.msdn.microsoft.com/bharry/2017/05/24/the-largest-git-repo-on-the-planet/', '微軟：全世界最大的 Git 儲存庫', '微軟把 Windows 原始碼搬到 Git，並說明如何讓 Git 撐住這麼大的儲存庫。', ['巨型儲存庫的挑戰', '虛擬檔案系統只下載需要的檔案', '複製與狀態查詢的效能', '遷移的過程']],
      ['https://www.infoq.com/news/2017/02/GVFS', '微軟以 GVFS 解決大型儲存庫的 Git 問題', '介紹微軟開源的 Git 虛擬檔案系統，讓 Git 能處理超大型儲存庫。', ['大型儲存庫的效能問題', '按需下載檔案', '檔案系統層的虛擬化', '對開發者的影響']],
      ['https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext', 'Google 為什麼把數十億行程式碼放在單一儲存庫', 'Google 說明單一儲存庫的好處、代價，以及支撐它的工具。', ['單一儲存庫的好處：統一版本與原子變更', '主幹開發', '大規模重構工具', '代價與取捨']],
      ['https://medium.com/adyen/from-0-100-billion-scaling-infrastructure-and-workflow-at-adyen-7b63b690dfb6', 'Adyen 擴展基礎設施與 Git 工作流程', 'Adyen 分享交易量從零成長到千億時，基礎設施與開發工作流程的演進。', ['業務成長對工程的影響', 'Git 工作流程的調整', '基礎設施的擴展', '文化與流程']],
      ['https://medium.com/booking-com-infrastructure/dotfiles-distribution-dedb69c66a75', 'Booking.com 的共用設定檔發布', 'Booking.com 說明如何把開發者的共用設定檔發布到大量機器上。', ['開發環境一致性的需求', '設定檔的集中管理', '發布與更新機制', '個人化與標準化的平衡']],
      ['https://engineeringblog.yelp.com/2018/06/yelps-secret-detector.html', 'Yelp 的機密偵測器：防止機密寫進原始碼', 'Yelp 開源工具，在提交程式碼前偵測金鑰與密碼，防止機密外洩。', ['機密寫進原始碼的風險', '提交前掃描', '以規則與亂度判斷機密', '降低誤報']],
      ['https://engineering.linkedin.com/blog/2018/09/managing-software-dependency-at-scale', 'LinkedIn 大規模管理軟體相依', 'LinkedIn 說明如何在大量儲存庫之間管理相依版本與升級。', ['相依地獄的問題', '版本的傳播與升級', '相依關係的視覺化', '自動化工具']],
      ['https://engineering.linkedin.com/blog/2020/continuous-integration', 'LinkedIn 如何在高速變動的儲存庫中合併程式碼', 'LinkedIn 說明在大量提交下維持主幹穩定的合併流程。', ['高頻提交造成的衝突', '合併前驗證', '合併佇列', '持續整合的效率']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2018/dynamic-configuration-at-twitter.html', 'Twitter 的動態組態', 'Twitter 打造的動態組態系統，讓服務不必重新部署就能變更設定。', ['動態組態的需求', '組態的分發與更新', '變更的安全機制', '稽核與復原']],
      ['https://medium.com/mixpaneleng/dynamic-configuration-at-mixpanel-94bfcf97d6b8', 'Mixpanel 的動態組態', 'Mixpanel 說明以 Kubernetes 的組態物件分發動態設定的做法。', ['動態組態的需求', '以 Kubernetes 組態物件分發', '設定的即時更新', '變更的安全性']],
      ['https://sg.godaddy.com/engineering/2019/03/06/dynamic-configuration-for-nodejs/', 'GoDaddy 的 Node.js 動態組態', 'GoDaddy 說明為 Node.js 服務打造動態組態的做法。', ['動態組態的需求', '組態的來源與合併', '即時更新', '測試與驗證']],
      ['https://engineering.atspotify.com/2023/5/fleet-management-at-spotify-part-3-fleet-wide-refactoring', 'Spotify 的機群管理：全機群重構', 'Spotify 說明如何對上千個元件自動進行大規模重構與升級。', ['機群管理的概念', '自動化的大規模變更', '以自動產生的合併請求推動升級', '變更的追蹤']],
    ],
  },
  {
    id: 's-cicd',
    group: '服務與交付',
    name: '規模化的持續整合與交付',
    question: '一天部署上百次，還能保持穩定嗎？',
    lessons: [
      ['https://www.synopsys.com/blogs/software-security/agile-cicd-devops-glossary/', '敏捷、持續整合／交付與開發維運的差別', '整理敏捷開發、持續整合、持續交付與開發維運的常見術語與差異。', ['持續整合與持續交付的差別', '持續部署', '開發維運的文化', '自動化測試的角色']],
      ['https://code.fb.com/web/rapid-release-at-massive-scale/', 'Facebook 大規模的快速發布', 'Facebook 說明如何從每週發布，改成每天多次持續地把程式碼推到正式環境。', ['從分支發布改為持續推送', '分階段發布', '自動化測試與監控', '功能開關']],
      ['https://medium.com/netflix-techblog/towards-true-continuous-integration-distributed-repositories-and-dependencies-2a2e3108c051', 'Netflix 邁向真正的持續整合', 'Netflix 說明在大量分散式儲存庫下，如何讓相依升級與持續整合更順暢。', ['多儲存庫的相依問題', '相依版本的鎖定與升級', '以工具自動驗證相容性', '持續整合的回饋速度']],
      ['https://dropbox.tech/infrastructure/continuous-integration-and-deployment-with-bazel', 'Dropbox 以 Bazel 做持續整合與部署', 'Dropbox 以 Bazel 建置系統統一建置與測試，加快持續整合與部署。', ['可重現的建置', '增量建置與快取', '只測試受影響的部分', '部署流程']],
      ['https://medium.com/airbnb-engineering/adopting-bazel-for-web-at-scale-a784b2dbe325', 'Airbnb 在網頁前端大規模導入 Bazel', 'Airbnb 說明把網頁前端建置遷移到 Bazel 的過程與效益。', ['前端建置的效能問題', '遷移策略', '遠端快取與遠端執行', '對開發者的影響']],
      ['https://tech.buzzfeed.com/continuous-deployments-at-buzzfeed-d171f76c1ac4', 'BuzzFeed 的持續部署', 'BuzzFeed 分享建立持續部署流程的做法。', ['持續部署的流程', '部署工具', '自動化測試', '回滾機制']],
      ['https://yahooeng.tumblr.com/post/155765242061/open-sourcing-screwdriver-yahoos-continuous', 'Yahoo 的 Screwdriver：持續交付建置系統', 'Yahoo 開源的持續交付平台，為動態基礎設施而設計。', ['以程式碼定義管線', '容器化的建置環境', '擴展性', '與原始碼管理整合']],
      ['https://www.betterment.com/resources/ci-cd-shortening-the-feedback-loop/', 'Betterment：以持續整合與交付縮短回饋循環', 'Betterment 說明如何縮短從提交程式碼到上線的時間。', ['回饋循環的重要性', '平行化測試', '部署自動化', '監控與回滾']],
      ['https://medium.com/engineering-brainly/ci-cd-at-scale-fdfb0f49e031', 'Brainly 大規模的持續整合與交付', 'Brainly 分享如何把程式碼部署到上千台伺服器。', ['大規模部署的挑戰', '部署管線', '滾動更新', '監控與回滾']],
      ['https://engineering.shopify.com/blogs/engineering/scaling-ios-ci-with-anka', 'Shopify 以 Anka 擴展 iOS 持續整合', 'Shopify 以 macOS 虛擬化工具 Anka 擴展 iOS 建置機群。', ['iOS 建置必須使用 macOS 的限制', '以虛擬機器隔離建置環境', '映像檔管理', '擴展建置容量']],
      ['https://engineeringblog.yelp.com/2019/04/Scaling-Jira-Server-Administration-For-The-Enterprise.html', 'Yelp 擴展企業級 Jira 伺服器的管理', 'Yelp 說明如何管理企業級 Jira 伺服器，支撐大量團隊使用。', ['大量使用者的效能問題', '設定的標準化', '自動化管理', '升級與維運']],
      ['https://flexport.engineering/how-flexport-halved-testing-costs-with-an-auto-scaling-ci-cd-cluster-8304297222f', 'Flexport 以自動擴展的持續整合叢集把測試成本減半', 'Flexport 讓持續整合的執行環境依需求自動擴縮，降低成本並縮短等待。', ['固定容量的浪費', '依排隊工作自動擴展', '使用競價機器降低成本', '測試時間的改善']],
    ],
  },
];
