import type { UnitSource } from './types';

// 第三階：技能｜非同步與協調（訊息、事件、鎖、排程）
const group = '非同步與協調';

export const skillFlow: UnitSource[] = [
  {
    id: 's-queue',
    group,
    name: '訊息佇列與事件串流',
    question: '哪些事可以晚一點做？交給佇列之後，要保證什麼？',
    lessons: [
      ['https://arxiv.org/pdf/1704.00411.pdf', '分散式訊息代理佇列綜覽', '學術綜述，比較 Kafka 與 RabbitMQ 等訊息代理在架構、傳遞保證與效能上的差異。', ['訊息代理的角色與常見架構', '至少一次、至多一次與恰好一次的傳遞保證', 'Kafka 與 RabbitMQ 的設計差異', '吞吐量與延遲的比較']],
      ['https://quoraengineering.quora.com/Qmessage-Handling-Billions-of-Tasks-Per-Day', 'Quora 的 Qmessage：每天處理數十億個任務', 'Quora 打造的分散式非同步任務佇列，負責處理網站背後大量的延後工作。', ['為什麼需要非同步任務佇列', '任務的排程與重試', '佇列的擴展與隔離', '監控任務積壓']],
      ['https://eng.uber.com/cherami/', 'Uber 的 Cherami：非同步任務的訊息佇列', 'Uber 自建的分散式訊息佇列，用來可靠地傳遞非同步任務，重視持久性與可擴展性。', ['競爭消費者模式', '訊息的持久化與複寫', '可用性優先的設計', '延遲任務與死信佇列']],
      ['https://medium.com/airbnb-engineering/dynein-building-a-distributed-delayed-job-queueing-system-93ab10f05f99', 'Airbnb 的 Dynein：分散式延遲任務佇列', 'Airbnb 打造的延遲任務系統，讓任務能在指定時間可靠地執行。', ['延遲任務的需求：提醒、逾時處理', '以 DynamoDB 與 SQS 組成的架構', '排程準確度與擴展性', '任務至少執行一次的保證']],
      ['https://netflixtechblog.com/timestone-netflixs-high-throughput-low-latency-priority-queueing-system-with-built-in-support-1abf249ba95f', 'Netflix 的 Timestone：高吞吐低延遲的優先權佇列', 'Netflix 為媒體處理打造的優先權佇列，確保同一組不可平行的工作不會被同時執行。', ['優先權佇列的需求', '不可平行處理的工作如何排他執行', '以 Redis 為基礎的實作', '持久化與可觀測性']],
      ['http://engineering.indeedblog.com/blog/2017/06/delaying-messages/', 'Indeed 以 RabbitMQ 延遲處理非同步訊息', 'Indeed 利用 RabbitMQ 的訊息存活時間與死信交換器，實作延遲重試。', ['失敗後延遲重試的需求', '訊息存活時間與死信交換器', '多層延遲佇列', '避免重試風暴']],
      ['https://dropbox.tech/infrastructure/introducing-cape', 'Dropbox 的 Cape：事件串流處理框架', 'Dropbox 打造的低延遲事件處理框架，讓各團隊能即時回應使用者與系統事件。', ['事件驅動處理的需求', '低延遲與高可靠的取捨', '事件的順序與重試', '框架化讓各團隊共用']],
      ['https://engineering.linkedin.com/blog/2019/brooklin-open-source', 'LinkedIn 的 Brooklin：近即時資料串流服務', 'LinkedIn 開源的分散式串流服務，負責在各種資料來源與目的地之間搬移資料。', ['多種資料來源與目的地', '變更資料擷取', '取代 Kafka 叢集鏡像工具', '多租戶與擴展']],
      ['https://engineering.linkedin.com/blog/2018/04/samza-aeon--latency-insights-for-asynchronous-one-way-flows', 'LinkedIn 以 Samza 量測非同步流程的延遲', 'LinkedIn 以 Samza 串流處理追蹤非同步單向流程，量測端到端延遲。', ['非同步流程難以量測延遲', '以事件關聯計算端到端延遲', '串流處理的狀態管理', '延遲指標的應用']],
      ['https://yahooeng.tumblr.com/post/161855616651/open-sourcing-bullet-yahoos-forward-looking', 'Yahoo 的 Bullet：串流資料的前瞻查詢引擎', 'Yahoo 開源的查詢引擎，讓使用者對「即將流入」的串流資料下查詢，而不是查詢已儲存的資料。', ['前瞻查詢與傳統查詢的差別', '不儲存資料的查詢方式', '以 Storm 或 Spark 執行查詢', '適用情境：除錯與即時驗證']],
      ['https://codeascraft.com/2018/05/29/the-eventhorizon-saga/', 'Etsy 的 EventHorizon：即時觀察事件串流', 'Etsy 打造的工具，讓工程師能即時觀察網站送出的事件，方便除錯與驗證。', ['事件追蹤的除錯困難', '即時觀察事件的介面', '篩選與搜尋事件', '提升事件資料品質']],
      ['https://engineering.riotgames.com/news/riot-messaging-service', 'Riot Games 的訊息服務', 'Riot Games 打造的推播訊息服務，讓後端能即時通知數百萬名玩家的用戶端。', ['大量長連線的管理', '發布／訂閱的訊息路由', '水平擴展', '訊息可靠性']],
      ['https://dropbox.tech/infrastructure/infrastructure-messaging-system-model-async-platform-evolution', 'Dropbox 非同步平台的訊息系統模型', 'Dropbox 說明非同步工作平台的演進，以及統一的訊息系統模型。', ['非同步工作的多種型態', '統一的訊息模型', '傳遞保證與重試', '平台化的好處']],
      ['https://www.zillow.com/engineering/debugging-production-event-logging/', 'Zillow 以事件日誌為正式環境除錯', 'Zillow 以結構化的事件日誌追蹤使用者流程，加快正式環境問題的排查。', ['傳統日誌難以追蹤流程', '結構化事件', '以關聯編號串起事件', '除錯效率的改善']],
      ['https://medium.com/netflix-techblog/building-a-cross-platform-in-app-messaging-orchestration-service-86ba614f92d8', 'Netflix 的跨平台應用程式內訊息編排服務', 'Netflix 打造的服務，決定在各種裝置上何時、向誰顯示應用程式內訊息。', ['應用程式內訊息的需求', '跨裝置的一致體驗', '規則與目標對象', '訊息頻率控制']],
      ['https://medium.com/netflix-techblog/re-architecting-the-video-gatekeeper-f7b0ac2f6b00', 'Netflix 重新設計影片上架守門服務', 'Netflix 重新設計決定影片何時可以上架播放的系統，改成以事件驅動的方式更新狀態。', ['影片上架前要滿足的多個條件', '從輪詢改為事件驅動', '狀態的一致性', '降低延遲與負載']],
      ['https://www.infoq.com/presentations/neflix-push-messaging-scale', 'Netflix 擴展推播訊息到數百萬台裝置', 'Netflix 演講分享以 Zuul 打造大規模推播系統的經驗。', ['大量長連線的管理', '推播伺服器的擴展', '連線的平衡與遷移', '推播的可靠性']],
      ['https://yahooeng.tumblr.com/post/135321837876/benchmarking-streaming-computation-engines-at', 'Yahoo 的串流運算引擎基準測試', 'Yahoo 比較 Storm、Flink 與 Spark Streaming 在延遲與吞吐量上的表現。', ['基準測試的設計', '延遲與吞吐量的取捨', '微批次與逐筆處理的差異', '測試結果的解讀']],
      ['https://deliveroo.engineering/2019/02/05/improving-stream-data-quality-with-protobuf-schema-validation.html', 'Deliveroo 以 Protobuf 綱要驗證提升串流資料品質', 'Deliveroo 以 Protocol Buffers 綱要與驗證規則，確保事件串流的資料品質。', ['串流資料品質的問題', '綱要定義與版本管理', '在生產端驗證資料', '向前與向後相容規則']],
      ['https://medium.engineering/scaling-email-infrastructure-for-medium-digest-254223c883b8', 'Medium 擴展電子郵件基礎設施', 'Medium 說明每日精選電子報的發送系統，如何擴展到大量使用者。', ['大量電子郵件的產生與發送', '以佇列分散工作', '個人化內容的計算', '發送速率與送達率']],
      ['https://slack.engineering/real-time-messaging/', 'Slack 的即時訊息', 'Slack 說明訊息如何從發送者即時送到全球的用戶端，以及背後的伺服器架構。', ['頻道伺服器與閘道伺服器的分工', '以一致性雜湊分配頻道', '長連線的管理', '全球部署與延遲']],
      ['https://medium.com/nikeengineering/moving-faster-with-aws-by-creating-an-event-stream-database-dedec8ca3eeb', 'Nike 以 AWS 打造事件串流資料庫', 'Nike 以事件串流作為資料的主要紀錄，加快新服務的開發。', ['以事件作為真實來源', '事件的儲存與重播', '衍生資料的產生', '開發速度的提升']],
      ['https://medium.com/udemy-engineering/designing-the-new-event-tracking-system-at-udemy-a45e502216fd', 'Udemy 設計新的事件追蹤系統', 'Udemy 重新設計使用者行為的事件追蹤系統，改善資料品質與擴展性。', ['舊追蹤系統的問題', '事件綱要的管理', '收集與處理管線', '資料品質驗證']],
    ],
  },
  {
    id: 's-pubsub',
    group,
    name: '發布／訂閱與 Kafka',
    question: '把日誌當成系統之間的介面，會帶來什麼可能？',
    lessons: [
      ['https://aws.amazon.com/pub-sub-messaging/', '什麼是發布／訂閱訊息', 'AWS 的入門說明，介紹發布／訂閱模式如何讓服務之間非同步、解耦地溝通。', ['發布者、主題與訂閱者', '推送與拉取兩種傳遞方式', '扇出與訊息過濾', '與訊息佇列的差別']],
      ['https://yahooeng.tumblr.com/post/150078336821/open-sourcing-pulsar-pub-sub-messaging-at-scale', 'Yahoo 開源 Pulsar：大規模發布／訂閱訊息系統', 'Yahoo 開源的訊息系統，以分層架構分離服務與儲存，支援多租戶與跨區複寫。', ['服務層與儲存層分離', '以 BookKeeper 持久化訊息', '多租戶與跨區域複寫', '多種訂閱模式']],
      ['https://code.facebook.com/posts/188966771280871/wormhole-pub-sub-system-moving-data-through-space-and-time/', 'Facebook 的 Wormhole：跨越時空搬移資料', 'Facebook 讀取資料庫交易日誌並發布變更，讓快取與索引等系統即時更新。', ['從資料庫日誌擷取變更', '可靠地傳遞給訂閱者', '跨資料中心的資料搬移', '處理落後的訂閱者']],
      ['https://medium.com/pinterest-engineering/memq-an-efficient-scalable-cloud-native-pubsub-system-4402695dd4e7', 'Pinterest 的 MemQ：雲端原生的發布／訂閱系統', 'Pinterest 打造以物件儲存為基礎的發布／訂閱系統，大幅降低成本。', ['以物件儲存作為訊息持久層', '批次寫入降低成本', '與 Kafka 的比較', '適合的工作負載']],
      ['https://medium.com/netflix-techblog/how-netflix-microservices-tackle-dataset-pub-sub-4a068adcc9a', 'Netflix 微服務如何發布與訂閱資料集', 'Netflix 打造機制，讓微服務能訂閱並取得最新版本的資料集。', ['資料集分發的需求', '版本化的資料集', '推送變更通知', '讀取效能與一致性']],
      ['https://martin.kleppmann.com/papers/kafka-debull15.pdf', 'Kafka、Samza 與分散式資料的 Unix 哲學', 'Martin Kleppmann 與 Jay Kreps 說明 Kafka 與 Samza 如何把 Unix 管線的設計哲學帶進分散式資料處理。', ['Unix 管線的組合哲學', '以日誌作為系統之間的介面', '串流處理的可組合性', '重新處理與容錯']],
      ['https://engineering.linkedin.com/kafka/running-kafka-scale', 'LinkedIn 大規模執行 Kafka', 'LinkedIn 身為 Kafka 的發源地，分享如何管理每天處理上兆則訊息的叢集。', ['多叢集的分層架構', '叢集之間的鏡像複製', '監控與稽核', '容量規劃']],
      ['https://medium.com/pinterest-engineering/how-pinterest-runs-kafka-at-scale-ff9c6f735be', 'Pinterest 大規模執行 Kafka', 'Pinterest 分享 Kafka 叢集的部署方式與自動化維運工具。', ['在雲端上部署 Kafka', '自動修復失效的代理節點', '分割區的平衡', '監控指標']],
      ['https://tech.trello.com/why-we-chose-kafka/', 'Trello 為什麼選擇 Kafka', 'Trello 說明為即時同步架構選擇 Kafka 的理由，以及與其他方案的比較。', ['即時同步功能的需求', '與 RabbitMQ 等方案的比較', '訊息順序與持久化', '維運考量']],
      ['https://engineering.salesforce.com/how-apache-kafka-inspired-our-platform-events-architecture-2f351fe4cf63', 'Salesforce：Kafka 如何啟發平台事件架構', 'Salesforce 說明如何以 Kafka 的概念打造平台事件功能。', ['平台事件的需求', '以日誌為核心的設計', '多租戶的考量', '事件的保存與重播']],
      ['https://open.nytimes.com/publishing-with-apache-kafka-at-the-new-york-times-7f0e3b7d2077', '紐約時報以 Kafka 發布內容', '紐約時報把所有發布過的內容存在 Kafka，作為內容的唯一真實來源。', ['以日誌保存所有內容', '單一真實來源', '重播日誌建立新服務', '永久保存的主題']],
      ['https://engineeringblog.yelp.com/2016/07/billions-of-messages-a-day-yelps-real-time-data-pipeline.html', 'Yelp 每天數十億則訊息的即時資料管線', 'Yelp 以 Kafka 打造即時資料管線，讓各服務共享資料變更。', ['資料管線的架構', '綱要管理', '變更資料擷取', '資料的消費與轉換']],
      ['https://medium.com/criteo-labs/upgrading-kafka-on-a-large-infra-3ee99f56e970', 'Criteo 在大型基礎設施上升級 Kafka', 'Criteo 分享在大量叢集上安全升級 Kafka 的步驟與經驗。', ['升級的風險', '滾動升級流程', '協定版本的相容', '升級期間的監控']],
      ['https://shopifyengineering.myshopify.com/blogs/engineering/running-apache-kafka-on-kubernetes-at-shopify', 'Shopify 在 Kubernetes 上執行 Kafka', 'Shopify 說明把 Kafka 搬到 Kubernetes 的做法，以及有狀態服務的挑戰。', ['有狀態服務在 Kubernetes 上的挑戰', '持久化儲存', '代理節點的身分與網路', '滾動更新']],
      ['https://engineeringblog.yelp.com/2022/03/kafka-on-paasta-part-two.html', 'Yelp 在內部平台上以 Kubernetes 執行 Kafka', 'Yelp 把 Kafka 搬到以 Kubernetes 為基礎的內部平台，並自動化叢集維運。', ['以運算子管理 Kafka', '代理節點的替換', '資料的重新平衡', '維運的自動化']],
      ['https://engineeringblog.yelp.com/2019/01/migrating-kafkas-zookeeper-with-no-downtime.html', 'Yelp 零停機遷移 Kafka 的 ZooKeeper', 'Yelp 分享在不中斷 Kafka 服務的前提下，把 ZooKeeper 叢集搬到新機器。', ['ZooKeeper 在 Kafka 中的角色', '遷移的步驟', '避免腦裂', '遷移後的驗證']],
      ['https://eng.uber.com/reliable-reprocessing/', 'Uber 以 Kafka 打造可靠的重新處理與死信佇列', 'Uber 設計重試主題與死信佇列，讓處理失敗的訊息不會卡住整個消費流程。', ['失敗訊息阻塞消費的問題', '重試主題與延遲', '死信佇列的處理', '避免重試造成額外負載']],
      ['https://eng.uber.com/chaperone/', 'Uber 的 Chaperone：端到端稽核 Kafka', 'Uber 打造的稽核系統，檢查訊息在 Kafka 各個階段是否遺失或重複。', ['資料遺失難以察覺', '依時間視窗統計訊息數量', '比對各階段的計數', '即時告警']],
      ['https://dropbox.tech/infrastructure/finding-kafkas-throughput-limit-in-dropbox-infrastructure', 'Dropbox 找出 Kafka 的吞吐量極限', 'Dropbox 以系統化的負載測試，找出 Kafka 在自家基礎設施上的吞吐量上限。', ['負載測試的設計', '找出成為瓶頸的資源', '生產者與代理設定的影響', '容量規劃']],
      ['https://medium.com/walmartlabs/cost-orchestration-at-walmart-f34918af67c4', 'Walmart 的雲端成本編排', 'Walmart 以 Kafka 串流收集雲端資源用量，計算並分攤各團隊的成本。', ['雲端成本的可見性', '以串流收集用量資料', '成本的計算與分攤', '推動成本最佳化']],
      ['https://medium.com/hulu-tech-blog/how-hulu-uses-influxdb-and-kafka-to-scale-to-over-1-million-metrics-a-second-1721476aaff5', 'Hulu 以 InfluxDB 與 Kafka 擴展到每秒上百萬個指標', 'Hulu 以 Kafka 緩衝並分送指標，讓 InfluxDB 能承受大量寫入。', ['指標寫入量的挑戰', '以 Kafka 作為緩衝', '多個 InfluxDB 叢集的分流', '高可用設計']],
      ['https://medium.com/paypal-tech/scaling-kafka-to-support-paypals-data-growth-a0b4da420fab', 'PayPal 擴展 Kafka 以支撐資料成長', 'PayPal 分享大規模 Kafka 叢集的管理、監控與效能調校。', ['叢集規模與配置', '用戶端函式庫與設定管理', '監控與告警', '安全性']],
    ],
  },
  {
    id: 's-dedup',
    group,
    name: '去重複與恰好一次',
    question: '訊息一定會重送：怎麼讓結果只算一次？',
    lessons: [
      ['https://en.wikipedia.org/wiki/Data_deduplication', '資料去重複', '維基百科條目，介紹資料去重複的原理、方式與應用。', ['以雜湊辨識重複資料', '檔案層級與區塊層級去重', '寫入時與寫入後去重', '去重在備份與儲存中的應用']],
      ['https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/', 'Kafka 如何做到恰好一次語意', 'Confluent 說明 Kafka 透過冪等生產者與交易，實現串流處理中的恰好一次語意。', ['至少一次與至多一次的問題', '冪等生產者', '跨分割區的交易', '讀取已提交的隔離等級']],
      ['http://eng.tapjoy.com/blog-list/real-time-deduping-at-scale', 'Tapjoy 的即時大規模去重複', 'Tapjoy 說明如何在大量事件中即時去除重複，確保計費與統計正確。', ['重複事件的來源', '以唯一編號去重', '時間視窗與狀態保存', '記憶體與準確度的取捨']],
      ['https://segment.com/blog/exactly-once-delivery/', 'Segment 如何恰好一次地傳遞數十億則訊息', 'Segment 以 Kafka 與 RocksDB 打造去重複系統，確保訊息恰好被處理一次。', ['用戶端重送造成的重複', '以訊息編號判斷重複', '以 RocksDB 保存見過的編號', '去重視窗的大小']],
      ['https://medium.com/@andrewsumin/efficient-storage-how-we-went-down-from-50-pb-to-32-pb-99f9c61bf6b4', 'Mail.Ru 以去重複把儲存從 50PB 降到 32PB', 'Mail.Ru 為雲端儲存導入去重複機制，大幅節省儲存空間。', ['使用者重複上傳的檔案', '以內容雜湊辨識重複', '參照計數與刪除', '節省空間的效果']],
      ['https://medium.com/mixpaneleng/petabyte-scale-data-deduplication-mixpanel-engineering-e808c70c99f8', 'Mixpanel 的 PB 級資料去重複', 'Mixpanel 說明如何在 PB 級的事件資料中去除重複事件。', ['重複事件對分析的影響', '在查詢時與壓實時去重', '以事件編號判斷重複', '效能與正確性的平衡']],
    ],
  },
  {
    id: 's-events',
    group,
    name: '事件驅動與領域驅動設計',
    question: '以「發生了什麼事」來建模，系統會長成什麼樣子？',
    lessons: [
      ['https://martinfowler.com/articles/201701-event-driven.html', '「事件驅動」到底是什麼意思', 'Martin Fowler 釐清常被混為一談的四種事件驅動模式。', ['事件通知', '攜帶狀態轉移的事件', '事件溯源', '命令查詢職責分離']],
      ['https://medium.com/swlh/creating-coding-excellence-with-domain-driven-design-88f73d2232c3', '阿里巴巴的領域驅動設計實踐', '阿里巴巴工程師說明如何以領域驅動設計整理複雜的業務邏輯。', ['領域模型與貧血模型的差別', '限界上下文的劃分', '聚合與實體', '分層架構']],
      ['https://medium.com/weebly-engineering/how-to-organize-your-monolith-before-breaking-it-into-services-69cbdb9248b0', 'Weebly：拆服務之前先整理好單體', 'Weebly 說明在拆成微服務之前，如何先用領域驅動設計整理單體程式碼。', ['直接拆服務的風險', '在單體內劃分模組邊界', '以領域驅動設計找出邊界', '逐步抽離服務']],
      ['https://engineering.moonpig.com/development/modelling-for-domain-driven-design', 'Moonpig 的領域驅動設計建模', 'Moonpig 分享以領域驅動設計為業務建模的過程與心得。', ['與領域專家共同建模', '通用語言', '限界上下文', '模型的持續演進']],
      ['https://www.infoq.com/presentations/netflix-scale-event-sourcing', 'Netflix 下載功能的事件溯源擴展', 'Netflix 演講分享以事件溯源打造下載授權服務的經驗。', ['下載授權的業務規則', '以事件記錄狀態變化', '快照與重播', '擴展與效能']],
      ['https://medium.com/@eulerfx/scaling-event-sourcing-at-jet-9c873cac33b8', 'Jet.com 擴展事件溯源', 'Jet.com 分享在電商系統中大規模使用事件溯源的做法與挑戰。', ['事件儲存的選擇', '事件串流的分割', '投影的建立與重建', '一致性與並行控制']],
      ['https://www.ebayinc.com/stories/blogs/tech/event-sourcing-in-action-with-ebays-continuous-delivery-team/', 'eBay 持續交付團隊的事件溯源實踐', 'eBay 以事件溯源重新設計持續交付系統，記錄每一次變更。', ['以事件記錄系統狀態', '投影與查詢模型', '事件版本管理', '除錯與稽核的好處']],
      ['https://medium.com/inside-freenow/event-sourcing-an-evolutionary-perspective-31e7387aa6f1', 'FREE NOW 的事件溯源：演進的觀點', 'FREE NOW 分享事件溯源在系統演進中的角色與經驗。', ['導入事件溯源的動機', '事件結構的演進', '重播與投影', '遇到的困難']],
      ['https://medium.com/engineering-brainly/scalable-content-feed-using-event-sourcing-and-cqrs-patterns-e09df98bf977', 'Brainly 以事件溯源與讀寫分離打造內容動態', 'Brainly 以事件溯源與命令查詢職責分離，建立可擴展的內容動態服務。', ['讀寫模型分離的好處', '以事件更新讀取模型', '動態消息的擴展', '最終一致性的處理']],
    ],
  },
  {
    id: 's-lock',
    group,
    name: '分散式鎖與協調',
    question: '兩台機器同時想改同一筆資料時，誰說了算？',
    lessons: [
      ['https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html', '如何做分散式鎖', 'Martin Kleppmann 分析 Redis 的 Redlock 演算法，說明為什麼分散式鎖需要防護權杖。', ['為了效率與為了正確性而用鎖的差別', '行程暫停與網路延遲會讓租約失效', '防護權杖：用遞增編號擋住過期的持有者', '依賴時間假設為什麼危險']],
      ['https://blog.acolyer.org/2015/02/13/the-chubby-lock-service-for-loosely-coupled-distributed-systems/', 'Google 的 Chubby 鎖服務', '論文導讀：Google 為鬆散耦合的分散式系統設計的粗粒度鎖服務，也兼作小型設定儲存。', ['粗粒度鎖與細粒度鎖', '以 Paxos 維持一致', '以類似檔案系統的介面提供鎖與設定', '用戶端快取與租約']],
      ['https://www.youtube.com/watch?v=MDuagr729aU', 'Uber 的分散式鎖', 'Uber 演講分享在大規模服務中使用分散式鎖的經驗與陷阱。', ['需要分散式鎖的情境', '鎖服務的選擇', '鎖逾時與失效', '避免過度依賴鎖']],
      ['https://engineering.gosquared.com/distributed-locks-using-redis', 'GoSquared 以 Redis 實作分散式鎖', 'GoSquared 分享使用 Redis 實作分散式鎖的方法與注意事項。', ['以 SET NX 搭配存活時間取得鎖', '只由持有者釋放鎖', '鎖逾時的設定', 'Redis 故障時的風險']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2018/zookeeper-at-twitter.html', 'Twitter 的 ZooKeeper', 'Twitter 分享大規模使用 ZooKeeper 做協調服務的經驗與改進。', ['ZooKeeper 在服務協調中的角色', '大量用戶端連線的挑戰', '觀察者節點與讀取擴展', '維運與監控']],
      ['https://chartio.com/blog/eliminating-duplicate-queries-using-distributed-locking/', 'Chartio 以分散式鎖消除重複查詢', 'Chartio 以分散式鎖避免多個使用者同時觸發相同的昂貴查詢。', ['重複查詢對資料庫的壓力', '以查詢內容作為鎖的鍵', '等待結果而不是重複執行', '鎖逾時的處理']],
    ],
  },
  {
    id: 's-schedule',
    group,
    name: '分散式排程與工作流程',
    question: '成千上萬個定時工作與相依任務，要怎麼排得不漏也不重？',
    lessons: [
      ['https://www.csee.umbc.edu/courses/graduate/CMSC621/fall02/lectures/ch11.pdf', '分散式排程', '大學課程講義，介紹分散式系統中的工作分配與負載分享演算法。', ['負載分享與負載平衡的差別', '工作遷移的時機', '由傳送端啟動與由接收端啟動的演算法', '排程的穩定性']],
      ['https://www.pagerduty.com/eng/distributed-task-scheduling-3/', 'PagerDuty 的分散式任務排程', 'PagerDuty 的系列文章，說明如何以 Kafka 與 Cassandra 打造可靠的分散式任務排程器。', ['排程器的可靠性需求', '以 Kafka 分割任務', '以 Cassandra 保存排程', '故障時任務的轉移']],
      ['https://landing.google.com/sre/sre-book/chapters/distributed-periodic-scheduling/', 'Google 打造分散式定時排程服務', '《Google 網站可靠性工程》的章節，說明如何打造可靠的分散式定時排程服務。', ['單機定時排程的不足', '以 Paxos 保存排程狀態', '避免任務重複或遺漏', '大量任務同時觸發的問題']],
      ['https://quoraengineering.quora.com/Quoras-Distributed-Cron-Architecture', 'Quora 的分散式定時排程架構', 'Quora 說明如何把定時工作從單機搬到分散式架構，提升可靠性。', ['單機定時工作的單點故障', '任務的分派與執行', '失敗重試與告警', '任務的可觀測性']],
      ['https://medium.com/airbnb-engineering/chronos-a-replacement-for-cron-f05d7d986a9d', 'Airbnb 的 Chronos：取代傳統定時排程', 'Airbnb 開源在 Mesos 上執行的容錯排程器，用來取代傳統的定時排程。', ['傳統定時排程的限制', '在 Mesos 上執行任務', '任務相依關係', '容錯與重試']],
      ['https://engblog.nextdoor.com/we-don-t-run-cron-jobs-at-nextdoor-6f7f9cc62040', 'Nextdoor 不用定時排程工具', 'Nextdoor 說明為什麼不用傳統定時排程，而是改用自建的排程方式。', ['定時排程的維運問題', '以佇列觸發排程任務', '任務的可觀測性', '故障恢復']],
      ['https://eng.uber.com/peloton/', 'Uber 的 Peloton：統一的資源排程器', 'Uber 打造的叢集排程器，統一管理批次、串流與線上服務等不同工作負載。', ['多種工作負載共用叢集', '資源配額與搶占', '大規模批次工作的排程', '提升叢集使用率']],
      ['https://medium.com/netflix-techblog/fenzo-oss-scheduler-for-apache-mesos-frameworks-5c340e77e543', 'Netflix 的 Fenzo：Mesos 的開源排程器', 'Netflix 開源的排程函式庫，依資源與限制條件把任務配置到合適的機器。', ['排程的限制條件與適配度', '資源裝箱以提升使用率', '自動擴縮叢集', '排程決策的可擴展性']],
      ['https://airflow.apache.org/', 'Apache Airflow：工作流程編排平台', 'Airflow 官方網站，這是以程式碼定義、排程與監控工作流程的開源平台。', ['以有向無環圖定義工作流程', '排程與相依管理', '重試與回填', '監控介面']],
      ['https://medium.com/airbnb-engineering/airflow-a-workflow-management-platform-46318b977fd8', 'Airbnb 的 Airflow：工作流程管理平台', 'Airflow 的誕生文章，Airbnb 說明為何打造這套以程式碼定義工作流程的平台。', ['資料管線的相依複雜度', '以程式碼定義工作流程', '排程與回填', '視覺化與監控']],
      ['https://www.adyen.com/knowledge-hub/apache-airflow-at-adyen', 'Adyen 的 Apache Airflow', 'Adyen 分享在支付公司中使用 Airflow 管理資料管線的經驗。', ['資料管線的管理需求', '部署與擴展', '安全性考量', '維運經驗']],
      ['https://engineering.pandora.com/apache-airflow-at-pandora-1d7a844d68ee', 'Pandora 的 Apache Airflow', 'Pandora 分享以 Airflow 管理巨量資料管線的做法。', ['巨量資料管線的挑戰', '工作流程的組織', '監控與告警', '遇到的問題']],
      ['https://medium.com/robinhood-engineering/why-robinhood-uses-airflow-aed13a9a90c8', 'Robinhood 為什麼使用 Airflow', 'Robinhood 說明選擇 Airflow 的理由，以及在金融資料管線中的應用。', ['選擇工作流程工具的考量', '資料管線的相依', '任務重試與告警', '擴展方式']],
      ['https://eng.lyft.com/running-apache-airflow-at-lyft-6e53bb8fccff', 'Lyft 執行 Apache Airflow', 'Lyft 分享在大規模資料平台中執行 Airflow 的架構與改進。', ['大量工作流程的管理', '排程器的效能', '監控指標', '對開源專案的改進']],
      ['https://drivy.engineering/airflow-architecture/', 'Drivy 的 Airflow 架構', 'Drivy 分享以 Airflow 管理資料管線的架構設計。', ['工作流程的組織方式', '部署架構', '監控與告警', '導入經驗']],
      ['https://engineering.grab.com/experimentation-platform-data-pipeline', 'Grab 以 Airflow 打造實驗平台的資料管線', 'Grab 說明實驗平台的資料管線如何以 Airflow 編排。', ['實驗平台的資料需求', '工作流程設計', '資料品質檢查', '擴展方式']],
      ['https://medium.com/adobetech/adobe-experience-platform-orchestration-service-with-apache-airflow-952203723c0b', 'Adobe 以 Airflow 打造編排服務', 'Adobe 以 Airflow 為基礎，為自家平台打造多租戶的工作流程編排服務。', ['多租戶編排的需求', '以 Airflow 為核心的服務化', '擴展與隔離', '維運方式']],
      ['https://medium.com/walmartlabs/auditing-airflow-batch-jobs-73b45100045', 'Walmart 稽核 Airflow 批次工作', 'Walmart 建立稽核機制，追蹤 Airflow 批次工作的執行狀況。', ['批次工作的可見性', '執行紀錄的收集', '異常偵測', '稽核報表']],
      ['https://hackernoon.com/meet-maat-alibabas-dag-based-distributed-task-scheduler-7c9cf0c83438', '阿里巴巴的 MaaT：以有向無環圖為基礎的任務排程器', '阿里巴巴打造的分散式任務排程器，以有向無環圖描述任務之間的相依關係。', ['任務相依的描述方式', '分散式排程的架構', '任務的容錯', '大規模任務的效能']],
      ['https://www.etsy.com/codeascraft/boundary-layer-declarative-airflow-workflows', 'Etsy 的 boundary-layer：宣告式 Airflow 工作流程', 'Etsy 開源的工具，讓工程師用設定檔宣告工作流程，再自動產生 Airflow 程式碼。', ['以設定檔描述工作流程', '自動產生 Airflow 程式碼', '驗證與重用', '降低撰寫門檻']],
    ],
  },
];
