import type { UnitSource } from './types';

// 第四階：智慧｜判斷整個系統與團隊
export const wisdom: UnitSource[] = [
  {
    id: 'w-simple',
    group: '判斷',
    name: '知道什麼不要做',
    question: '在「能做」與「該做」之間，你怎麼選？',
    lessons: [
      ['https://medium.com/@rdsubhas/10-modern-software-engineering-mistakes-bc67fbef4fc8', '避免過度設計：十個現代軟體工程錯誤', '整理十個常見的過度設計錯誤，例如過早抽象、過度泛化，以及為了未來而寫程式。', ['過早抽象的代價', '為「將來可能需要」寫的程式', '共用程式碼造成的耦合', '過度熱衷新技術']],
      ['https://www.infoq.com/articles/scalability-worst-practices', '擴展性的最差實務', '整理大型系統中常見的擴展錯誤，從萬用錘子到缺乏監控。', ['萬用錘子：用同一種技術解決所有問題', '濫用共享資源', '呼叫外部服務沒有設定逾時', '依賴英雄而不是自動化', '缺乏監控']],
      ['https://medium.com/@DataStax/instagram-engineerings-3-rules-to-a-scalable-cloud-application-architecture-c44afed31406', 'Instagram 擴展雲端架構的三條規則', 'Instagram 分享三條擴展原則：使用成熟技術、不重新發明輪子、保持簡單。', ['使用經過驗證的成熟技術', '不要重新發明輪子', '保持簡單', '用簡單的架構支撐快速成長']],
      ['https://engineering.zalando.com/posts/2018/01/simplicity-by-distributing-complexity.html', 'Zalando：以分散複雜度換取簡單', 'Zalando 說明如何把複雜度分散到小而清楚的元件，讓整體保持簡單。', ['複雜度無法消滅，只能轉移', '小而專注的元件', '清楚的介面與邊界', '自治團隊與負責範圍']],
      ['http://tech.transferwise.com/why-over-reusing-is-bad/', '過度重用為什麼不好', 'TransferWise 說明過度追求程式碼重用會造成不必要的耦合，讓修改變得困難。', ['重用與耦合的關係', '共用函式庫帶來的連動變更', '適度重複勝過錯誤的抽象', '何時才值得抽出共用元件']],
      ['https://architecht.io/lessons-from-facebook-on-engineering-for-scale-f5716f0afc7a', '自動化與抽象：Facebook 的擴展經驗', 'Facebook 工程師分享以自動化與抽象層支撐快速成長的心得。', ['用自動化取代重複的人工作業', '以抽象層隱藏基礎設施的複雜度', '讓工程師專注在產品', '工具化的文化']],
      ['https://8thlight.com/blog/sarah-sunday/2017/09/15/aws-dos-and-donts.html', '使用 AWS 的該做與不該做', '8th Light 整理使用 AWS 時的實務建議與常見錯誤。', ['以程式碼管理基礎設施', '權限與帳號的管理', '成本的監控', '避免手動修改正式環境']],
      ['https://medium.com/@hellostanley/design-doesnt-scale-4d81e12cbc3e', '設計無法擴展', 'Spotify 設計總監 Stanley Wood 說明設計團隊擴大後的一致性問題，以及設計系統的角色。', ['團隊擴大造成的設計不一致', '設計原則與共同語言', '設計系統的建立', '擴展的是協作方式，而不是產出']],
      ['http://highscalability.com/blog/2013/8/26/reddit-lessons-learned-from-mistakes-made-scaling-to-1-billi.html', 'Reddit 擴展到十億瀏覽量時犯過的錯', 'Reddit 共同創辦人分享擴展過程中的錯誤與教訓。', ['為故障做好準備並盡早自動化', '用佇列處理耗時工作', '對未登入的使用者大量使用快取', '簡單勝過聰明']],
    ],
  },
  {
    id: 'w-stack',
    group: '整體架構',
    name: '技術堆疊與後端演進',
    question: '一家公司的整套系統，是怎麼一步步長成今天的樣子？',
    lessons: [
      ['https://medium.engineering/the-stack-that-helped-medium-drive-2-6-millennia-of-reading-time-e56801f7c492', 'Medium 的技術堆疊', 'Medium 介紹支撐平台的完整技術堆疊，從前端、後端到資料與維運。', ['以 Node.js 為主的服務', '資料儲存的選擇', '非同步處理與佇列', '部署與監控']],
      ['https://engineering.shopify.com/blogs/engineering/e-commerce-at-scale-inside-shopifys-tech-stack', 'Shopify 的技術堆疊：大規模電商', 'Shopify 介紹支撐大量商店的技術堆疊與架構。', ['以 Ruby on Rails 為核心的單體', '以分區隔離商店資料', '前端與行動技術', '基礎設施與維運']],
      ['https://medium.com/airbnb-engineering/building-services-at-airbnb-part-4-23c95e428064', 'Airbnb 打造服務的系列文章', 'Airbnb 的四篇系列文章，說明服務化時的框架、標準與可靠性做法。', ['服務框架與程式碼產生', '服務之間的介面定義', '可靠性與逾時', '服務的測試與部署']],
      ['https://evernote.com/blog/a-digest-of-evernotes-architecture/', 'Evernote 的架構', 'Evernote 介紹以分片為基礎的後端架構，每個分片負責一群使用者。', ['以使用者分片的架構', '分片內的服務組成', '資料儲存與備份', '擴展方式']],
      ['https://engineering.linkedin.com/architecture/brief-history-scaling-linkedin', 'LinkedIn 擴展簡史', 'LinkedIn 回顧從單體應用程式到服務導向架構、Kafka 與多資料中心的擴展歷程。', ['從單體到服務導向架構', '拆出會員關係圖與搜尋服務', '以 Kafka 統一資料流', '多資料中心部署']],
      ['https://yahooeng.tumblr.com/post/157200523046/introducing-tripod-flickrs-backend-refactored', 'Flickr 重構後端：Tripod', 'Flickr 說明重構後端資料存取層的原因與設計。', ['舊後端的問題', '資料存取層的抽象', '快取與一致性', '逐步遷移']],
      ['https://medium.com/zendesk-engineering/the-history-of-infrastructure-at-zendesk-part-3-foundation-team-forming-and-evolving-9859e40f5390', 'Zendesk 基礎設施的歷史', 'Zendesk 回顧基礎設施與基礎團隊的演進歷程。', ['基礎設施的演進階段', '基礎團隊的成立', '平台化的過程', '組織與技術的互動']],
      ['https://bytes.grubhub.com/cloud-infrastructure-at-grubhub-94db998a898a', 'Grubhub 的雲端基礎設施', 'Grubhub 說明遷移到雲端後的基礎設施架構。', ['雲端遷移的動機', '服務的部署方式', '多區域與高可用', '維運自動化']],
      ['https://medium.com/@palantir/terraforming-stack-overflow-enterprise-in-aws-47ee431e6be7', 'Palantir 以 Terraform 在 AWS 上部署問答平台', 'Palantir 分享以基礎設施即程式碼，在 AWS 上部署 Stack Overflow 企業版的經驗。', ['基礎設施即程式碼', '以 Terraform 描述雲端資源', '部署的可重現性', '維運與升級']],
      ['https://netflixtechblog.com/ready-for-changes-with-hexagonal-architecture-b315ec967749', 'Netflix 以六角架構為變化做好準備', 'Netflix 以六角架構隔離業務邏輯與資料來源，讓更換資料來源變得容易。', ['六角架構的核心概念', '埠與轉接器', '隔離業務邏輯與外部依賴', '更換資料來源的彈性']],
    ],
  },
  {
    id: 'w-platform',
    group: '整體架構',
    name: '平台、閘道與核心服務',
    question: '哪些能力值得做成平台，讓所有團隊共用？',
    lessons: [
      ['https://eng.uber.com/architecture-api-gateway/', 'Uber API 閘道的架構', 'Uber 說明 API 閘道的演進與架構，負責路由、驗證與協定轉換。', ['API 閘道的職責', '以設定驅動的端點管理', '協定轉換', '閘道的擴展與可靠性']],
      ['https://medium.com/tinder/how-we-built-the-tinder-api-gateway-831c6ca5ceca', 'Tinder 如何打造 API 閘道', 'Tinder 以 Spring Cloud Gateway 打造自家的 API 閘道。', ['自建閘道的動機', '以設定驅動的路由', '過濾器與身分驗證', '部署與效能']],
      ['https://engineering.riotgames.com/news/riot-games-api-deep-dive', 'Riot Games API 平台深入解析', 'Riot Games 說明對外開放遊戲資料的 API 平台架構。', ['對外 API 的需求', '限流與金鑰管理', '代理與快取', '平台的擴展']],
      ['https://engineering.wework.com/our-api-specification-workflow-9337448d6ee6', 'WeWork 的 API 規格工作流程', 'WeWork 說明以 API 規格文件驅動開發的流程與工具。', ['規格優先的開發流程', 'API 規格格式的選擇', '文件與模擬伺服器', '規格的審查']],
      ['https://engineering.linkedin.com/blog/2019/05/building-member-trust-through-a-centralized-and-scalable-setting', 'LinkedIn 的集中式設定平台', 'LinkedIn 以集中且可擴展的設定平台管理會員的各項設定，建立信任。', ['分散設定造成的不一致', '集中式設定服務', '設定的讀取效能', '隱私與信任']],
      ['https://engineering.linkedin.com/blog/2018/01/now-you-see-me--now-you-dont--linkedins-real-time-presence-platf', 'LinkedIn 的即時上線狀態平台', 'LinkedIn 打造即時顯示會員是否在線的平台，處理大量心跳與狀態變化。', ['上線狀態的即時性需求', '心跳與逾時判斷', '狀態變化的推播', '大量連線的擴展']],
      ['https://bytes.swiggy.com/kabootar-swiggys-communication-platform-e5a43cc25629', 'Swiggy 的 Kabootar：通訊平台', 'Swiggy 打造統一的通訊平台，負責簡訊、推播與電子郵件的發送。', ['多種通訊管道的整合', '範本與個人化', '發送的優先順序與速率', '送達率的追蹤']],
      ['https://netflixtechblog.com/rapid-event-notification-system-at-netflix-6deb1d2b57d1', 'Netflix 的即時事件通知系統', 'Netflix 打造事件通知系統，把使用者的操作即時同步到其他裝置與服務。', ['跨裝置同步的需求', '事件的優先順序', '推播與拉取的混合', '系統的擴展']],
      ['https://tech.ebayinc.com/engineering/a-lightweight-distributed-architecture-to-handle-thousands-of-library-releases-at-ebay/', 'eBay 處理數千個函式庫發布的輕量分散式架構', 'eBay 以輕量的分散式架構處理大量內部函式庫的發布流程。', ['函式庫發布的規模', '工作的分派與執行', '狀態追蹤', '系統的簡化']],
      ['https://medium.com/netflix-techblog/implementing-the-netflix-media-database-53b5a840b42a', 'Netflix 媒體資料庫的實作', 'Netflix 打造媒體資料庫，儲存並查詢影片、音訊與字幕的技術中繼資料。', ['媒體中繼資料的需求', '時間軸資料的儲存', '查詢與索引', '擴展方式']],
      ['https://medium.com/walmartlabs/member-transaction-history-architecture-8b6e34b87c21', 'Walmart 會員交易紀錄架構', 'Walmart 說明會員交易紀錄服務的架構，提供快速的歷史查詢。', ['交易紀錄的讀寫特性', '資料模型設計', '查詢效能', '資料保存']],
      ['https://dropbox.tech/infrastructure/-testing-our-new-sync-engine', 'Dropbox 測試新的同步引擎', 'Dropbox 說明重寫檔案同步引擎後，如何以隨機化測試確保正確性。', ['同步引擎的正確性需求', '可重現的隨機化測試', '模擬各種故障與競態', '測試對重寫的幫助']],
      ['https://medium.com/glassdoor-engineering/building-a-nearline-system-for-scale-and-performance-part-ii-9e01bf51b23d', 'Glassdoor 打造近線系統兼顧規模與效能', 'Glassdoor 介於即時與批次之間的近線處理系統，用於更新推薦與索引。', ['即時、近線與批次處理的差別', '事件驅動的更新', '處理延遲與成本', '系統架構']],
    ],
  },
  {
    id: 'w-product',
    group: '整體架構',
    name: '產品系統案例',
    question: '把前面學到的元件組起來，一個真實產品長什麼樣子？',
    lessons: [
      ['https://engineering.riotgames.com/news/chat-service-architecture-persistence', 'Riot Games 聊天服務的架構', 'Riot Games 的三篇系列文章，說明遊戲聊天服務的伺服器、持久化與擴展。', ['以 XMPP 為基礎的聊天服務', '伺服器架構', '訊息的持久化', '大量同時上線的擴展']],
      ['https://technology.riotgames.com/news/architecture-league-client-update', '《英雄聯盟》用戶端更新的架構', 'Riot Games 說明重新打造遊戲用戶端的架構設計。', ['舊用戶端的限制', '以網頁技術打造介面', '外掛化的架構', '更新與相容性']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2020/building-twitters-ad-platform-architecture-for-the-future.html', 'Twitter 為未來打造的廣告平台架構', 'Twitter 重新設計廣告平台架構，提升開發效率與可靠性。', ['舊廣告系統的問題', '平台化的架構', '廣告投放流程', '開發效率的提升']],
      ['https://blog.twitter.com/engineering/en_us/topics/infrastructure/2021/how-we-built-twitter-s-highly-reliable-ads-pacing-service', 'Twitter 打造高可靠的廣告預算控速服務', 'Twitter 說明控制廣告預算花費速度的服務，如何做到高可靠。', ['廣告預算控速的需求', '即時花費的計算', '分散式狀態的一致性', '可靠性設計']],
      ['https://medium.com/@Pinterest_Engineering/building-a-real-time-user-action-counting-system-for-ads-88a60d9c9a', 'Pinterest 打造廣告的即時使用者行為計數系統', 'Pinterest 即時計算使用者對廣告的行為次數，用於頻率控制與預算。', ['即時計數的需求', '以串流處理計數', '時間視窗與過期', '查詢效能']],
      ['https://medium.com/@Pinterest_Engineering/building-a-dynamic-and-responsive-pinterest-7d410e99f0a9', 'Pinterest 的追蹤動態、興趣動態與精選推薦架構', 'Pinterest 說明多種動態消息的產生架構。', ['推送式與拉取式動態', '候選產生與排序', '即時更新', '大量使用者的擴展']],
      ['https://www.slideshare.net/linecorp/architecture-sustaining-line-sticker-services', '支撐 LINE 貼圖服務的架構', 'LINE 分享貼圖商店與傳送服務背後的架構。', ['貼圖的傳送與下載', '內容傳遞網路', '購買與授權', '流量尖峰的處理']],
      ['https://open.nytimes.com/play-by-play-moving-the-nyt-games-platform-to-gcp-with-zero-downtime-cf425898d569', '紐約時報零停機把遊戲平台搬到 Google 雲端', '紐約時報說明遊戲平台零停機遷移的每一個步驟。', ['遷移的規劃', '資料同步', '流量切換', '零停機的驗證']],
      ['https://slack.engineering/how-slack-built-shared-channels-8d42c895b19f', 'Slack 如何打造共享頻道', 'Slack 說明讓不同公司共用頻道的架構設計，以及對原本架構的影響。', ['原本以工作區分片的架構', '跨工作區的資料存取', '權限與資料擁有權', '架構的調整']],
      ['https://medium.com/netflix-techblog/https-medium-com-netflix-techblog-simone-a-distributed-simulation-service-b2c85131ca1b', 'Netflix 的 Simone：分散式模擬服務', 'Netflix 打造模擬服務，產生各種裝置與播放情境，用於測試。', ['裝置與情境的多樣性', '模擬的設定', '分散式執行', '測試效率']],
      ['https://engineeringblog.yelp.com/2017/04/how-yelp-runs-millions-of-tests-every-day.html', 'Yelp 的 Seagull：每天執行數千萬個測試', 'Yelp 打造分散式測試系統，把大量測試分散到多台機器平行執行。', ['測試時間過長的問題', '測試的分割與排程', '以競價機器降低成本', '結果的彙整']],
      ['https://medium.com/agoda-engineering/priceaggregator-an-intelligent-system-for-hotel-price-fetching-part-3-52acfc705081', 'Agoda 的 PriceAggregator：智慧的旅館價格擷取系統', 'Agoda 說明如何聰明地向供應商擷取旅館價格，兼顧新鮮度與成本。', ['價格擷取的成本', '快取與新鮮度的取捨', '決定何時重新擷取', '系統架構']],
      ['https://medium.com/tinder-engineering/phoenix-tinders-testing-platform-part-iii-520728b9537', 'Tinder 的 Phoenix：測試平台', 'Tinder 的三篇系列文章，說明實驗與功能測試平台的設計。', ['實驗平台的需求', '使用者分組', '功能開關', '結果分析']],
    ],
  },
  {
    id: 'w-payment',
    group: '整體架構',
    name: '金融與支付系統',
    question: '錢不能算錯一分：正確性要怎麼設計進架構裡？',
    lessons: [
      ['https://www.redhat.com/architect/portfolio/detail/12-integrating-a-modern-payments-architecture', '整合現代支付架構', 'Red Hat 的參考架構，說明現代支付系統的組成與整合方式。', ['支付系統的組成元件', '事件驅動的整合', '即時支付的需求', '可靠性與稽核']],
      ['https://monzo.com/blog/2016/09/19/building-a-modern-bank-backend/', 'Monzo 打造現代銀行後端', 'Monzo 說明從零打造銀行後端的架構，以微服務與雲端為基礎。', ['以微服務打造銀行系統', '分散式資料儲存', '高可用的要求', '監理與資安']],
      ['https://medium.com/@Wealthsimple/engineering-at-wealthsimple-reinventing-our-trading-platform-for-scale-17e332241b6c', 'Wealthsimple 重新打造可擴展的交易平台', 'Wealthsimple 說明為了擴展而重新設計交易平台的過程。', ['舊平台的瓶頸', '交易流程的重新設計', '可靠性與正確性', '遷移策略']],
      ['https://medium.com/margobank/choosing-an-architecture-85750e1e5a03', 'Margo Bank 選擇核心銀行系統架構', 'Margo Bank 說明選擇核心銀行系統架構時的考量。', ['核心銀行系統的需求', '架構選項的比較', '事件溯源的考量', '決策過程']],
      ['https://www.infoq.com/presentations/nubank-architecture', 'Nubank 的架構', 'Nubank 演講分享以 Clojure、Datomic 與 Kafka 打造的金融科技架構。', ['不可變資料與 Datomic', '以 Kafka 串起服務', '分片與擴展', '函數式程式設計的應用']],
      ['http://tech.transferwise.com/the-transferwise-stack-heartbeat-of-our-little-revolution/', 'TransferWise 的技術堆疊', 'TransferWise 介紹支撐跨國匯款服務的技術堆疊。', ['後端語言與框架', '資料儲存', '服務架構', '工程文化']],
      ['https://medium.com/build-addepar/our-tech-stack-a4f55dab4b0d', 'Addepar 的技術堆疊', 'Addepar 介紹財富管理平台的技術堆疊。', ['後端與資料處理', '金融計算的正確性', '前端技術', '基礎設施']],
      ['https://medium.com/airbnb-engineering/avoiding-double-payments-in-a-distributed-payments-system-2981f6b070bb', 'Airbnb 在分散式支付系統中避免重複扣款', 'Airbnb 打造冪等性框架，確保支付請求重試時不會重複扣款。', ['分散式支付的重複扣款風險', '冪等鍵的設計', '把請求拆成前置、執行與後置階段', '重試與錯誤分類']],
      ['https://www.etsy.com/sg-en/codeascraft/scaling-etsy-payments-with-vitess-part-3--reducing-cutover-risk', 'Etsy 以 Vitess 擴展支付系統', 'Etsy 的三篇系列文章，說明把支付資料庫遷移到 Vitess 分片，並降低切換風險。', ['支付資料庫的擴展需求', '以 Vitess 分片', '資料遷移與驗證', '降低切換風險的做法']],
      ['https://paytm.com/blog/engineering/how-paytm-handles-millions-of-digital-transactions-safely-everyday/', 'Paytm 每天安全處理數百萬筆數位交易', 'Paytm 說明支付系統如何兼顧安全、可靠與擴展。', ['大量交易的處理', '交易的一致性', '風險控管', '可用性設計']],
      ['https://www.grammarly.com/blog/engineering/billing-and-payments-platform/', 'Grammarly 的帳務與支付平台', 'Grammarly 說明重新打造帳務與支付平台的架構。', ['訂閱帳務的複雜度', '支付供應商的整合', '帳務事件與對帳', '平台的彈性']],
    ],
  },
  {
    id: 'w-interview',
    group: '表達',
    name: '面試：把知識說成設計',
    question: '四十五分鐘內，你能把一個系統從零講到取捨嗎？',
    lessons: [
      ['https://hackernoon.com/anatomy-of-a-system-design-interview-4cb57d75a53f', '系統設計面試的剖析', '拆解系統設計面試的流程，說明面試官在每個階段想看到什麼。', ['釐清需求與限制', '估算規模', '提出高階設計', '深入關鍵元件並討論取捨']],
      ['http://blog.gainlo.co/index.php/2015/10/22/8-things-you-need-to-know-before-system-design-interviews/', '系統設計面試前該知道的八件事', '整理準備系統設計面試時的八個重點觀念。', ['面試沒有標準答案', '由上而下的設計方式', '主動釐清需求', '說明取捨，而不是背誦技術']],
      ['https://hackernoon.com/top-10-system-design-interview-questions-for-software-engineers-8561290f0444', '十大系統設計面試題', '整理十道常見的系統設計面試題，例如短網址、聊天系統與動態消息。', ['設計短網址服務', '設計聊天系統', '設計動態消息', '設計網路爬蟲', '設計叫車系統']],
      ['https://hackernoon.com/how-not-to-design-netflix-in-your-45-minute-system-design-interview-64953391a054', '別在四十五分鐘的面試裡這樣設計 Netflix', '以反例說明系統設計面試常見的錯誤，例如一開始就陷入細節。', ['一開始就深入細節', '沒有釐清需求', '忽略規模估算', '沒有說明取捨']],
      ['https://www.glassdoor.com/Interview/What-happens-when-you-type-www-google-com-in-your-browser-QTN_56396.htm', '在瀏覽器輸入網址後會發生什麼事', '經典面試題：從按下 Enter 到頁面出現，中間經過了哪些網路與系統環節。', ['DNS 解析', '建立 TCP 與加密連線', 'HTTP 請求與伺服器處理', '瀏覽器解析與渲染']],
      ['http://highscalability.com/blog/2017/12/11/netflix-what-happens-when-you-press-play.html', 'Netflix：按下播放鍵之後發生了什麼事', '從使用者按下播放鍵開始，追蹤 Netflix 在雲端與內容傳遞網路中完成的一連串工作。', ['控制平面在 AWS，資料平面在 Open Connect', '影片的轉碼與多種版本', '播放授權與挑選伺服器', '自適應串流']],
      ['https://monzo.com/blog/2018/04/05/how-monzo-to-monzo-payments-work/', 'Monzo：點對點轉帳是怎麼運作的', 'Monzo 說明一筆轉帳在系統中經過的每一個服務與步驟。', ['轉帳請求的處理流程', '帳本與餘額的更新', '服務之間的非同步事件', '一致性與冪等性']],
      ['https://githubengineering.com/transit-and-peering-how-your-requests-reach-github/', '網路轉接與對等互連：你的請求如何抵達 GitHub', 'GitHub 說明網際網路流量如何透過轉接與對等互連抵達它的資料中心。', ['網路轉接與對等互連的差別', 'BGP 路由', '邊緣節點的角色', '網路容量與備援']],
      ['https://labs.spotify.com/2018/08/31/smoother-streaming-with-bbr/', 'Spotify 以 BBR 讓音樂串流更順暢', 'Spotify 測試 BBR 壅塞控制演算法，減少串流卡頓。', ['TCP 壅塞控制的角色', 'BBR 與傳統演算法的差異', '實驗設計', '對卡頓率的改善']],
    ],
  },
  {
    id: 'w-talk-infra',
    group: '借鏡',
    name: '演講：分散式系統與可靠性',
    question: '建造過大系統的人，最常提醒哪些事？',
    lessons: [
      ['https://www.youtube.com/watch?v=Y6Ev8GIlbxc', '一堂課看懂分散式系統', 'Tim Berglund 以淺顯的方式，從單機資料庫一路講到分散式儲存、運算與訊息。', ['讀取副本與分片', '一致性雜湊', '分散式運算', '分散式訊息']],
      ['https://www.usenix.org/conference/srecon17americas/program/presentation/erlich', 'Facebook 打造即時基礎設施', 'Facebook 工程師分享即時訊息與推播基礎設施的設計與維運。', ['即時推播的需求', '大量長連線', '發布／訂閱架構', '可靠性']],
      ['https://www.usenix.org/conference/srecon16/program/presentation/alvidrez', '為 Google 打造可靠的社交基礎設施', 'Google 經理分享打造社交產品基礎設施時的可靠性經驗。', ['社交產品的可靠性需求', '服務之間的相依', '容量規劃', '從事故中學習']],
      ['https://www.youtube.com/watch?v=K8YuavUy6Qc', 'Google 規模的分散式建置系統', '演講介紹 Google 如何以分散式建置系統處理龐大的單一儲存庫。', ['巨型儲存庫的建置挑戰', '可重現的建置', '遠端快取與遠端執行', '建置的正確性']],
      ['https://www.youtube.com/watch?v=ggizCjUCCqE', 'Dropbox 的網站可靠性工程', 'Dropbox 網站可靠性工程經理分享團隊的工作方式與經驗。', ['網站可靠性工程的職責', '值班與事故處理', '混沌工程', '可靠性文化']],
      ['https://www.youtube.com/watch?v=H4vMcD7zKM0', 'Google 如何維運行星規模的基礎設施', 'Google 雲端的網站可靠性工程總監分享維運大規模基礎設施的原則。', ['錯誤預算', '服務水準目標', '減少重複勞動', '事後檢討文化']],
      ['https://www.youtube.com/watch?v=CZ3wIuvmHeM&t=2837s', 'Netflix 的微服務指南', 'Josh Evans 以生動的比喻，說明 Netflix 在微服務上遇到的問題與解法。', ['相依關係與連鎖故障', '規模帶來的挑戰', '多樣性與標準化', '變更管理']],
      ['https://www.youtube.com/watch?v=1-3Ahy7Fxsc', '在大型線上服務中達成快速回應', 'Jeff Dean 說明在尾端延遲無法避免的情況下，如何讓整體回應時間仍維持快速。', ['尾端延遲的放大效應', '對沖請求', '綁定請求與取消', '以選擇性複寫降低延遲']],
      ['https://www.youtube.com/watch?v=QCHiNEw73AU', 'Facebook 的規模經驗', 'Facebook 工程總監分享網站快速成長時學到的擴展教訓。', ['快速迭代與擴展的平衡', '快取與資料庫', '故障處理', '工程文化']],
      ['https://atscaleconference.com/videos/performance-scale-2018-opening-remarks/', 'Facebook 以效能支撐擴展', 'Facebook 基礎設施副總裁在研討會開場分享效能對擴展的重要性。', ['效能與基礎設施成本', '軟硬體的共同設計', '效能工程的組織', '持續的效能改善']],
      ['https://atscaleconference.com/videos/solving-large-scale-data-center-and-cloud-interconnection-problems/', '解決大規模資料中心與雲端互連問題', 'Equinix 技術長分享資料中心與雲端之間互連的挑戰與解法。', ['資料中心互連的需求', '多雲連接', '網路延遲與頻寬', '互連的架構']],
      ['https://www.youtube.com/watch?v=wzsxJqeVIhY&list=PLMu8-hpCxIVENuAue7bd0eCAglLGY_8AW&index=7', '阿里巴巴的高效能封包處理平台', '阿里巴巴分享高效能網路封包處理平台的設計。', ['軟體封包處理的效能挑戰', '繞過核心的封包處理', '多核心的平行處理', '應用情境']],
      ['https://www.salesforce.com/video/1757880/', 'Salesforce 為大中華區最佳化效能', 'Salesforce 企業架構師分享為大中華區使用者改善效能的做法。', ['跨境網路的延遲', '就近部署與加速', '靜態資源的最佳化', '效能量測']],
      ['https://www.youtube.com/watch?v=bxhYNfFeVF4', 'Facebook 擴展負載平衡以支撐十三億使用者', 'Facebook 正式環境工程師說明多層負載平衡架構。', ['DNS 導流', '邊緣與資料中心的負載平衡', '第四層與第七層負載平衡', '容量與故障處理']],
      ['https://www.youtube.com/watch?v=tbqcsHg-Q_o', 'Netflix 擴展全球內容傳遞網路', 'Netflix 全球網路總監分享 Open Connect 內容傳遞網路的設計。', ['自建內容傳遞網路的理由', '在網路業者機房內部署快取伺服器', '離峰時預先填充內容', '全球擴展']],
    ],
  },
  {
    id: 'w-talk-scale',
    group: '借鏡',
    name: '演講：擴展的故事',
    question: '別人在流量暴增的那一天，做了哪些決定？',
    lessons: [
      ['https://www.youtube.com/watch?v=N8NWDHgWA28', 'Shopify 處理每秒八萬次請求的搶購架構', 'Shopify 說明如何撐住名人商品開賣時的瞬間流量。', ['瞬間流量的特性', '以分區隔離商店', '限流與排隊', '韌性測試']],
      ['https://vimeo.com/252367076', 'GIPHY 如何把動圖送給三億使用者', 'GIPHY 工程師分享動圖傳遞背後的架構。', ['動圖的儲存與轉碼', '內容傳遞網路', '搜尋服務', '流量的擴展']],
      ['https://www.youtube.com/watch?v=PE4gwstWhmc', '擴展 Dropbox', 'Dropbox 早期後端工程師分享網站快速成長時的擴展經驗。', ['早期架構的瓶頸', '資料庫的擴展', '先用簡單的解法', '量測與監控']],
      ['https://www.youtube.com/watch?v=IO4teCbHvZw', 'Facebook 把直播擴展到十億使用者', 'Facebook 工程總監說明直播服務如何處理大量同時觀看。', ['直播的延遲需求', '熱門直播的流量集中', '邊緣快取與請求合併', '可靠性']],
      ['https://www.youtube.com/watch?v=hnpzNAPiC0E', 'Instagram 擴展基礎設施', 'Instagram 工程師分享擴展到多個資料中心並提升效率的經驗。', ['擴展到多個資料中心', '資料的複寫', '效率與效能改善', '維持開發速度']],
      ['https://www.youtube.com/watch?v=6OvrFkLSoZ0', 'Twitter 擴展基礎設施', 'Twitter 工程師分享快取與基礎設施的擴展經驗。', ['快取叢集的規模', '快取的效能', '基礎設施的標準化', '維運經驗']],
      ['https://www.youtube.com/watch?v=LfqyhM1LeIU', 'Etsy 擴展基礎設施', 'Etsy 工程經理分享基礎設施的擴展經驗。', ['基礎設施的演進', '資料庫擴展', '部署文化', '監控']],
      ['https://atscaleconference.com/videos/scaling-alibabas-real-time-infrastructure-for-global-shopping-holiday/', '阿里巴巴為全球購物節擴展即時基礎設施', '阿里巴巴分享購物節期間即時資料處理的架構。', ['購物節的流量高峰', '即時計算平台', '容量規劃', '穩定性保障']],
      ['https://www.youtube.com/watch?v=cdsfRXr9pJU', 'Spotify 擴展資料基礎設施', 'Spotify 工程師分享資料基礎設施的擴展經驗。', ['資料量的成長', 'Hadoop 叢集', '遷移到雲端', '資料工具']],
      ['https://www.youtube.com/watch?v=jQNCuD_hxdQ&list=RDhnpzNAPiC0E&index=11', '擴展 Pinterest', 'Pinterest 創始工程師分享從小流量擴展到大規模的歷程與教訓。', ['早期技術選擇的錯誤', '保持架構簡單', '分片 MySQL', '成熟技術的價值']],
      ['https://www.infoq.com/presentations/slack-scalability', '擴展 Slack', 'Slack 基礎設施工程師分享訊息服務的擴展經驗。', ['以工作區分片的架構', '即時訊息服務', '大型企業客戶的挑戰', '快取與一致性']],
      ['https://www.youtube.com/watch?v=5yDO-tmIoXY&feature=youtu.be', '擴展 YouTube 後端', 'YouTube 工程師分享資料庫擴展的經驗，以及 Vitess 的誕生。', ['MySQL 的擴展瓶頸', '分片與路由層', 'Vitess 的角色', '連線池與查詢保護']],
      ['https://www.youtube.com/watch?v=nuiLcWE8sPA', '擴展 Uber 後端', 'Uber 首席系統架構師分享即時派車系統的擴展。', ['即時派車的需求', '地理空間索引', '服務的擴展', '可用性設計']],
      ['https://www.youtube.com/watch?v=RlkCdM_f3p4', '把大型影音網站擴展到每天兩億次瀏覽', 'MindGeek 平台開發主管分享高流量網站的擴展經驗。', ['高流量網站的架構', '快取策略', '內容傳遞', '資料庫擴展']],
      ['https://www.infoq.com/presentations/quora-analytics', 'Quora 擴展計數基礎設施', 'Quora 工程師分享大規模計數與分析基礎設施的設計。', ['計數的需求', '即時與批次計算', '儲存設計', '擴展方式']],
      ['https://www.youtube.com/watch?v=g_MPGU_m01s', '擴展微軟的 Git', '微軟分享把 Windows 開發搬到 Git，並擴展到大量工程師的經驗。', ['巨型儲存庫的挑戰', '虛擬檔案系統', '伺服器端的擴展', '開發者體驗']],
      ['https://www.youtube.com/watch?v=F-f0-k46WVk', 'Shopify 跨多個資料中心擴展多租戶架構', 'Shopify 說明如何把多租戶架構擴展到多個資料中心。', ['以分區隔離商店', '跨資料中心移轉', '商店的搬移', '故障隔離']],
    ],
  },
  {
    id: 'w-org-team',
    group: '團隊',
    name: '職級與團隊擴展',
    question: '擴展團隊的目標，是人數變多，還是產出變多？',
    lessons: [
      ['https://developers.soundcloud.com/blog/engineering-levels', 'SoundCloud 的工程職級', 'SoundCloud 說明工程職級的設計，讓工程師清楚自己的成長方向。', ['職級的定義', '技術與影響力的期望', '晉升流程', '職級與薪資的關係']],
      ['https://medium.com/palantir/dev-versus-delta-demystifying-engineering-roles-at-palantir-ad44c2a6e87', 'Palantir 的兩種工程角色', 'Palantir 說明專注產品的開發工程師，與貼近客戶的部署工程師有什麼不同。', ['開發工程師的職責', '部署工程師的職責', '兩者的協作', '適合的人格特質']],
      ['https://dropbox.tech/culture/our-updated-engineering-career-framework', 'Dropbox 的工程職涯框架', 'Dropbox 公開工程職涯框架，說明各職級的期望與評估方式。', ['職涯框架的用途', '各職級的期望', '影響力與範圍', '公開透明的好處']],
      ['https://www.youtube.com/watch?v=-PXi_7Ld5kU', 'Twitter 擴展工程團隊', 'Twitter 演講分享工程團隊快速成長時的組織與流程經驗。', ['團隊成長的痛點', '組織結構的調整', '溝通與決策', '維持工程品質']],
      ['https://engineering.linkedin.com/blog/2018/03/scaling-decision-making-across-teams-within-linkedin-engineering', 'LinkedIn 跨團隊擴展決策', 'LinkedIn 說明如何讓大量團隊在技術決策上保持一致，又不失效率。', ['決策瓶頸', '技術決策的流程', '文件與審查', '讓決策可以擴展']],
      ['https://blog.gojekengineering.com/the-dynamics-of-scaling-an-organisation-cb96dbe8aecd', 'GO-JEK 擴展組織的動態', 'GO-JEK 分享資料科學團隊與組織擴展時的經驗。', ['組織擴展的挑戰', '團隊結構', '招募與文化', '溝通']],
      ['https://engineering.zalando.com/posts/2018/05/scaling-agile-zalando.html', 'Zalando 擴展敏捷開發', 'Zalando 說明在大型組織中擴展敏捷開發的做法。', ['大規模敏捷的挑戰', '團隊的自主與對齊', '規劃流程', '持續改善']],
      ['https://hackernoon.com/how-we-run-bol-com-with-60-autonomous-teams-fe7a98c0759', 'bol.com 以六十個自主團隊運作', 'bol.com 說明如何讓六十個自主團隊運作並保持對齊。', ['自主團隊的設計', '團隊之間的對齊', '架構與組織的關係', '領導方式']],
      ['https://blog.intercom.com/how-we-build-software/', 'Intercom 擴展產品團隊的經驗', 'Intercom 分享打造軟體的方式，以及產品團隊擴展時的教訓。', ['小步快跑的出貨節奏', '先定義問題', '團隊結構', '品質與速度']],
      ['https://medium.com/@eleonorazucconi/toby-oliver-cto-typeform-on-hiring-managing-and-scaling-engineering-teams-86bef9e5a708', 'Typeform 的招募、管理與團隊擴展', 'Typeform 技術長分享招募、管理與擴展工程團隊的心得。', ['招募的標準', '新人的融入', '管理者的角色', '團隊擴展的節奏']],
      ['https://instagram-engineering.com/scaling-the-datagram-team-fc67bcf9b721', 'Instagram 擴展資料基礎設施團隊', 'Instagram 分享資料基礎設施團隊的擴展經驗。', ['團隊的職責範圍', '招募與成長', '支援與自助', '優先順序的管理']],
      ['https://medium.com/flexport-design/designing-a-design-team-a9a066bc48a5', 'Flexport 設計一個設計團隊', 'Flexport 說明如何從零建立並擴展設計團隊。', ['設計團隊的定位', '招募', '與工程和產品的協作', '設計文化']],
      ['https://medium.com/salesforce-ux/the-salesforce-team-model-for-scaling-a-design-system-d89c2a2d404b', 'Salesforce 擴展設計系統的團隊模式', 'Salesforce 說明設計系統團隊的組織模式與運作方式。', ['集中式與聯邦式團隊', '設計系統的貢獻流程', '與產品團隊的協作', '治理與採用']],
      ['https://medium.com/wish-engineering/scaling-the-analytics-team-at-wish-part-4-recruiting-2a9823b9f5a', 'Wish 擴展分析團隊：招募篇', 'Wish 擴展分析團隊的系列文章，本篇聚焦招募。', ['分析人才的招募標準', '面試流程', '新人培養', '團隊結構']],
      ['https://medium.com/transferwise-ideas/from-2-founders-to-1000-employees-how-a-small-scale-startup-grew-into-a-global-community-9f26371a551b', 'TransferWise 從兩位創辦人成長到一千名員工', 'TransferWise 分享新創公司成長為全球組織的歷程與文化。', ['自主團隊的組織方式', '文化的維持', '快速成長的挑戰', '溝通與透明']],
      ['https://medium.com/thinking-design/lessons-learned-growing-a-ux-team-from-10-to-170-f7b47be02262', 'Adobe 把使用者體驗團隊從十人擴展到一百七十人', 'Adobe 分享使用者體驗團隊快速擴張時學到的教訓。', ['招募的節奏', '團隊結構', '維持設計品質', '與產品組織的關係']],
      ['https://medium.com/@sarahtavel/five-lessons-from-scaling-pinterest-6a699a889b08', 'Pinterest 擴展的五個教訓', 'Pinterest 早期成員分享公司擴展過程中的五個教訓。', ['專注在核心使用者', '以資料做決策', '招募的標準', '文化的建立']],
      ['http://engineering.vinted.com/2018/09/04/how-we-approach-engineering-at-vinted/', 'Vinted 的工程方式', 'Vinted 說明工程團隊的原則、組織與工作方式。', ['工程原則', '團隊組織', '技術決策', '持續改善']],
    ],
  },
  {
    id: 'w-org-culture',
    group: '團隊',
    name: '工程文化與協作',
    question: '好的工程文化，是靠哪些日常做法累積出來的？',
    lessons: [
      ['https://engineering.indeedblog.com/blog/2018/10/using-metrics-to-improve-the-development-process-and-coach-people/', 'Indeed 以指標改善開發流程並輔導同仁', 'Indeed 說明如何用開發流程的指標找出瓶頸，並作為輔導而非考核的工具。', ['開發流程指標的選擇', '以指標找出瓶頸', '避免指標被濫用', '以指標進行輔導']],
      ['https://medium.com/@SkyscannerEng/9-mistakes-to-avoid-while-creating-an-internal-product-63d579b00b1a', 'Skyscanner：打造內部產品要避免的九個錯誤', 'Skyscanner 整理打造內部平台與工具時常見的錯誤。', ['沒有把內部使用者當成客戶', '缺乏產品思維', '推廣與支援不足', '沒有衡量採用程度']],
      ['https://codeascraft.com/2018/01/04/selecting-a-cloud-provider/', 'Etsy 以責任分配矩陣選擇雲端供應商', 'Etsy 在選擇雲端供應商時，以負責、當責、諮詢、告知四種角色分工，推動大型決策。', ['責任分配矩陣的四種角色', '大型技術決策的流程', '評估雲端供應商的面向', '跨團隊的溝通']],
      ['https://engineering.zalando.com/posts/2018/10/four-pillars-leadership.html', 'Zalando 領導的四大支柱：同理、啟發、信任、誠實', 'Zalando 分享領導團隊的四個核心原則。', ['同理心', '啟發與願景', '建立信任', '誠實的回饋']],
      ['https://engineering.shopify.com/blogs/engineering/pair-programming-explained', 'Shopify 的結對程式設計', 'Shopify 說明結對程式設計的做法、好處與常見誤解。', ['駕駛與導航兩種角色', '結對的好處：知識分享與品質', '遠端結對', '什麼時候適合結對']],
      ['https://blog.asana.com/2017/12/distributed-responsibility-engineering-manager/', 'Asana 的分散式責任', 'Asana 把工程經理的職責拆給不同的人承擔，讓責任更清楚。', ['工程經理職責過多的問題', '把責任分散給多個角色', '清楚的負責範圍', '對團隊的影響']],
      ['https://engineering.zalando.com/posts/2019/03/rotating-engineers-at-zalando.html', 'Zalando 的工程師輪調', 'Zalando 讓工程師在團隊之間輪調，促進知識分享與成長。', ['輪調的目的', '輪調的流程', '對個人與團隊的好處', '遇到的挑戰']],
      ['https://medium.com/pinterest-engineering/how-pinterest-supercharged-its-growth-team-with-experiment-idea-review-fd6571a02fb8', 'Pinterest 以實驗構想審查加速成長團隊', 'Pinterest 在實驗開始前先審查構想，提高實驗的品質與成功率。', ['實驗構想審查的流程', '事前定義假設與指標', '減少無效實驗', '知識的累積']],
      ['https://engineering.atspotify.com/2020/06/25/tech-migrations-the-spotify-way/', 'Spotify 的技術遷移方式', 'Spotify 說明如何在大量自主團隊中推動技術遷移。', ['技術遷移的困難', '讓遷移變得容易', '追蹤遷移進度', '遷移的優先順序']],
      ['https://engineeringblog.yelp.com/2021/01/whose-code-is-it-anyway.html', 'Yelp 改善程式碼的負責歸屬', 'Yelp 說明如何釐清程式碼的負責團隊，讓問題能找到對的人。', ['程式碼無人負責的問題', '記錄負責資訊', '自動化的負責人對應', '維持資訊正確']],
      ['https://tech.ebayinc.com/engineering/how-creating-an-agile-code-base-helped-ebay-pivot-for-apple-silicon/', 'eBay 以敏捷的程式碼庫快速支援 Apple Silicon', 'eBay 說明良好的程式碼庫結構，如何讓團隊快速因應平台變化。', ['程式碼庫的模組化', '自動化建置與測試', '快速因應平台變化', '技術債的管理']],
      ['https://medium.com/miro-engineering/agile-data-engineering-at-miro-ec2dcc8a3fcb', 'Miro 的敏捷資料工程', 'Miro 分享把敏捷方法應用在資料工程團隊的經驗。', ['資料工程的特性', '迭代式交付', '與需求方的協作', '品質與測試']],
      ['https://medium.com/airbnb-engineering/incident-management-ae863dc5d47f', 'Airbnb 透過 Slack 自動化事故管理', 'Airbnb 以聊天機器人自動化事故的建立、通知與追蹤。', ['事故管理的流程', '以聊天工具集中溝通', '自動化的通知與記錄', '事後檢討']],
      ['https://medium.com/bbc-product-technology/refactor-organisation-80e4e171d922', 'BBC 重構組織', 'BBC 以「重構」的觀念調整組織結構，讓團隊更有效率。', ['組織也需要重構', '康威定律', '團隊邊界的調整', '漸進式的改變']],
    ],
  },
  {
    id: 'w-review',
    group: '團隊',
    name: '程式碼審查',
    question: '審查程式碼時，你是在找錯，還是在傳承？',
    lessons: [
      ['https://ai.google/research/pubs/pub47025', '現代程式碼審查：Google 的案例研究', 'Google 的研究論文，分析內部程式碼審查的動機、流程與成效。', ['程式碼審查的動機：教育、規範與把關', '變更小、審查者少的特性', '審查速度', '審查中的常見問題']],
      ['https://medium.com/@palantir/code-review-best-practices-19e02780015f', 'Palantir 的程式碼審查最佳實務', 'Palantir 整理程式碼審查的目的、準備與審查重點。', ['程式碼審查的目的', '提交者的準備', '審查者該看什麼', '溝通的語氣']],
      ['https://engineering.linecorp.com/en/blog/effective-code-review/', 'LINE 的有效程式碼審查', 'LINE 分享讓程式碼審查更有效率的做法。', ['審查的目標', '小而清楚的變更', '審查意見的寫法', '自動化檢查']],
      ['https://medium.engineering/code-reviews-at-medium-bed2c0dce13a', 'Medium 的程式碼審查', 'Medium 說明程式碼審查的原則與流程。', ['審查的原則', '審查的時效', '審查意見的分類', '團隊文化']],
      ['https://engineering.linkedin.com/blog/2018/06/scaling-collective-code-ownership-with-code-reviews', 'LinkedIn 以程式碼審查擴展集體所有權', 'LinkedIn 說明如何透過程式碼審查，讓大家共同維護程式碼。', ['集體程式碼所有權的概念', '審查者的選擇', '審查品質', '擴展到大量工程師']],
      ['https://medium.com/disney-streaming/the-secret-to-better-code-reviews-c14c7884b9ac', 'Disney 讓程式碼審查更好的祕訣', 'Disney 串流團隊分享改善程式碼審查的具體做法。', ['審查前的自我檢查', '提供脈絡', '具體的回饋', '審查的節奏']],
      ['https://www.netlify.com/blog/2020/03/05/feedback-ladders-how-we-encode-code-reviews-at-netlify/', 'Netlify 的回饋階梯：為審查意見標示輕重', 'Netlify 以山、石、沙、塵等比喻標示審查意見的嚴重程度，讓溝通更清楚。', ['審查意見輕重不明的問題', '回饋階梯的等級', '區分必須修改與建議', '減少誤解']],
    ],
  },
];
